ej2-asp-core-mvc/breadcrumb/EJ2_ASP.NETCORE/overflow.md

Have changed overflow mode in breadcrumb UG Docs and referred images with code-snippet files individually

(EJ2-59206): Breadcrumb Documentation in asp-core-mvc

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/adding-script-references.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/security-aspects.md

ASP.NET Core script nonce changes moved to hotfix.

documentation(EJ2CORE-781): ASP.NET Core script nonce changes moved to hotfix.

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/feature-module.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/toolbar.md

Resolve the dead link by providing the proper link.

documentation(EJ2-60275): Resolve the dead link on a documentation page

---

ej2-asp-core-mvc/message/EJ2_ASP.MVC/customization.md
ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/customization.md

Need to resolve the file path issue for message
Included the improper file names.
Find how it was missed in our earlier testing and development by analysing the below checklist. This will help prevent similar mistakes in the future. 
- Specification document
- Requirement document
- Common guidelines / Core team guideline
- Specification document
- Requirement document
Common guidelines not followed.
Manual testing.
NA
No
Included proper file names.
NA.
NA
- Did you run the automation against your fix?No
- Is there any API name change?No
- Is there any existing behavior change of other features due to this code change?No
- Does your new code introduce new warnings or binding errors?No
- Does your code pass all FxCop and StyleCop rules?NA
- Did you record this case in the unit test or UI …

documentation(EJ2-65405): Need to resolve file path issue for Message

---

ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/icons.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/positions.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/styles.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.NETCORE/icons.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.NETCORE/positions.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.NETCORE/styles.md

Need to update UG heading casing and API links in ASP.NET Core and ASP.NET MVC platform
Update UG heading casing and API links for Floating Action Button.
NA 
NA
NA

documentation(BLAZ-26909): FAB heading and api links updated

---

ej2-asp-core-mvc/carousel/EJ2_ASP.NETCORE/navigators-and-indicators.md

The position of the indicatorsType documentation is wrong so changed the position of the sample.

bug(836659): indicators Type documentation location is wrong

---

ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/timezone.md

Updated code snippets for NET Core Web App 3.0 for Timezone topic in scheduler
NA
NA

Documentation(SC-43825): Added code snippets for converting .NET Core Web App from 2.2 code to 3.0 for Timezone topic in scheduler.

---

ej2-asp-core-mvc/accordion/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/appbar/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/carousel/EJ2_ASP.MVC/populating-items.md
ej2-asp-core-mvc/carousel/EJ2_ASP.NETCORE/populating-items.md
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/tab/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/tab/how-to/create-wizard-using-tab.md
ej2-asp-core-mvc/tab/how-to/prevent-content-swipe-selection.md
ej2-asp-core-mvc/toolbar/EJ2_ASP.MVC/getting-started.md

Description:
Fix the link navigate issue and mapping api links in core and mvc  documentation
Test cases:
NA
NA

documentation(ES-837798-Core-and-mvc-docs): mapping the api links and fix navigate link issues

---

ej2-asp-core-mvc/code-snippet/appbar/size-and-color/prominent/razor
ej2-asp-core-mvc/code-snippet/appbar/size-and-color/prominent/tagHelper

Resolved image not displayed issue in Prominent AppBar core and mvc preview sample documentation
NA
NA

Documentation(ES-819678): Resolved image not displayed issue in Prominent AppBar core and mvc preview sample

---

ej2-asp-core-mvc/code-snippet/uploader/localization/razor
ej2-asp-core-mvc/uploader/localization.md

Need to add localization text for 'Total files' and 'Size'
We have not added the for L10 for `Total files` and `Size` details to our documentaion.
To resolve this issue, to add the L10 for  `Total files` and `Size` details to our documentaion.
- Ensure the changes affects others functionalities.
Provide details about the areas or combinations that have been tested against these code changes.
Need to Ensure properly on Future implementation.
Already covered this bunit and got failed now.
Is this common issue need to be addressed in the same component or on other …

bug(857645):Need to add localization text for 'Total files' and 'Size'

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/table.md

To validate and resolve the liquid exception error in RTE documentation sample.
I have checked the reported issue, and the issue occurred because the path is not properly referred in the table.md file
No
No
I have removed the commend text in the table.md file.
No
No
No
No
/label ~bug

847030: To validate and resolve the liquid exception error in RTE documentation sample.

---

ej2-asp-core-mvc/query-builder/clone-group-rule.md
ej2-asp-core-mvc/query-builder/import-export.md
ej2-asp-core-mvc/query-builder/lock-group-rule.md

Modify Querybuilder UG Content for Import-Export, Lock and Clone Samples

878261: Modify Querybuilder UG Content for Import-Export, Lock and Clone Samples

---

ej2-asp-core-mvc/document-editor/collaborative-editing.md

Removed preview tag and note point from the collaborative editing file

877243: Removed preview from collaborative editing

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/form-designer/create-programmatically.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/form-designer/create-with-user-interface-interaction.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/toolbar-icon-customization.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/open-pdf-file/from-amazon-s3.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/open-pdf-file/from-azure-blob-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/open-pdf-file/from-box-cloud-file-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/open-pdf-file/from-google-cloud-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/open-pdf-file/from-google-drive.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/save-pdf-file/to-amazon-s3.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/save-pdf-file/to-azure-blob-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/save-pdf-file/to-box-cloud-file-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/save-pdf-file/to-google-cloud-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/save-pdf-file/to-google-drive.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/form-designer/create-programmatically.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/form-designer/create-with-user-interface-interaction.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/getting-started-with-server-backed.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/toolbar-icon-customization.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/open-pdf-file/from-amazon-s3.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/open-pdf-file/from-azure-blob-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/open-pdf-file/from-box-cloud-file-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/open-pdf-file/from-google-cloud-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/open-pdf-file/from-google-drive.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/save-pdf-file/to-amazon-s3.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/save-pdf-file/to-azure-blob-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/save-pdf-file/to-box-cloud-file-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/save-pdf-file/to-google-cloud-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/save-pdf-file/to-google-drive.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

The folder structure is proper in the master and latest hotfix branches.  so modify the folder structure manually in the development branch.

380478: FormDesigner folder is modified as hotfix branch 

---

ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-blob/document-editor.cs
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-blob/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-blob/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-docx/document-editor.cs
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-docx/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-docx/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-dotx/document-editor.cs
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-dotx/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-dotx/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-sfdt/document-editor.cs
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-sfdt/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-sfdt/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-txt/document-editor.cs
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-txt/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/export-container-txt/tagHelper
ej2-asp-core-mvc/document-editor/export.md

Added documentation for preview sample of document editor container. Added word template(.dotx) in the heading which was missing earlier. Added code snippet column in the api table.

877298: Added documentation for preview sample of document editor container

---

ej2-asp-core-mvc/code-snippet/document-editor-container/toggle-track-pane/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/toggle-track-pane/tagHelper
ej2-asp-core-mvc/document-editor/track-changes.md

Added documentation for toggle track pane in track-changes.md file .

380577: Added documentation for toggle track pane

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/getting-started.md

The note section regarding limitations has been updated. The standalone PDF Viewer now includes support for PNG images, thus removing the limitation associated with PNG image compatibility.

884073: Note section in standalone PDF Viewer is updated

---

ej2-asp-core-mvc/document-editor/export.md

Resolved the format error.

---

ej2-asp-core-mvc/dashboard-layout/interaction-with-panels/dragging-of-panels.md

kindly review the multiple h1 changes.
Regards,
Edith.

SEO-182398-core-mvc-dashboard-layout-Multiple-h1

---

ej2-asp-core-mvc/document-editor/collaborative-editing.md

Hi,
Kindly review my content on "How to perform Scaling in Collaborative Editing application" and provide your feedback.
Regards,
Akshaya

882104 - Add UG for scaling in collaborative editing

---

ej2-asp-core-mvc/code-snippet/chart/axis/working-data/remote-data/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/remote-data/tagHelper

Changed service link in remote sample.

885456: Changes service link in ASP.NET Core and ASP.NET MVC documentation.

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/pivot-chart.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/pivot-chart.md

Bullet points are missing under the drill-up/drill-down topic. Thus, we need to update it.

882947: Need to include bullet points in the pivot chart drill down topic

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/file-browser/controller.cs

Need to move the web service link into 'services.syncfusion.com' from 'ej2services.syncfusion.com
Updating the sample host URLs
No
No
Updating the sample host URLs
Yes
No
No
No
/label ~bug

889328: Need to move the web service link into 'services.syncfusion.com' from 'ej2services.syncfusion.com

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/data-binding/remote-data.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/getting-started-mvc.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/data-binding/remote-data.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/getting-started-core.md
ej2-asp-core-mvc/tree-grid/overview.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Getting started changes in core and mvc platform

documentation(888757): databinding changes

---

ej2-asp-core-mvc/code-snippet/diagram/connectors/connectorCollection/connectorCollection.cs
ej2-asp-core-mvc/code-snippet/diagram/connectors/connectorCollection/tagHelper
ej2-asp-core-mvc/code-snippet/diagram/group/groupCollection/groupCollection.cs
ej2-asp-core-mvc/code-snippet/diagram/group/groupCollection/tagHelper
ej2-asp-core-mvc/code-snippet/diagram/node/nodescollection/nodescollection.cs
ej2-asp-core-mvc/code-snippet/diagram/node/nodescollection/tagHelper
ej2-asp-core-mvc/diagram/connectors.md
ej2-asp-core-mvc/diagram/group.md
ej2-asp-core-mvc/diagram/nodes.md

Update the UG Documentation for the Add Elements feature with needed files and samples.

Provide support to add diagram nodes or connectors collection dynamically through API method

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/basic/default/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/basic/default/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/getting-started.md

To update documentation for the getting started in the Rich Text Editor for all platforms
No
No
No
No
No
No
/label ~bug

890543: To update the getting started documentation page in the Rich text editor component in JS, TS, Core, and MVC platforms

---

ej2-asp-core-mvc/code-snippet/textarea/rows-cols/razor
ej2-asp-core-mvc/code-snippet/textarea/rows-cols/tagHelper
ej2-asp-core-mvc/textarea/rows-columns.md

Textarea component rows and colums property changes in Documentation on EJ2 Platform
Need to add Textarea component rows and colums property changes in Documentation on EJ2 Platform
Added Textarea component rows and colums property changes in Documentation on EJ2 Platform
NA
NA
Is there …

890708: Textarea component documentation in Blazor

---

ej2-asp-core-mvc/spreadsheet/keyboard-shortcuts.md

Description:
Added content for the newly added keyboard shortcuts in Spreadsheet.

 documentation(891499): Added content for the newly added keyboard shortcuts.

---

ej2-asp-core-mvc/multicolumn-combobox/EJ2_ASP.MVC/virtualization.md
ej2-asp-core-mvc/multicolumn-combobox/EJ2_ASP.NETCORE/virtualization.md

Need to fix the documentation failures due to the MCCB component.

UG(892244): Fixed documentation failure due to code snippet file path.

---

ej2-asp-core-mvc/code-snippet/spreadsheet/open-from-json/openController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/open-from-json/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/open-from-json/tagHelper
ej2-asp-core-mvc/code-snippet/spreadsheet/save-as-json/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/save-as-json/saveController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/save-as-json/tagHelper
ej2-asp-core-mvc/spreadsheet/open-save.md

Description:
Added code sample and UG content for Save as json feature.

Documentation(EJ2-891499): Added code sample and UG content for  json serialization feature.

---

ej2-asp-core-mvc/code-snippet/accordion/getting-started/contenttemplate/tagHelper
ej2-asp-core-mvc/code-snippet/accordion/how-to/partial-view/razor
ej2-asp-core-mvc/code-snippet/accordion/how-to/partial-view/tagHelper
ej2-asp-core-mvc/code-snippet/schedule/data-binding/Odata/razor
ej2-asp-core-mvc/code-snippet/schedule/data-binding/Odata/tagHelper
ej2-asp-core-mvc/code-snippet/schedule/data-binding/additional-parameter/razor
ej2-asp-core-mvc/code-snippet/schedule/data-binding/additional-parameter/tagHelper
ej2-asp-core-mvc/code-snippet/schedule/data-binding/custom-adaptor/razor
ej2-asp-core-mvc/code-snippet/schedule/data-binding/custom-adaptor/tagHelper
ej2-asp-core-mvc/code-snippet/tab/partial-view/razor
ej2-asp-core-mvc/code-snippet/tab/partial-view/tagHelper

Changed the new Service link from old Service link.

888062: Changing the new service link from old link.

---

ej2-asp-core-mvc/code-snippet/chart/axis/working-data/custom-adaptor/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/custom-adaptor/tagHelper
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/offline-mode/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/offline-mode/tagHelper
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/web-adaptor/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/web-adaptor/tagHelper

889696: Change the service link for Core and MVC documentation..

---

ej2-asp-core-mvc/code-snippet/document-editor/add-save-button-in-toolbar/document-editor.cs
ej2-asp-core-mvc/code-snippet/document-editor/add-save-button-in-toolbar/razor
ej2-asp-core-mvc/code-snippet/document-editor/add-save-button-in-toolbar/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor/auto-save-server/razor
ej2-asp-core-mvc/code-snippet/document-editor/auto-save-server/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor/custom-toolbar/razor
ej2-asp-core-mvc/document-editor/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/document-editor/EJ2_ASP.NETCORE/getting-started-core.md
ej2-asp-core-mvc/document-editor/how-to/add-save-button-in-toolbar.md
ej2-asp-core-mvc/document-editor/how-to/auto-save-document.md
ej2-asp-core-mvc/document-editor/how-to/customize-tool-bar.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added the save toolbar button to custom toolbar and auto save document.

Added the save toolbar button to custom toolbar and auto save document.

---

ej2-asp-core-mvc/document-editor/faq/unsupported-file-format.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added FAQ on why do i get the unsupported warning message when opening document.

895726: Added documentation on unsupported file formats.

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/open-pdf-file/from-amazon-s3.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/save-pdf-file/to-amazon-s3.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/open-pdf-file/from-amazon-s3.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/save-pdf-file/to-amazon-s3.md

Provide sample and steps to load the PDF document from AWS S3 in Standalone PDF Viewer

EJ2 896980 Open PDF file from AWS S3

---

ej2-asp-core-mvc/code-snippet/document-editor-container/comments-mention/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/comments-mention/tagHelper
ej2-asp-core-mvc/document-editor/comments.md

Added the API documentation for insert comments

Added the API documentation for insert comments

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/form-filling.md

Image Content was not properly imported in the PDF Viewer documentation.

EJ2 899030: Content Broken in MVC documentation

---

ej2-asp-core-mvc/document-editor/comments.md

Added insert reply comment, get comment and delete comments api.

899281: Added insert reply comment, get comment and delete comments api.

---

ej2-asp-core-mvc/spreadsheet/open-save.md

Added KB on how to deploy a spreadsheet open and save web API service to AWS Lambda.

documentation(EJ2-894666): Added KB on how to deploy a spreadsheet open and save web API service to AWS Lambda.

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/introduction.md

-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/3276|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187647|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B2A368E74-D539-456F-9819-C9B68637E490%7D&file=Faith.xlsx&action=default&mobileredirect=true|
-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Scr
Changes made | Reason for change
-- | --
| Page with redirect| To increase page performance |

SEO-187489-ej2-Asp.net-core-Introduction-Page-with-redirect-link

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/slashmenu/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/slashmenu/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/slashmenu/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/slash-menu.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/slash-menu.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Make a Slash menu documentation for the Rich Text Editor.
Need to create a slash menu documentation.
No
No
Created a slash menu documentation.
No
No
NA
No
/label ~bug

903423: Make a Slash menu documentation for the Rich Text Editor.

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/print.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/text-search.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/text-search.md

Description:
Highlight tag closed properly in print md file and Lexer issue addressed for text search md files in both core and MVC.

1234: highlight Lexer issue fix and close highlight

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/export/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/export/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/export/tagHelper
ej2-asp-core-mvc/code-snippet/rich-text-editor/import/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/import/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/import/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/import-and-export.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/import-and-export.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

To add documentation for Import/export feature in all the platform except angular
Need to add an Import/export documentation.
No
No
Created an  Import/export documentation.
No
No
NA
No
/label ~bug

914538: To add documentation for Import/export feature in all the platform except angular

---

ej2-asp-core-mvc/diagram/EJ2_ASP.NETCORE/getting-started.md

Updated the 'Getting Started' section in the diagram documentation to include instructions for both Visual Studio and Visual Studio Code environments.

933689: Core Application Getting Started Update

---

ej2-asp-core-mvc/code-snippet/dropdowntree/data-binding/remote-data/razor
ej2-asp-core-mvc/code-snippet/dropdowntree/data-binding/remote-data/remotedata.cs
ej2-asp-core-mvc/code-snippet/dropdowntree/templates/actionFailureTemplate/razor
ej2-asp-core-mvc/code-snippet/dropdowntree/templates/customTemplate_mode/razor
ej2-asp-core-mvc/code-snippet/dropdowntree/templates/footerTemplate/razor
ej2-asp-core-mvc/code-snippet/dropdowntree/templates/headerTemplate/razor
ej2-asp-core-mvc/code-snippet/dropdowntree/templates/itemTemplate/razor
ej2-asp-core-mvc/code-snippet/dropdowntree/templates/valueTemplate/razor

938381: Test and resolve issues in UG all sections - ASP MVC Dropdown Tree control.

938381: Test and resolve issues in UG all sections - ASP MVC Dropdown Tree control.

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/getting-started.md

How to reference resource URL locally in the PDF Viewer without using CDN links?

931453: How to reference resource URL locally in the PDF Viewer without using CDN links?

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/exec-command.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/exec-command.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

877792: modified heading of executeCommand and included insertAudio & insertVideo in RichTextEditor(Mvc/Core)

877792: modified heading of executeCommand and included insertAudio & insertVideo in RichTextEditor(Mvc/Core)

---

ej2-asp-core-mvc/code-snippet/schedule/appointments/prevent-tooltip/data.cs
ej2-asp-core-mvc/code-snippet/schedule/appointments/prevent-tooltip/razor
ej2-asp-core-mvc/code-snippet/schedule/appointments/prevent-tooltip/tagHelper
ej2-asp-core-mvc/code-snippet/schedule/calendar-export/custom-print/data.cs
ej2-asp-core-mvc/code-snippet/schedule/calendar-export/custom-print/razor
ej2-asp-core-mvc/code-snippet/schedule/calendar-export/custom-print/tagHelper
ej2-asp-core-mvc/code-snippet/schedule/excel-export/excel-customize/data.cs
ej2-asp-core-mvc/code-snippet/schedule/excel-export/excel-customize/razor
ej2-asp-core-mvc/code-snippet/schedule/excel-export/excel-customize/tagHelper
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/appointments.md
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/exporting.md
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/virtual-scrolling.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/appointments.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/exporting.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/virtual-scrolling.md

Added the UG documentation for OverScanCount property in tab component.
[Documentation](https://syncfusion.sharepoint.com/:w:/r/sites/EJ2-ClientSide/_layouts/15/doc2.aspx?sourcedoc=%7B1587b7e3-9555-46b4-92e8-24d365bf11db%7D&action=edit)
[947725](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/947725)
NA 
NA
NA
Is there …

947725: Added the UG documentation for overScanCount property.

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/annotation/text-markup-annotation.md

-- | --
|Task Category | Site Audit work- Title too long|
|Content Task Link/Mail Screenshot |![image](https://github.com/user-attachments/assets/c0de89e6-28b9-4552-9871-ce5299d1e7e7)|
|Hotfix |https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/4146 |
|Ticket/Task link |https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/200103 |
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7Bc4d37df0-3f11-4b4c-a5c2-eabff4e4c288%7D&action=edit&activeCell=%27Title%20Too%20Long%27!A5&wdinitialsession=8f0d24f1-fe24-764a-c28b-f181fb1a9b15&wdrldsc=2&wdrldc=1&wdrldr=AccessTokenExpiredWarning%2CRefreshingExpiredAccessT|
|-- | -- |
| Worked on Title too …

SEO-200103-EJ2-ASP.NET-MVC-pdfviewer-Title-too-long

---

ej2-asp-core-mvc/document-editor/how-to/customize-color-picker.md

933118: Added notes for possibility of modifying the predefined highlight colors in Core and MVC.

933118: Added notes for possibility of modifying the predefined highlight colors in Core and MVC.

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/editor-types/inline-editing.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/insert-image-media/audio.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/insert-image-media/insert-images.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/insert-image-media/video.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/smart-editing/emoji-picker.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/smart-editing/mentions.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/tools/built-in-tools.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/tools/text-formatting.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/editor-types/inline-editing.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/editor-types/resizable-editor.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/insert-image-media/audio.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/insert-image-media/insert-images.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/insert-image-media/video.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/smart-editing/emoji-picker.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/smart-editing/mentions.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/tools/built-in-tools.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/tools/text-formatting.md

951777: Corrected the image path -Dev

951777: Corrected the image path -Dev

---

ej2-asp-core-mvc/document-editor/how-to/get-current-word.md
ej2-asp-core-mvc/document-editor/how-to/get-the-selected-content.md

957760: Removed Unwanted codes to resolve documentation compilation error in Documentation

957760: Removed Unwanted codes to resolve documentation compilation error in Documentation

---

ej2-asp-core-mvc/code-snippet/pivot-table/toolbar/save-load-json/razor
ej2-asp-core-mvc/code-snippet/pivot-table/toolbar/save-load-json/tagHelper

Need to update the Core platform toolbar documentation sample.

855594: Need to update the Core platform toolbar documentation sample.

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/text-search.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/text-search.md

Description:
Updated the UG with proper hashtags on heading to resolve sidebar issue

964167: Updated the UG with proper hashtags on heading to resolve sidebar issue

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/clear-undo-redo/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/clear-undo-redo/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/clear-undo-redo/tagHelper
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-bottom/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-bottom/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-bottom/tagHelper
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-popup/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-popup/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-popup/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/toolbar/toolbar-position.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/toolbar/toolbar-types.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/undo-redo.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/toolbar/toolbar-position.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/toolbar/toolbar-types.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/undo-redo.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

* [950709](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/950709) - Create UG Documentation for bottom toolbar, popup toolbar an clear undo redo stack Support in All Platforms
Added the documentation for typescript and javascript sample
* If any other reason, provide the details here.
Test cases did not cover this specific use case.
No
No
Added the documentation for typescript and javascript sample
-Ensured with tests.
NA
No
No
* [] All provided information are reviewed and ensured.

950709: Added the documentation for the popup , bottom toolbar and clearundoredo method

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/show-recent-color/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/show-recent-color/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/show-recent-color/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/tools/styling-tools.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/tools/styling-tools.md

* [965196](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/965196) - UG Documentation for Show Recent Color Support in All Platform Rich Text Editor
Added the documentation for MVC and Core sample
* If any other reason, provide the details here.
Test cases did not cover this specific use case.
No
No
Added the documentation for MVC and Core sample
-Ensured with tests.
NA
No
No
* [] All provided information are reviewed and ensured.

965196: UG Documentation for Show Recent Color Support in All Platform Rich Text Editor

---

ej2-asp-core-mvc/code-snippet/document-editor-container/customize-ribbon-backstage/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/customize-ribbon-backstage/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor-container/customize-ribbon-file/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/customize-ribbon-file/tagHelper
ej2-asp-core-mvc/document-editor/EJ2_ASP.MVC/ribbon.md
ej2-asp-core-mvc/document-editor/EJ2_ASP.NETCORE/ribbon.md
ej2-asp-core-mvc/document-editor/how-to/customize-ribbon.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

967341:  Added the ribbon documentation for asp-core and mvc.

967341: Added the ribbon documentation

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/enable-text-selection.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/enable-text-selection.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Description:
UG Documentation on How to Dynamically enable or disable text selection.

966016: UG Documentation on How to Dynamically enable or disable text selection.

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/scrolling/virtual-scrolling.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/scrolling/virtual-scrolling.md

Removed the column chooser limitation from column virtualization, as support has now been provided.

965638: Updated virtual scroll limitation in development

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/show-hide-annotation.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/show-hide-annotation.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Description:
Show and Hide Annotation UG Docs

845073: Show and Hide Annotation UG Docs

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/image-authenticate/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/image-authenticate/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/insert-image-media/insert-images.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/insert-image-media/insert-images.md

971624: Corrected the event name added in the Secure image upload with authenticatio-HF/Core/MVC1

971624: Corrected the event name added in the Secure image upload with authenticatio-HF/Core/MVC1

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/checklist-cs1/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/checklist-cs1/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/checklist-cs1/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/tools/text-formatting.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/tools/text-formatting.md

[976516](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/976516) -  UG documentation for Checklist feature in the Rich Text Editor.
The checklist documentation was missing and needed to be included.
No.
No
Included the checklist documentation. 
No
No
NA
No
No
/label ~bug

976516: UG documentation for Checklist feature in the Rich Text Editor

---

ej2-asp-core-mvc/ai-assistview/EJ2_ASP.MVC/ai-integrations/gemini-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.MVC/ai-integrations/ollama-llm-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.MVC/ai-integrations/openai-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.NETCORE/ai-integrations/gemini-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.NETCORE/ai-integrations/ollama-llm-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.NETCORE/ai-integrations/openai-integration.md
ej2-asp-core-mvc/code-snippet/ai-assistview/ai-integrations/gemini-ai/geminicore.cs
ej2-asp-core-mvc/code-snippet/ai-assistview/ai-integrations/gemini-ai/geminimvc.cs
ej2-asp-core-mvc/code-snippet/ai-assistview/ai-integrations/gemini-ai/razor
ej2-asp-core-mvc/code-snippet/ai-assistview/ai-integrations/gemini-ai/tagHelper
ej2-asp-core-mvc/code-snippet/ai-assistview/ai-integrations/open-ai/openaicore.cs
ej2-asp-core-mvc/code-snippet/ai-assistview/ai-integrations/open-ai/openaimvc.cs
ej2-asp-core-mvc/code-snippet/ai-assistview/ai-integrations/open-ai/razor
ej2-asp-core-mvc/code-snippet/ai-assistview/ai-integrations/open-ai/tagHelper
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to add UG for the Azure Open AI integration with the AI assistview component in the Core and MVC platform.
[982586](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/982586)
NA
NA
Azure Open Ai
NA
NA
Confirm whether the ensured feature is in both Blazor …

982586: added UG for the Azure Open AI integration with the AI assistview component in the Core and MVC platform

---

ej2-asp-core-mvc/ai-assistview/EJ2_ASP.MVC/ai-integrations/gemini-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.MVC/ai-integrations/openai-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.NETCORE/ai-integrations/gemini-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.NETCORE/ai-integrations/openai-integration.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/bot-integrations/integration-with-bot-framework.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/bot-integrations/integration-with-dialogflow.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/bot-integrations/integration-with-bot-framework.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/bot-integrations/integration-with-dialogflow.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

updated UG concerns in Md file :
gemini ai
azure open ai
bot integration

updated latest concerns in UG(Hotfix)
