syncfusion-content/ej2-asp-core-mvc-docs

ej2-asp-core-mvc/maskedtextbox/style-appearance.md
ej2-asp-core-mvc/numerictextbox/style-appearance.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/textbox/style-appearance.md
ej2-asp-core-mvc/uploader/style-appearance.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

BLAZ-100 - Style and appearance migrated which was missed earlier.

BLAZ-100 - Style and appearance migrated which was missed earlier.

---

ej2-asp-core-mvc/code-snippet/tab/ajax/razor
ej2-asp-core-mvc/code-snippet/tab/ajax/tagHelper
ej2-asp-core-mvc/drop-down-tree/templates.md

BLAZ-100 - Moved latest changes.

BLAZ-100 - Moved latest changes.

---

ej2-asp-core-mvc/calendar/style-appearance.md
ej2-asp-core-mvc/datepicker/style-appearance.md
ej2-asp-core-mvc/daterangepicker/style-appearance.md
ej2-asp-core-mvc/datetimepicker/style-appearance.md
ej2-asp-core-mvc/timepicker/style-appearance.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Style and appearance topics migrated.

BLAZ-100 Style and appearance topics migrated.

---

ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/getting-started-core.md

Customer reported changes merged
https://github.com/syncfusion/ej2-aspnetcore-docs/pull/4

customer changes merged

---

ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/data-binding.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/data-binding.md

In data-binding UG correction for server-side methods.

documentation(EJ2-57924): Data binding UG correction for server side methods

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/right-to-left.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/state-persistence.md
ej2-asp-core-mvc/sparkline/appearance.md.bak

Moved files to resolve conflicts.

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/appearance/size-modes.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/getting-started/aspnet-core-mvc-htmlhelper.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/getting-started/aspnet-core-mvc-taghelper.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/getting-started/client-side-resource.md

Issue in title changes committed.

Issue in title changes committed.

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/toolbar.md

Adding line spacing tool forum in UG See also section

documentation(EJ2-57689): Adding line spacing tool forum in UG

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/appearance/icons.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/areas.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/input-validation.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/internationalization.md

Resolved spacing issues in the ASP.NET core documentation.

documentation(EJ2CORE-722): ASP.NET core documentation changes committed to hotfix.

---

ej2-asp-core-mvc/grid/accessibility.md

Grid accessibility asp changes

documentation(EJ2-58121): Grid accessibility asp changes

---

ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/axis-customization.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/axis-labels.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-annotations.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-print.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/cross-hair-and-track-ball.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/data-editing.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/data-labels.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/data-markers.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/date-time-axis.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/ej1-api-migration.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/financial-types.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/internationalization.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/legend.md

EJ2-57882 Reviewed the contents in ej2 core 

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/data-binding/bind-entity-framework.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/data-binding/restful-service-binding.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/data-binding/webapi-service-binding.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/how-to/both-html-and-tag-helper.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/how-to/render-asp-core-app-in-ie.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/html-attributes.md
ej2-asp-core-toc.html

ASP.NET Core documentation toc changes committed.

documentation(EJ2CORE-736): ASP.NET Core toc changes committed.

---

ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/localization.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/numeric-axis.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/other-types.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/overview.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/polar-radar.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/selection.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/strip-line.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/technical-indicators.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/trend-lines.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/working-with-data.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/zooming.md

Reviewed the contents in chart

EJ2-57882 Reviewed the contents in EJ2 Core

---

ej2-asp-core-mvc/code-snippet/tree-grid/adaptive/default.cs
ej2-asp-core-mvc/code-snippet/tree-grid/adaptive/razor
ej2-asp-core-mvc/code-snippet/tree-grid/adaptive/tagHelper
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/adaptive.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/adaptive.md

1) Running the Treegrid component in the adaptive layout. We can use the treegrid component in the mobile or desktop using the adaptive layout feature.
2) Added the sample to run and gave details about the feature.
3) Given property links to know the details about the property with their usage description.

Documentation(EJ2-58558): Added Documentation for the Adaptive View Feature

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

BLAZ-100 casing in toc corrected.

---

ej2-asp-core-mvc/daterangepicker/accessibility.md
ej2-asp-core-mvc/daterangepicker/customization.md
ej2-asp-core-mvc/daterangepicker/how-to/customization-using-cssclass.md
ej2-asp-core-mvc/daterangepicker/how-to/customize-the-daterangepicker-day-header.md
ej2-asp-core-mvc/daterangepicker/how-to/daterangepicker-for-core.md
ej2-asp-core-mvc/daterangepicker/how-to/daterangepicker-for-mvc.md
ej2-asp-core-mvc/daterangepicker/how-to/disable-the-daterangepicker-component.md
ej2-asp-core-mvc/daterangepicker/how-to/set-the-placeholder.md
ej2-asp-core-mvc/daterangepicker/range-restriction.md
ej2-asp-core-mvc/datetimepicker/EJ2_ASP.NETCORE/globalization.md
ej2-asp-core-mvc/datetimepicker/accessibility.md
ej2-asp-core-mvc/datetimepicker/customization.md
ej2-asp-core-mvc/datetimepicker/date-time-masking.md
ej2-asp-core-mvc/datetimepicker/date-time-range.md
ej2-asp-core-mvc/datetimepicker/how-to/customize-the-datetimepicker-day-header.md
ej2-asp-core-mvc/datetimepicker/how-to/datetimepicker-for-core.md
ej2-asp-core-mvc/datetimepicker/how-to/datetimepicker-for-mvc.md
ej2-asp-core-mvc/datetimepicker/how-to/disable-the-datetimepicker-component.md
ej2-asp-core-mvc/datetimepicker/how-to/set-the-placeholder.md
ej2-asp-core-mvc/datetimepicker/strict-mode.md
ej2-asp-core-mvc/datetimepicker/style-appearance.md

EJ2-58605 Reviewed the contents in Ej2 Core

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/cdn-fallback.md

ASP.NET Core CDN fallback changes committed.

documentation(EJ2CORE-763): ASP.NET Core CDN fallback changes committed.

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/adding-script-references.md

Warning added for un-version cdn links usage.

documentation(EJ2CORE-763): Warning added for un-version cdn links usage.

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/appearance/size-modes.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/animation.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/areas.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/compatible-with-essential-JS1.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/how-to/extend-and-customize-controls.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/input-validation.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/internationalization.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/state-persistence.md

ASP.NET Core documentation changes committed.

documentation(EJ2CORE-763): ASP.NET Core documentation changes committed.

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/cdn-fallback.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/internationalization.md

ASP.NET Core CDN fallback changes committed to hotfix.

documentation(EJ2CORE-763): ASP.NET Core CDN fallback changes to hotfix.

---

ej2-asp-core-mvc/document-editor/EJ2_ASP.MVC/getting-started.md

Added version specific CDN link

documentation(EJ2-58572): Added version specific cdn link

---

ej2-asp-mvc-toc.html

Removed Visual Studio Code integration in MVC toc file

EXT-6600-MVC TOC file changes

---

ej2-asp-core-mvc/document-editor/EJ2_ASP.NETCORE/feature-module.md
ej2-asp-core-mvc/document-editor/EJ2_ASP.NETCORE/import.md
ej2-asp-core-mvc/document-editor/how-to/auto-save-document-in-document-editor.md
ej2-asp-core-mvc/document-editor/how-to/change-document-view.md
ej2-asp-core-mvc/document-editor/how-to/customize-context-menu.md
ej2-asp-core-mvc/document-editor/how-to/customize-font-family-drop-down.md
ej2-asp-core-mvc/document-editor/how-to/customize-tool-bar.md
ej2-asp-core-mvc/document-editor/how-to/deploy-document-editor-component-for-mobile.md
ej2-asp-core-mvc/document-editor/how-to/disable-optimized-text-measuring.md
ej2-asp-core-mvc/document-editor/how-to/export-document-as-pdf.md
ej2-asp-core-mvc/document-editor/how-to/get-the-selected-content.md
ej2-asp-core-mvc/document-editor/how-to/open-default-document.md
ej2-asp-core-mvc/document-editor/how-to/open-document-by-address.md
ej2-asp-core-mvc/document-editor/how-to/override-the-keyboard-shortcuts.md
ej2-asp-core-mvc/document-editor/how-to/read-by-default.md
ej2-asp-core-mvc/document-editor/how-to/resize-document-editor.md
ej2-asp-core-mvc/document-editor/how-to/set-default-format-in-document-editor.md
ej2-asp-core-mvc/document-editor/how-to/show-hide-spinner.md

Reviewed the files in how to  and core folder in document editor

DOC-4263 Reviewed the content in ASP.NET Core

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/adding-script-references.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/drag-and-drop.md

ASP.NET Core common section samples committed.

documentation(EJ2CORE-763): ASP.NET Core common section samples committed.

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

1) Running the Treegrid component in the adaptive layout. We can use the treegrid component in the mobile or desktop using the adaptive layout feature.
2) Added the sample to run and gave details about the feature.
3) Given property links to know the details about the property with their usage description.

Doc(EJ2-58558):AdaptiveUG

---

ej2-asp-core-mvc/code-snippet/breadcrumb/specific-item-template/default.cs
ej2-asp-core-mvc/code-snippet/breadcrumb/specific-item-template/razor
ej2-asp-core-mvc/code-snippet/breadcrumb/specific-item-template/tagHelper

Added specific-item-template code-snippet file individually with codes

(EJ2-58646): UG Docs in Breadcrumb

---

ej2-asp-core-mvc/code-snippet/breadcrumb/specific-item-template/default.cs
ej2-asp-core-mvc/code-snippet/breadcrumb/specific-item-template/razor
ej2-asp-core-mvc/code-snippet/breadcrumb/specific-item-template/tagHelper

Added specific-item-template code-snippet file individually with codes

(EJ2-59206): Breadcrumb Documentation in asp-core-mvc

---

ej2-asp-core-mvc/breadcrumb/accessibility.md

Provide Keyboard accessibility support to Breadcrumb component.

(EJ2-55796):Provide Keyboard accessibility support to Breadcrumb component.

---

ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/column-template.md

documentation(BLAZ-21465): Documentation link added

---

ej2-asp-core-mvc/carousel/EJ2_ASP.MVC/animations-and-transitions.md
ej2-asp-core-mvc/carousel/EJ2_ASP.NETCORE/animations-and-transitions.md

bug(EJ2CORE-689): carousel UG review corrections addressed

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/appearance/theme.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/adding-script-references.md

ASP.NET Core common section changes committed.

documentation(EJ2CORE-780): ASP.NET Core common section changes committed.

---

ej2-asp-core-mvc/accordion/EJ2_ASP.MVC/getting-started.md

bug(EJ2CORE-689): publish failures resolved

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/introduction.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/nuget-packages.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/system-requirements.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/upgrade/how-to-upgrade-syncfusion-components-using-vs-extensions.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/upgrade/upgrade-syncfusion-aspnetcore-nuget-packages.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/upgrade/upgrading-syncfusion-aspnetcore-extensions.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/upgrade/upgrading.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-code-integration/create-project.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-code-integration/download-and-installation.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/check-for-updates.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/convert-project.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/create-project.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/create-samples.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/download-and-installation.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/overview.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/scaffolding.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/upgrade-project.md

Reviewed visual studio code and upgrade folder

DOC-4263 Reviewed the files in Asp.net Core

---

ej2-asp-core-mvc/EJ2_ASP.MVC/appearance/theme.md
ej2-asp-core-mvc/common/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/common/EJ2_ASP.MVC/state-persistence.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/state-persistence.md

ASP.NET MVC changes committed to hotfix.

documentation(EJ2CORE-780): ASP.NET MVC changes committed to hotfix.

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/appearance/theme.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/getting-started/yeoman.md

ASP.NET core common changes committed.

documentation(EJ2CORE-780): ASP.NET core common changes committed.

---

ej2-asp-core-mvc/code-snippet/menu/how-to/rounded/Rounded.cs
ej2-asp-core-mvc/code-snippet/menu/how-to/rounded/razor
ej2-asp-core-mvc/code-snippet/menu/how-to/rounded/tagHelper
ej2-asp-core-mvc/menu/how-to/menu-item-click.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

documentation(EJ2-56527): menu bar sample changed

---

ej2-asp-mvc-toc.html

documentation(EJ2-56527): menu bar sample link changed

---

ej2-asp-core-mvc/code-snippet/spreadsheet/collaborative-editing/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/collaborative-editing/tagHelper
ej2-asp-core-mvc/code-snippet/spreadsheet/collaborative-prevent-action/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/collaborative-prevent-action/tagHelper
ej2-asp-core-mvc/spreadsheet/use-cases/collaborative-editing.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Collaborative doc included and it sample code changed

documentation(EJ2-59815): Collaborative doc included and it sample code changed

---

ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/data-labels.md

documentation(EJ2-36899): UG topic for series percentage added

---

ej2-asp-core-mvc/split-button/accessibility.md

UG Content change for Split Button component.

(EJ2-59990):UG Content change for Split Button component.

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/licensing/licensing-troubleshoot.md

ASP.NET Core licensing changes committed.

documentation(EJ2CORE-775): ASP.NET Core licensing changes committed.

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/licensing/licensing-troubleshoot.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/adding-script-references.md

ASP.NET Core script reference and licensing changes moved to hotfix.

documentation(EJ2CORE-781): ASP.NET Core script reference changes moved to hotfix.

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/adding-script-references.md

ASP.NET Core script nonce changes committed.

documentation(EJ2CORE-781): ASP.NET Core script nonce changes committed.

---

ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/trend-lines.md
ej2-asp-core-mvc/code-snippet/chart/trendlines/hide/hide.cs
ej2-asp-core-mvc/code-snippet/chart/trendlines/hide/razor
ej2-asp-core-mvc/code-snippet/chart/trendlines/hide/tagHelper

documentation(EJ2-38141): sample Added

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/create-project.md

**Content Changes Description**
I have changed the document of a syncfusion content - EJ2 CORE document, I have newly added the content about **Authentication Type** which I have newly provided the Support in Syncfusion **EJ2 CORE** Project, So that I have added the content in document about authentication and also I have added the respective images for the Authentication in UG document.

EXT-6719 UG document changes for EJ2 Core authentication support

---

ej2-asp-core-mvc/spreadsheet/accessibility.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to add ARIA-Accessibility document and its contents into UG Documentation.
Added ARIA-Accessibility to spreadsheet component. Therefore, included new document.
Added ARIA-Accessibility description and contents into the document.
NA
NA
Test cases
NA

documentation(EJ2-59816): ARIA-Accessibility document included.

---

ej2-asp-core-mvc/code-snippet/document-editor-container/disable-header-footer/document-editor.cs
ej2-asp-core-mvc/document-editor/how-to/disable-header-and-footer-edit-in-document-editor.md

documentation(EJ2-55600): Resolved failure

documentation(EJ2-55600): Resolved failure

---

ej2-asp-core-mvc/gantt/state-persistence.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

documentation(EJ2-61044): added state persistence UG

---

ej2-asp-core-mvc/spreadsheet/keyboard-shortcuts.md

Need to add KeyBoard Shortcuts document and its contents into UG Documentation.
Added KeyBoard Shortcuts to spreadsheet component. Therefore, included new document.
Added KeyBoard Shortcuts contents into the document.
NA
NA
**Test cases**
NA

documentation(EJ2-59817): Keyboard-shortcuts document included.

---

ej2-asp-core-mvc/spreadsheet/keyboard-shortcuts.md

Need to add KeyBoard Shortcuts document and its contents into UG Documentation.
Added KeyBoard Shortcuts to spreadsheet component. Therefore, included new document.
Added KeyBoard Shortcuts contents into the document.
NA
NA
**Test cases**
NA

documentation(EJ2-59817): Keyboard-shortcuts document included

---

ej2-asp-core-mvc/code-snippet/gantt/rows/preventReorder/preventReorder.cs
ej2-asp-core-mvc/code-snippet/gantt/rows/preventReorder/razor
ej2-asp-core-mvc/code-snippet/gantt/rows/preventReorder/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/row/prevent-reorder/razor
ej2-asp-core-mvc/code-snippet/tree-grid/row/prevent-reorder/reorder.cs
ej2-asp-core-mvc/code-snippet/tree-grid/row/prevent-reorder/tagHelper
ej2-asp-core-mvc/gantt/rows.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/row.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/row.md

UG topic for prevent row re-ordering has in gantt has been added.

documentation(EJ2-60487): UG topic for prevent row re-ordering has in gantt has been added.

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/row.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/row.md

documentation(EJ2-60145): Resolved errors

---

ej2-asp-core-mvc/code-snippet/grid/globalization/internationalization/razor
ej2-asp-core-mvc/code-snippet/grid/globalization/internationalization/tagHelper
ej2-asp-core-mvc/code-snippet/grid/globalization/localization/razor
ej2-asp-core-mvc/code-snippet/grid/globalization/localization/tagHelper
ej2-asp-core-mvc/code-snippet/grid/globalization/righttoleft/razor
ej2-asp-core-mvc/code-snippet/grid/globalization/righttoleft/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/global-local/enableRtl/razor
ej2-asp-core-mvc/code-snippet/tree-grid/global-local/enableRtl/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/global-local/global/razor
ej2-asp-core-mvc/code-snippet/tree-grid/global-local/global/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/global-local/internalization/razor
ej2-asp-core-mvc/code-snippet/tree-grid/global-local/internalization/tagHelper
ej2-asp-core-mvc/common/EJ2_ASP.MVC/localization.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/localization.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/global-local.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/global-local.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/global-local.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/global-local.md

The pager three dot icon read message has been changed

bug(EJ2-60225):Changing-read-message-of-pager-icon

---

ej2-asp-core-mvc/code-snippet/gantt/state-persist/custom/column-prevent.cs
ej2-asp-core-mvc/code-snippet/gantt/state-persist/custom/razor
ej2-asp-core-mvc/code-snippet/gantt/state-persist/custom/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/state-persist/default/column-persist.cs
ej2-asp-core-mvc/code-snippet/gantt/state-persist/default/razor
ej2-asp-core-mvc/code-snippet/gantt/state-persist/default/tagHelper
ej2-asp-core-mvc/gantt/criticalpath.md
ej2-asp-core-mvc/gantt/state-persistence.md

Added how to add and prevent persist documentation

documentation(EJ2-61479): added docs for state persistence

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/row/indent.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/row/indent.md

doc(EJ2-61390): IndentUG

---

ej2-asp-core-mvc/spreadsheet/keyboard-shortcuts.md

Need to add KeyBoard Shortcuts document and its contents into UG Documentation.
Added KeyBoard Shortcuts to spreadsheet component. Therefore, included new document.
Added KeyBoard Shortcuts contents into the document.
NA
NA
**Test cases**
NA

documentation(EJ2-59817): Review Changes -  Resolved.

---

ej2-asp-core-mvc/spreadsheet/keyboard-shortcuts.md

Need to add Key Board Shortcuts document and its contents into UG Documentation.
Added  Key Board Shortcuts to spreadsheet component. Therefore, included new document.
Added  Key Board Shortcuts description and contents into the document.
NA
NA
**Test cases**
NA

documentation(EJ2-61619): Keyboard-shortcuts document included.

---

ej2-asp-core-mvc/spreadsheet/accessibility.md

Need to add ARIA-Accessibility and Key Board Shortcuts document and its contents into UG Documentation.
Added ARIA-Accessibility and Key Board Shortcuts to spreadsheet component. Therefore, included new document.
Added ARIA-Accessibility and Key Board Shortcuts description and contents into the document.
NA
NA
**Test cases**
NA

documentation(EJ2-61619): ARIA- Accessibility document included.

---

ej2-asp-core-mvc/maps/legend.md
ej2-asp-core-mvc/maps/providers/bing-maps.md

We have fixed the reported issue in the automation. Please merge the same.

EJ2-61059 - Fixed exception.

---

ej2-asp-core-mvc/code-snippet/pivot-table/onHeaderSort/OnHeaderSort.cs
ej2-asp-core-mvc/code-snippet/pivot-table/onHeaderSort/razor
ej2-asp-core-mvc/code-snippet/pivot-table/onHeaderSort/tagHelper
ej2-asp-core-mvc/code-snippet/pivot-table/sorting/custom-sorting/Custom-sorting.cs
ej2-asp-core-mvc/code-snippet/pivot-table/sorting/custom-sorting/razor
ej2-asp-core-mvc/code-snippet/pivot-table/sorting/custom-sorting/tagHelper
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/pivot-chart.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/sorting.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/pivot-chart.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/sorting.md

documentation(EJ2-58518): custom sorting documentation.

---

ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/appointments.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/appointments.md

Issue:
Multi dragging is not working in mobile mode
Solution: 
Added a note in the Documentation for Drag and Drop Multiple Appointments in ASP.NETCORE and ASP.MVC

Documentation(BLAZ-23257): Multi dragging is not working in mobile mode

---

ej2-asp-core-mvc/code-snippet/pivot-table/field-list/Search-desired-field-popup/Search-desired-field-popup.cs
ej2-asp-core-mvc/code-snippet/pivot-table/field-list/Search-desired-field-popup/razor
ej2-asp-core-mvc/code-snippet/pivot-table/field-list/Search-desired-field-popup/tagHelper
ej2-asp-core-mvc/code-snippet/pivot-table/field-list/Search-desired-field-static/Search-desired-field-static.cs
ej2-asp-core-mvc/code-snippet/pivot-table/field-list/Search-desired-field-static/razor
ej2-asp-core-mvc/code-snippet/pivot-table/field-list/Search-desired-field-static/tagHelper
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/field-list.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/field-list.md

documentation(EJ2-61568): UG documentation for field list search option.

---

ej2-asp-core-mvc/code-snippet/tree-grid/indent/razor
ej2-asp-core-mvc/code-snippet/tree-grid/indent/tagHelper
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/row/indent.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/row/indent.md
ej2-asp-core-toc.html

Added Indent and outdent method in the documentation.

doc(EJ2-61814): Added Indent and outdent method in the documentation.

---

ej2-asp-core-mvc/code-snippet/gantt/scrolling/responsive/razor
ej2-asp-core-mvc/code-snippet/gantt/scrolling/responsive/responsive.cs
ej2-asp-core-mvc/code-snippet/gantt/scrolling/responsive/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/scrolling/width-height/razor
ej2-asp-core-mvc/code-snippet/gantt/scrolling/width-height/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/scrolling/width-height/width-height.cs
ej2-asp-core-mvc/gantt/criticalpath.md
ej2-asp-core-mvc/gantt/scrolling.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added responsive UG documentation

documentation(EJ2-61304): added responsive UG docs

---

ej2-asp-core-mvc/code-snippet/toolbar/template-configuration/integratemenucomponent/menucomponent.cs
ej2-asp-core-mvc/code-snippet/toolbar/template-configuration/integratemenucomponent/razor
ej2-asp-core-mvc/code-snippet/toolbar/template-configuration/integratemenucomponent/tagHelper
ej2-asp-core-mvc/toolbar/template-configuration.md

Sample added for integrate menu component into toolbar component

documentation(EJ2-61152): sample added

---

ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/editor-template.md
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/exporting.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/editor-template.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/exporting.md

**(MVC) and (Core):**
1) Added openQuickInfoPopup public method in Ug documentation.
2) Added custom separator when exporting Scheduler events to CSV export in Ug documentation.

documentation(EJ2-61543): Include the UG documentation for newly added features in (Core) and (MVC) has been added.

---

ej2-asp-core-mvc/gantt/criticalpath.md

documentation(EJ2-61304): Modified critical path UG

---

ej2-asp-core-mvc/gantt/criticalpath.md

documentation(ej2-21614): modified critical path

---

ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/editor-template.md

**ASP .NET Core:**
Added Samples in Ug documentation.

documentation(EJ2-61543): Include the UG documentation for newly added features in (MVC) and (Core) documentation has been added.

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/infinite-scroll.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/row/row.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/virtual.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/infinite-scroll.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/row/row.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/virtual.md

Added virtualization limitation
Changed row template limitation
Added infinite scorll limitation

documentation(EJ2-57801): add limitation

---

ej2-asp-core-mvc/gantt/virtual-scroll.md

documentation(EJ2-46502): Updated virtual scroll UG

---

ej2-asp-core-mvc/gantt/task-dependency.md

Added parent predecessor support

documentation(EJ2-62829): Added parent predecessor support

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/virtual-scroll.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/virtual-scroll.md

Have resolved code snippet path error.

doc(EJ2-62325): Resolved code snippet path error.

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Resolved path error for the virtual-scroll sample.

doc(EJ2-62325): Resolved path error for the virtual-scroll sample.

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Have updated the file path in **mvc and core toc file.**

doc(EJ2-62325): Updated the file path in mvc and core toc file.

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Have cleared spacing issue in the mvc and core toc file

doc(EJ2-63452): Have cleared spacing issue in the mvc and core toc file

---

ej2-asp-core-mvc/grid/accessibility.md

CssClass added for Jaws reader

documentation(EJ2-62129):Improvement in JawsReader-Accessibility

---

ej2-asp-core-mvc/document-editor/keyboard-shortcut.md

Added the show/hide documentation short cut.

feature(EJ2-36027): Added the show/hide documentation short cut.

---

ej2-asp-core-mvc/code-snippet/document-editor/paragraph-format/razor
ej2-asp-core-mvc/code-snippet/document-editor/paragraph-format/tagHelper
ej2-asp-core-mvc/document-editor/paragraph-format.md

Added the show/hide paragraph marks.

feature(EJ2-36027): Added the show/hide paragraph marks.

---

ej2-asp-core-mvc/code-snippet/gantt/filtering/excelfilter/enablefilter.cs
ej2-asp-core-mvc/code-snippet/gantt/filtering/excelfilter/razor
ej2-asp-core-mvc/code-snippet/gantt/filtering/excelfilter/tagHelper
ej2-asp-core-mvc/gantt/filtering/excel-like-filter.md
ej2-asp-core-mvc/gantt/filtering/filter-menu.md
ej2-asp-core-mvc/gantt/filtering/filtering.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Adding excel filter and menu filter content .

documentation(EJ2-64256): excel filter and filter menu

---

ej2-asp-core-mvc/maps/providers/azure-maps.md

Committed azure path file error.

documentation(EJ2-62171): Committed azure path file error.

---

ej2-asp-core-mvc/code-snippet/mention/getting-started/data/data.cs
ej2-asp-core-mvc/code-snippet/mention/getting-started/default/data.cs
ej2-asp-core-mvc/code-snippet/mention/getting-started/showmentionchar/suggestionlist.cs
ej2-asp-core-mvc/mention/EJ2_ASP.NETCORE/getting-started.md

documentation(EJ2-63143): Resolved Getting started publish issue.

documentation(EJ2-63143): Resolved Getting started publish issue.

---

ej2-asp-core-mvc/carousel/EJ2_ASP.MVC/populating-items.md
ej2-asp-core-mvc/carousel/EJ2_ASP.NETCORE/populating-items.md

Reference link does not navigate to the another page issue has been resolved.

documentation(EJ2-62728): link does not navigate to the another page issue has been resolved.

---

ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/getting-started.md

Getting started documentation is updated for the floating action button control.
Getting started documentation is updated for the floating action button control.
Getting started documentation is updated for the floating action button control.
NA
NA

documentation(EJ2-63777): fab getting started is updated.

---

ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/getting-started.md

Getting started documentation is updated for the floating action button control.
Getting started documentation is updated for the floating action button control.
Getting started documentation is updated for the floating action button control.
NA
NA

feature(EJ2-63777): fab getting started is updated.

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/row-and-column.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/row-and-column.md

Autofit heading changes completed in ASP.NET Core and ASP.NET MVC platform.

document(EJ2-63766): Autofit heading changes completed.

---

ej2-asp-core-mvc/carousel/EJ2_ASP.MVC/styles-and-appearance.md
ej2-asp-core-mvc/carousel/EJ2_ASP.NETCORE/styles-and-appearance.md

Carousel CSS list table issue in ASP.NET has been corrected.

documentation(EJ2-61581): CSS list table in ASP.NET has been corrected

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/row-and-column.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/sorting.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/row-and-column.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/sorting.md

Review changes completed for core and mvc platform.

document(EJ2-63766): Review changes completed

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/excel-export.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/pdf-export.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/excel-export.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/pdf-export.md

documentation(EJ2-62353): Preparing UG document for "exportComplete" event.

---

ej2-asp-core-mvc/message/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/getting-started.md

Need to include the reviewed content.
Need to include the reviewed content for getting started section in ASP.NET Core and MVC Message component.
Added the reviewed content.
NA
No area is affected due to this changes.
NA
NA
* Is there any API name change? No
* Did you record this case in the unit test or UI test? NA

feature(EJ2-64707): Updated getting started section with reviewed content.

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/virtual-scroll.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/virtual-scroll.md

Have removed **virtual scrolling limitations for frozen column.**

doc(EJ2-65077): Removed virtual scrolling limitations for frozen column.

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/paging.md

documentation(EJ2-64269): Paging UG document added.

---

ej2-asp-core-mvc/appbar/position.md
ej2-asp-core-mvc/appbar/size-and-color.md

Description
Content correction in AppBar position, size and color
Content correction in AppBar position, size and color
Output screenshots
NA
No area is affected due to this changes.
Test cases
NA
Test bed sample location
NA
Did you run the automation against your implementation? NA
Does your code pass all FxCop and StyleCop rules? Yes
Did you record this case in the unit test or UI test? NA

documentation(BLAZ-26649): Content correction in AppBar position, size and color

---

ej2-asp-core-mvc/image-editor/annotation.md
ej2-asp-core-mvc/image-editor/how-to/render-image-editor-dialog.md

UG correction for Image Editor component.

UG(EJ2-65030):UG correction for Image Editor component.

---

ej2-asp-core-mvc/code-snippet/mention/accessibility/keyboard-intraction/Employees.cs
ej2-asp-core-mvc/code-snippet/mention/accessibility/keyboard-intraction/razor
ej2-asp-core-mvc/code-snippet/mention/accessibility/keyboard-intraction/tagHelper
ej2-asp-core-mvc/code-snippet/mention/customization/mention-char-customization/EmailData.cs
ej2-asp-core-mvc/code-snippet/mention/customization/popup-list-customization/Countries.cs
ej2-asp-core-mvc/code-snippet/mention/customization/suffix-char-customization/SportsData.cs
ej2-asp-core-mvc/code-snippet/mention/filtering-data/allow-space/Employees.cs
ej2-asp-core-mvc/code-snippet/mention/filtering-data/allow-space/razor
ej2-asp-core-mvc/code-snippet/mention/filtering-data/allow-space/tagHelper
ej2-asp-core-mvc/code-snippet/mention/filtering-data/suggestion-count/EmailData.cs
ej2-asp-core-mvc/code-snippet/mention/sorting/SportsData.cs
ej2-asp-core-mvc/code-snippet/mention/template/display-template/razor
ej2-asp-core-mvc/code-snippet/mention/template/display-template/tagHelper
ej2-asp-core-mvc/code-snippet/mention/template/spinner-template/razor
ej2-asp-core-mvc/code-snippet/mention/working-with-data/arrayof-json-data/SportsData.cs
ej2-asp-core-mvc/code-snippet/mention/working-with-data/web-api/tagHelper

documentation(EJ2-65169): Addressed review comments

documentation(EJ2-65169): Addressed review comments

---

ej2-asp-core-mvc/code-snippet/mention/customization/mention-char-customization/EmailData.cs
ej2-asp-core-mvc/code-snippet/mention/getting-started/data/tagHelper
ej2-asp-core-mvc/code-snippet/mention/getting-started/showmentionchar/tagHelper
ej2-asp-core-mvc/mention/EJ2_ASP.NETCORE/customization.md

documentation(EJ2-65169): Build failure issue resolved

documentation(EJ2-65169): Build failure issue resolved

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/calculated-field.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/data-binding.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/drill-down.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/row-and-column.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/tool-bar.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/calculated-field.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/data-binding.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/drill-down.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/grouping.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/paging.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/pivot-chart.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/row-and-column.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/tool-bar.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

In this PR, hotfix/hotfix-v20.3.0.47 branch changes are moved to development branch

documentation(EJ2-64714): Development branch update by hotfix/hotfix-v20.3.0.47

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/columns/columns-core.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/editing/dialog-editing.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/editing/persisting-data-in-server.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/filtering/excel-like-filter.md

resolve conflicts in PR 1019 https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/1019

documentation(ej2-65244): resolve conflicts in PR 1019

---

ej2-asp-core-mvc/EJ2_ASP.MVC/introduction.md

|**Task Link**|https://syncfusion.atlassian.net/browse/IN-18623|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. Need to change the Control list alignment to make it looks better.<br>3.These changes are in Overview page only, Some platforms are present inside the table.|
|**Solution description**|1.Added the new line-height, and new class.<br> 2. Also added the padding for list data to make it readable.<br>3. Apply the line-height as like our contents.<br>|
|**Output screenshots**|Control list ![image](https://user-images.githubusercontent.com/110027500/199717832-b1985e7e-456b-4228-a5f1-dce1dc73516a.png)|
|**Areas affected and ensured**|<ul><li>Changes are Fine wile ran Locally and also ensured that the changes are not …

IN-18623-Control-Category

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to update toc list order for Speed Dial UG documentation.
Toc list order for Speed Dial UG documentation.
Toc list order is updated for Speed Dial UG documentation.
NA
NA

documentation(EJ2MVC-468): toc is updated for speeddial

---

ej2-asp-core-mvc/EJ2_ASP.MVC/introduction.md

|**Task Link**|https://syncfusion.atlassian.net/browse/IN-18623|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. Need to change the Control list alignment to make it looks better.<br>3.These changes are in Overview page only, Some platforms are present inside the table.|
|**Solution description**|1.Added the new line-height, and new class.<br> 2. Also added the padding for list data to make it readable.<br>3. Apply the line-height as like our contents.<br>|
|**Output screenshots**|Control list ![image](https://user-images.githubusercontent.com/110027500/199717832-b1985e7e-456b-4228-a5f1-dce1dc73516a.png)|
|**Areas affected and ensured**|<ul><li>Changes are Fine wile ran Locally and also ensured that the changes are not …

IN-18623-Control-Category-MVC

---

ej2-asp-core-mvc/mention/EJ2_ASP.MVC/templates.md

documentation(EJ2-63820): Build failure issue resolved

documentation(EJ2-63820): Build failure issue resolved

---

ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/icons.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/positions.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/styles.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.NETCORE/icons.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.NETCORE/positions.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.NETCORE/styles.md

Need to update UG heading casing and API links
Update UG heading casing and API links for Floating Action Button.
NA 
NA
NA

documentation(BLAZ-26909): FAB casing and api links updated

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

documentation(EJ2-65767): Added Message component feature sections.

documentation(EJ2-65767): Added Message component feature sections.

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Resolved merge conflict for hotfix branch

feature(EJ2-65728): Resolved merge conflict

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/getting-started.md

Hi @KameshRajendran ,
I have added the missing code in getting started section of MVC and Core platforms. Please review the changes.
Regards,
Ranjitha A.

EJ2-65731 Added the missing code in getting started section

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/getting-started.md

Hi @KameshRajendran ,
I have updated the getting started section changes in the MVC and CORE platforms. Please review the changes.
Regards,
Ranjitha A.

EJ2-65731 MVC and CORE getting started changes

---

ej2-asp-core-mvc/floating-action-button/EJ2_ASP.MVC/positions.md
ej2-asp-core-mvc/floating-action-button/EJ2_ASP.NETCORE/positions.md

Need to update position topic for Fab control UG documentation.
Update position topic for Fab control UG documentation.
Updated position topic for Fab control UG documentation.
NA
NA

documentation(EJ2CORE-888): conflict resolved.

---

ej2-asp-core-mvc/gantt/managing-tasks/task-bar-editing.md
ej2-asp-core-mvc/gantt/time-line/zooming.md

resolved conflicts in https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/1209

documentation(ej2-66897): resolved conflicts

---

ej2-asp-core-mvc/code-snippet/spreadsheet/open-readonly/opencontroller.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/open-readonly/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/open-readonly/tagHelper
ej2-asp-core-mvc/spreadsheet/open-save.md

Need to include the content for how to open excel file in readOnly mode
Added the content for how to open excel file in readOnly mode
Added content for open excel file in readOnly mode
NA
NA
Test cases
NA

documentation(EJ2-61108): To include the content for how to open excel file in readOnly mode

---

ej2-asp-core-mvc/code-snippet/spreadsheet/open-readonly/opencontroller.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/open-readonly/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/open-readonly/tagHelper
ej2-asp-core-mvc/spreadsheet/open-save.md

Need to include the content for how to open excel file in readOnly mode
Added the content for how to open excel file in readOnly mode
Added content for open excel file in readOnly mode
NA
NA
Test cases
NA

documentation(EJ2-61108): To include the content for how to open excel file in readOnly mode 

---

ej2-asp-core-mvc/EJ2_ASP.MVC/introduction.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/introduction.md

|**Task Link**|https://syncfusion.atlassian.net/browse/IN-18783|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. No design changes are required.|
|**Solution description**|1.Added the font weight in the controlcategory class.<br> 2.Set the font weight to 500|
|**Output screenshots**|-|
|**Areas affected and ensured**|<ul><li>Changes in the ASP .Net Core and MVC introduction.md. Previous code didn't affected and ensured in end.</li></ul>|
|**Test cases**|Check the site locally.|
|**Testbed sample location**|-|
|**Additional CheckList**|<ul><li>Did you run the automation against your fix? No</li><li>Is there any API name change?No</li><li>Is there any existing behavior change of other features due to this code change? …

IN-18783: Check font weight of body content-dev

---

ej2-asp-core-mvc/code-snippet/dropdowntree/data-binding/prevent-node/preventnode.cs
ej2-asp-core-mvc/code-snippet/dropdowntree/data-binding/prevent-node/razor
ej2-asp-core-mvc/code-snippet/dropdowntree/data-binding/prevent-node/tagHelper

ASP MVC core documentation path changes for DropDownTree.

documentation(EJ2-63133):ASP MVC core documentation path changes for DropDownTree.

---

ej2-asp-core-mvc/file-manager/EJ2_ASP.MVC/getting-started.md

Hi @ChristoIssac 
|--|--|
|Task Category|ASP.NET MVC File Manager Money Keywords|
|Content Task Link/Mail Screenshot|https://syncfusion.atlassian.net/browse/CONTENT-7609|
|UX task|NA|
|Interlinking PR|Interlinking - https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/1180
|Ticket/Task link|https://syncfusion.atlassian.net/browse/SEO-2917|
|Excel/SharePoint link|https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/ASP.NET-MVC-File-Manager---Money-Keywords.aspx|
|asp.net mvc file manager|10-100 |1FT |Ranked in 1st position |got content review, added new section, added image, and removed extra space|
|asp.net mvc file manager example …

SEO-2913 ASP.NET MVC File Manager Interlinking

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/form-designer/create-fillable-PDF-forms/create-programmatically.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/form-designer/create-fillable-PDF-forms/create-with-user-interface-interaction.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/form-designer/create-fillable-PDF-forms/create-programmatically.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/form-designer/create-fillable-PDF-forms/create-with-user-interface-interaction.md

Hi @KameshRajendran ,
I have updated the H1 content in mvc and core platform. Please review the changes.
Regards,
Ranjitha A.

BLAZ-27620 Updated the H1 content in MVC and CORE platforms.

---

ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/expandstatemapping/expandstatemapping.cs
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/expandstatemapping/razor
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/lazy-loading/lazyLoading.cs
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/lazy-loading/razor
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/load-child-ondemand-virtualization/loadChildOnDemand.cs
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/load-child-ondemand-virtualization/razor
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/data-binding/data-binding.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/data-binding/remote-data.md

Added UG for lazy loading and load child ondemand with virtualization in remote data binding.

documentation(EJ2-67088): Added UG for lazy loading and load child ondemand with virtualization in remote data binding

---

ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/expandstatemapping/expandstatemapping.cs
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/expandstatemapping/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/lazy-loading/lazyLoading.cs
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/lazy-loading/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/load-child-ondemand-virtualization/loadChildOnDemand.cs
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/load-child-ondemand-virtualization/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/loading-animation/loadingAnimation.cs
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/loading-animation/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/expandstatemapping/razor
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/lazy-loading/razor
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/load-child-ondemand-virtualization/razor
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/loading-animation/loadingAnimation.cs
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/loading-animation/razor
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/data-binding/remote-data.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/loading-animation.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/data-binding/data-binding-core.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/data-binding/remote-data.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/loading-animation.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added UG for lazy loading, load child ondemand with virtualization and Shimmer effect in remote data binding feature.

documentation(EJ2-67364): Added UG for lazy loading, load child ondemand with virtualization and Shimmer effect in remote data binding feature

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/getting-started.md

Hi Team,
Kindly review the modified content in ASP .Net core and MVC PdfViewer and provide your feedback.
With Regards,
Gayathri R

EJ2-66939-Modified content in ASP .Net core and MVC PdfViewer

---

ej2-asp-core-mvc/code-snippet/spreadsheet/column-width/columnWidthController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/column-width/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/column-width/tagHelper
ej2-asp-core-mvc/code-snippet/spreadsheet/row-height/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/row-height/rowHeightController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/row-height/tagHelper
ej2-asp-core-mvc/spreadsheet/open-save.md
ej2-asp-core-mvc/spreadsheet/rows-and-columns.md

Need to include the size topic in UG documentation
Added the size topic in UG documentation
Included the size topic in UG documentation
NA
NA
Test cases
NA

documentation(EJ2-66586): To include the size topic in UG documentation

---

ej2-asp-core-mvc/spreadsheet/rows-and-columns.md

Resolved conflicts and modified

config(EJ2-66788): resolved conflicts

---

ej2-asp-core-mvc/document-editor/EJ2_ASP.NETCORE/import.md

Resolved typo error in import page

documentation(EJ2-67699): Resolved typo error in import page

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/how-to/upgrade-syncfusion-controls-to-latest-version.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/version-compatibility.md

Updated Version compatibility details for ASP.NET Core controls.

documentation(EJ2CORE-994): Update version compatibility

---

ej2-asp-core-mvc/document-editor/dialog.md

documentation(EJ2-65644): Resolved failure
[EJ2-65644]: https://syncfusion.atlassian.net/browse/EJ2-65644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

documentation(EJ2-65644): Resolved failure

---

ej2-asp-core-toc.html

- API Reference Link has been added for Rating Component. 
- Skeleton Component Rendering order has been Changed.

documentation(EJ2-68067): Rating-API Reference added; Skeleton-Changed Rendering Order

---

ej2-asp-core-toc.html

1. API Reference Link has been added for Rating Component.
2. Skeleton Component Rendering order has been Changed.

documentation(EJ2-68067):Rating-API Reference added; Skeleton-Changed Rendering Order

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/row/row-template.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/row/row-template.md

documentation(EJ2-57148): Limitation

---

ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/resources.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/resources.md

Description:
Removed the unknown tag 'endtab' in resources.md file in ASP MVC/core Scheduler
Test cases:
NA
NA

Documentation(EJ2-66488):Addressed review corrections in ASP MVC/core Scheduler

---

ej2-asp-core-mvc/rating/EJ2_ASP.MVC/appearance.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/labels.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/precision-modes.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/selection.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/templates.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/tooltip.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/appearance.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/labels.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/precision-modes.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/selection.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/templates.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/tooltip.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to update file path for appearance sample in Asp.net CORE and MVC platform.
Update file path for appearance sample in Asp.net CORE and MVC platform.
NA
NA
NA

documentation(EJ2CORE-993): Updated Appearance sample file path.

---

ej2-asp-core-mvc/rating/EJ2_ASP.MVC/appearance.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/labels.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/precision-modes.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/selection.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/templates.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/tooltip.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/appearance.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/labels.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/precision-modes.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/selection.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/templates.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/tooltip.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to update file path for appearance sample in Asp.net CORE and MVC platform.
cherry picked PR from - https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/1466
Update file path for appearance sample in Asp.net CORE and MVC platform.
NA
NA
NA

documentation(EJ2CORE-993): Updated Rating content title.

---

ej2-asp-core-mvc/rating/EJ2_ASP.MVC/appearance.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/selection.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/templates.md
ej2-asp-core-mvc/rating/EJ2_ASP.MVC/tooltip.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/appearance.md
ej2-asp-core-mvc/rating/EJ2_ASP.NETCORE/events.md

Need to update file path for appearance sample in Asp.net CORE and MVC platform.
Update file path for appearance sample in Asp.net CORE and MVC platform.
NA
NA
NA

documentation(EJ2CORE-993): Updated code snippet paths.

---

ej2-asp-core-mvc/rating/EJ2_ASP.MVC/templates.md

documentation(EJ2CORE-993): tag issue resolved- development

documentation(EJ2CORE-993): tag issue resolved-dev

---

ej2-asp-core-mvc/rating/EJ2_ASP.MVC/templates.md

documentation(EJ2CORE-993): tag issue resolved- hotfix

documentation(EJ2CORE-993): tag issue resolved-hotfix

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Drop-down menu for the split up topics is not visible issue in core and mvc has been fixed.

documentation(EJ2-68246):made the drop down list visible in mvc and core

---

ej2-asp-core-mvc/code-snippet/gantt/immutable/immutable/immutable.cs
ej2-asp-core-mvc/code-snippet/gantt/immutable/immutable/razor
ej2-asp-core-mvc/code-snippet/gantt/immutable/immutable/tagHelper
ej2-asp-core-mvc/gantt/immutable.md
ej2-asp-core-mvc/gantt/managing-tasks/splitting-and-merging-tasks.md
ej2-asp-core-mvc/gantt/managing-tasks/task-bar-editing.md
ej2-asp-core-mvc/gantt/module.md
ej2-asp-core-mvc/gantt/resources.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Fixed the broken links in mvc & core

documentation(EJ2-66823):fix the broken api links in mvc and core

---

ej2-asp-core-mvc/message/EJ2_ASP.MVC/customization.md
ej2-asp-core-mvc/message/EJ2_ASP.MVC/icons.md
ej2-asp-core-mvc/message/EJ2_ASP.MVC/severities.md
ej2-asp-core-mvc/message/EJ2_ASP.MVC/template.md
ej2-asp-core-mvc/message/EJ2_ASP.MVC/variants.md
ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/customization.md
ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/icons.md
ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/severities.md
ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/template.md
ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/variants.md

The links are missing for the properties of the message component.
Currently, our message documentation does not contain the property links. We need to add the links for better understanding.
Handled the scenario by providing the appropriate link.
Not applicable. Only changed the link.
-Ensured whether proper links are added.
Need to ensure this support in manual test cases.
Added the manual test cases for this support.
* Is there any API name change? No
* Did you record this case in the unit test or UI test? NA

feature(EJ2-68641): Link changed for the properties.

---

ej2-asp-core-mvc/file-manager/virtualization.md

File Manager ASP Core MVC UG corrections for Virtualization

documentation(EJ2-68587):File Manager ASP Core MVC UG corrections for Virtualization

---

ej2-asp-core-mvc/code-snippet/spreadsheet/open-save/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/open-save/tagHelper
ej2-asp-core-mvc/code-snippet/spreadsheet/save-header/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/save-header/tagHelper

Change the service URL in UG documents.
Change the new service URL in UG documents.
Find how it was missed in our earlier testing and development by analyzing the below checklist. This will help prevent similar mistakes in the future.
- Common guidelines / Core team guideline
- Specification document
- Requirement document
- Common guidelines / Core team guideline
- Specification document
- Requirement document
Change the new service URL in UG documents.
I have now changed the new service URL in UG documents.
NA
No
I have now changed the new service URL in UG documents.
NA
NA
This may vary for different teams or products. Check with your scrum masters.
- Did you run the automation against your fix? no
- Is there any API name change? no
- Is there any existing behavior change of other …

bug(EJ2-70051): Change the service URL in UG documents.

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/getting-started.md

In the sample level for import, export, and download, it throws an error due to the missing imported data due to the missing and mismatched jsonObject, which is handled in this PR.

 In sample level for import and export throws error due to missing of imported data 

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/resolve-Unable-to-find-an-entry-point-error.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/resolve-Unable-to-find-an-entry-point-error.md

Hi Kamesh,
I have updated the content review changes and committed. Can you please review and merge the changes?
Regards,
Ranjitha A.

BLAZ-30272 Updated the reviewed content.

---

ej2-asp-core-mvc/code-snippet/document-editor/optimize-sfdt/razor
ej2-asp-core-mvc/code-snippet/document-editor/optimize-sfdt/razorOld
ej2-asp-core-mvc/code-snippet/document-editor/optimize-sfdt/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor/optimize-sfdt/tagHelperOld
ej2-asp-core-mvc/document-editor/how-to/optimize-sfdt.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

documentation(EJ2-71156): Added UG for optimize sfdt

documentation(EJ2-71156): Added UG for optimize sfdt

---

ej2-asp-core-mvc/code-snippet/pivot-table/getting-start-mvc/olap-roles/razor
ej2-asp-core-mvc/code-snippet/pivot-table/getting-start-mvc/olap-roles/roles.cs
ej2-asp-core-mvc/code-snippet/pivot-table/getting-start-mvc/olap-roles/tagHelper
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/olap.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/olap.md

Included UG for "Role support in OLAP data source" for EJ2 Pivot Table.

sample(EJ2-70833): To include UG for "Role support in OLAP data source" for EJ2 Pivot Table.

---

ej2-asp-core-mvc/code-snippet/spreadsheet/pdf-orientation/pdfOrientationController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/pdf-orientation/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/pdf-orientation/tagHelper
ej2-asp-core-mvc/spreadsheet/open-save.md

Need to include the PDF orientation topic under the Save section in UG documentation.
Added the PDF orientation topic under the Save section in UG documentation.
Included PDF orientation topic under the Save section in UG documentation.
NA
NA
Test cases
NA

documentation(EJ2-71125): To include the PDF orientation topic under the Save section in UG documentation.

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/filtering/filtering.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/filtering/filtering.md

New documentation for adding additional operators in Data Grid

documentation(EJ2-70707):New documentation for adding additional operators in Data Grid

---

ej2-asp-core-mvc/code-snippet/ribbon/getting-started/default/tagHelper
ej2-asp-core-mvc/ribbon/EJ2_ASP.NETCORE/getting-started.md

documentation(EJ2-63710): conflit resovled

documentation(EJ2-63710): conflit resovled

---

ej2-asp-core-mvc/code-snippet/chart/accumulation-charts/chart-print/centerlabel/tagHelper
ej2-asp-core-mvc/code-snippet/chart/accumulation-charts/chart-print/hovertext/tagHelper

(EJ2-71411): To resolved the conflicts.

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/excel-export/exporting-hierarchy-grid.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/excel-export/exporting-hierarchy-grid.md

New documentation for excel export hierarchy grid in DataGrid

documentation(EJ2-71821):New documentation for excel export hierarchy grid in DataGrid

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/tool-bar.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/tool-bar.md

UG document to save and load report using database.

documentation(EJ2-67661): UG document to save and load report using database.

---

ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.MVC/center-label.md
ej2-asp-core-mvc/code-snippet/chart/accumulation-charts/chart-print/customization/tagHelper
ej2-asp-core-mvc/code-snippet/chart/series/other-types/error-bar-color/tagHelper
ej2-asp-core-mvc/code-snippet/progress-bar/types/tooltip3/tagHelper

To resolved the conflict issues.

(EJ2-71411): To resolved the conflict issues.

---

ej2-asp-core-mvc/code-snippet/grid/columns/autofit-column/autofit.cs
ej2-asp-core-mvc/code-snippet/grid/columns/autofit-column/razor
ej2-asp-core-mvc/code-snippet/grid/columns/autofit-column/tagHelper
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/columns/auto-fit-columns.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/auto-fit-columns.md

New documentation for autoFit in DataGrid

documentation(EJ2-71059):New documentation for autoFit in DataGrid

---

ej2-asp-core-mvc/code-snippet/pivot-table/field-list/static-fieldlist-virtualization/razor
ej2-asp-core-mvc/code-snippet/pivot-table/field-list/static-fieldlist-virtualization/tagHelper

Code snippet for static field list with virtualization sample updated.

documentation(EJ2-70395): Need to update code snippet for static field list with virtualization sample.

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/columns/columns.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/data-binding/how-to-change-the-data-source-or-columns-dynamically.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/columns.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/data-binding/how-to-change-the-data-source-or-columns-dynamically.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

New documentation for changeDatasource in Data Grid

documentation(EJ2-71593):New documentation for changeDatasource in Data Grid

---

ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/scatter.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/scatter.md

(EJ2-72084): To resolved the error.

---

ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-series.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-series.md
ej2-asp-core-toc.html

To added an multiple series in Core UG.

(EJ2-824842): To added multiple series in UG.

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

ES-826500: Removed unwanted Double Quote-Hotfix

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

ES-826500: Removed unwanted Double Quote

---

ej2-asp-core-mvc/message/EJ2_ASP.MVC/customization.md
ej2-asp-core-mvc/message/EJ2_ASP.MVC/getting-started.md

Hi @Girija-Rajendran ,
|--|--|
|Task Category|ASP.NET MVC Message Money Keywords|
|Content Task Link/Mail Screenshot|https://syncfusion.atlassian.net/browse/CONTENT-7812|
|UX task|NA|
|Interlinking  link|Interlinking - https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/1701
|Ticket/Task link|https://syncfusion.atlassian.net/browse/SEO-3245|
|Excel/SharePoint link|https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/ASP.NET-MVC-Message---Money-Keywords.aspx|
|asp.net mvc message|0-10 |Omitted-4FT |Need to improve FT position |got content review, changed image alignment added new section, and added image|
|asp.net mvc message example …

SEO-148047 ASP.NET MVC Message Interlinking

---

ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/customization.md
ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/getting-started.md

Hi @Girija-Rajendran ,
|--|--|
|Task Category|ASP.NET Core Message Money Keywords|
|Content Task Link/Mail Screenshot|https://syncfusion.atlassian.net/browse/CONTENT-7812|
|UX task|NA|
|Interlinking  link|Interlinking - https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/1700
|Ticket/Task link|https://syncfusion.atlassian.net/browse/SEO-3243|
|Excel/SharePoint link|https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/ASP.NET-Core-Message---Money-Keywords.aspx|
|asp.net core message|0-10 |18FT |Need to improve FT position |got content review, changed image alignment added new section, and added image|
|asp.net core message example …

SEO-148052 ASP.NET Core Message Interlinking

---

ej2-asp-core-mvc/appbar/EJ2_ASP.NETCORE/getting-started.md

|--|--|
|Task Category|ASP.NET Core AppBar Money Keywords
|Content Task Link/Mail Screenshot|https://syncfusion.atlassian.net/browse/CONTENT-7935 |
|UX task|NA|
|Interlinking| https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/1702|
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/123281/|
|Excel/SharePoint link|https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/ASP.NET-CORE-AppBar-Money-Keywords.aspx|
|ASP.NET Core AppBar|0-10 |4FT|To move FT to the first position |Changed some content in the page|
|ASP.NET Core AppBar control|0-10 |5FT |To improve the FT position|added in the md …

SEO-123281 ASP.NET Core AppBar changes

---

ej2-asp-core-mvc/code-snippet/gantt/data-binding/ajaxBinding/razor
ej2-asp-core-mvc/code-snippet/gantt/data-binding/ajaxBinding/tagHelper
ej2-asp-core-mvc/gantt/data-binding.md

Changed the ajax to fetch in core & mvc platform.

documentation(EJ2-831746):changed the ajax to fetch in core & mvc

---

ej2-asp-core-mvc/code-snippet/tooltip/ajaxcontent/razor
ej2-asp-core-mvc/code-snippet/tooltip/ajaxcontent/tagHelper
ej2-asp-core-mvc/code-snippet/tooltip/dynamic-content/razor
ej2-asp-core-mvc/code-snippet/tooltip/dynamic-content/tagHelper
ej2-asp-core-mvc/tooltip/content.md
ej2-asp-core-mvc/tooltip/how-to/dynamic-tooltip-content.md

Replaced the Ajax API in the Tooltip component using the Fetch API which is available in the Base library.

Documentation(ES-830958):Fetch API changes for Tooltip component has been added

---

ej2-asp-core-mvc/code-snippet/kanban/virtual-scrolling/default/controller.cs
ej2-asp-core-mvc/code-snippet/kanban/virtual-scrolling/default/datasource.cs
ej2-asp-core-mvc/code-snippet/kanban/virtual-scrolling/default/razor
ej2-asp-core-mvc/code-snippet/kanban/virtual-scrolling/default/tagHelper
ej2-asp-core-mvc/kanban/EJ2_ASP.MVC/virtual-scrolling.md
ej2-asp-core-mvc/kanban/EJ2_ASP.NETCORE/virtual-scrolling.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

documentation(834959): Kanban Virtual Scrolling Feature UG Documentation - Core & MVC - Development

documentation(834959): Kanban Virtual Scrolling Feature UG Documentation - Core & MVC - Development

---

ej2-asp-core-mvc/code-snippet/spreadsheet/chart-cs1/chartController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/chart-cs1/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/chart-cs1/tagHelper
ej2-asp-core-mvc/code-snippet/spreadsheet/chart-cs2/chartController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/chart-cs2/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/chart-cs2/tagHelper
ej2-asp-core-mvc/spreadsheet/illustrations.md

Added UG documentation and code snippets for Line marker chart feature

documentation(EJ2-822839): UG documentation of chart marker feature

---

ej2-asp-core-mvc/document-editor/header-footer.md

Feature(EJ2-39268): added UG documentation for Link to previous

Feature(EJ2-39268): added UG documentation for Link to previous

---

ej2-asp-core-mvc/spreadsheet/keyboard-shortcuts.md

Added/Modified keyboard shortcuts

documentation: added keyboard shortcuts changes

---

ej2-asp-core-mvc/code-snippet/spreadsheet/chart-cs2/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/chart-cs2/tagHelper

documentation(EJ2-822839): resolved script error

---

ej2-asp-core-mvc/code-snippet/schedule/recurrence-editor/editor-endtype-recurrence/data.cs
ej2-asp-core-mvc/code-snippet/schedule/recurrence-editor/editor-endtype-recurrence/razor
ej2-asp-core-mvc/code-snippet/schedule/recurrence-editor/editor-endtype-recurrence/tagHelper
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/recurrence-editor.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/recurrence-editor.md

Description:
Need to add UG for end type option customizing feature.
Test cases:
NA
NA

Documentation(ES-640231): Need to add UG for end type option customizing feature.

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/field-list.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/field-list.md

Updated the field list sort sample.

documentation(EJ2-834211): Updated the field list sort sample.

---

ej2-asp-core-mvc/diagram/automatic-layout.md

headings not displayed properly
Update automatic-layout.md
the bold tag for heading inside table tag not written properly has been fixed so that successive heading now rendered properly

bug(837014):rework on documentation issues

---

ej2-asp-core-mvc/tree-grid/accessibility.md

Have modified proper key combination to perform single expand/collapse operation

config(836051-keyNav):modified proper key navigation in accessibility 

---

ej2-asp-core-mvc/tree-grid/accessibility.md

Have modified proper key combination to perform single expand/collapse operation

config(836051-hotfix):modified proper key navigation in accessibility

---

ej2-asp-mvc-toc.html

Need to add the reversible slider topic in ASP MVC and core.

documentation(ES-834291):Need to add the reversible slider topic in ASP MVC and core.

---

ej2-asp-core-mvc/code-snippet/chart/series/column/titleoption/razor
ej2-asp-core-mvc/code-snippet/chart/series/column/titleoption/tagHelper

Resolved the title position issue.

(EJ2-834303): Resolved the title position issue.

---

ej2-asp-core-mvc/code-snippet/chart/series/column/titleoption/razor
ej2-asp-core-mvc/code-snippet/chart/series/column/titleoption/tagHelper

Resolved the title position issue.

(EJ2-836705): Resolved the title position issue.

---

ej2-asp-core-mvc/code-snippet/schedule/editor-template/editor-resource/razor
ej2-asp-core-mvc/code-snippet/schedule/editor-template/editor-resource/tagHelper

Added value for MultiSelect control in code snippets
NA
NA

Documentation(SC-829957): Added value for MultiSelect control.

---

ej2-asp-core-mvc/datepicker/style-appearance.md
ej2-asp-core-mvc/daterangepicker/style-appearance.md
ej2-asp-core-mvc/datetimepicker/style-appearance.md
ej2-asp-core-mvc/timepicker/style-appearance.md

We have included the full-screen popup feature documentation
The documentation added for explaining the new feature of full-screen popup
NA
NA
NA

feature(834525): Full screen feature documentation added

---

ej2-asp-core-mvc/diagram/symbol-palette.md
ej2-asp-core-mvc/diagram/tooltip.md

Doc(EJ2-838731) Development to hotfix asp dotnet.

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/global-local.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/global-local.md

Added Indent/Outdent locale text.

839773 localization hotfix

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/global-local.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/global-local.md

Added Indent/Outdent locale text.

839773 localization dev

---

ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/data-binding.md

Description:
Updated the UrlAdaptor UG topic with the example sample.
Scheduler CRUD section
Test cases:
NA
NA

Documentation(ES-822852): Updated the UrlAdaptor UG topic with the example sample.

---

ej2-asp-core-mvc/tab/how-to/create-wizard-using-tab.md
ej2-asp-core-mvc/tab/how-to/prevent-content-swipe-selection.md

Description:
Resolve build error.
Test cases:
NA
NA

documentation(ES-840066-Builderror): Resolve build error.

---

ej2-asp-core-mvc/file-manager/file-operations.md
ej2-asp-core-mvc/listview/EJ2_ASP.NETCORE/getting-started.md

Link : [https://ej2.syncfusion.com/aspnetcore/documentation/listview/getting-start](https://ej2.syncfusion.com/aspnetcore/documentation/listview/getting-started)
###ASP.NET MVC 
Link : https://ej2.syncfusion.com/aspnetmvc/documentation/file-manager/file-operations

ES-837840 : Corrections were added to the documentation.

---

ej2-asp-core-mvc/file-manager/file-operations.md
ej2-asp-core-mvc/listview/EJ2_ASP.NETCORE/getting-started.md

Link : [https://ej2.syncfusion.com/aspnetcore/documentation/listview/getting-start](https://ej2.syncfusion.com/aspnetcore/documentation/listview/getting-started)
###ASP.NET MVC 
Link : https://ej2.syncfusion.com/aspnetmvc/documentation/file-manager/file-operations

ES-837840-hot : Corrections were added to the documentation.

---

ej2-asp-core-mvc/gantt/virtual-scroll.md

Virtual scroll limitation modified.

documentation(838182) : Limitation edited

---

ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/data-binding.md

Description:
Updated the UrlAdaptor UG topic with the example sample.
Scheduler CRUD section
Test cases:
NA
NA

Documentation(ES-822852): Updated the UrlAdaptor UG topic with the example sample

---

ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/editor-template.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/editor-template.md

Include note section for e-field in custom event editor using template for core and mvc platform

Documentation(ES-841586) : To include note section for e-field in custom event editor using template for core and mvc platform

---

ej2-asp-core-mvc/code-snippet/spreadsheet/column-header-change/columnWidthController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/column-header-change/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/column-header-change/tagHelper
ej2-asp-core-mvc/spreadsheet/rows-and-columns.md

Added how to change the header text in column under rows and columns with sample code.

Added column header change content under rows and columns.

---

ej2-asp-core-mvc/code-snippet/spreadsheet/collaborative-editing/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/collaborative-editing/tagHelper
ej2-asp-core-mvc/code-snippet/spreadsheet/import-collaborative-mode/collaborativeImportController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/import-collaborative-mode/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/import-collaborative-mode/tagHelper
ej2-asp-core-mvc/spreadsheet/use-cases/collaborative-editing.md

Added the importing functionality on collaborative editing mode in ASP Core and MVC UG documentation.

Added importing functionality in collaborative editing section.

---

ej2-asp-core-mvc/code-snippet/spreadsheet/change-active-sheet/opencontroller.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/change-active-sheet/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/change-active-sheet/tagHelper
ej2-asp-core-mvc/spreadsheet/how-to/change-active-sheet.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added how to change the active sheet in imported excel file with sample code.

Added change active sheet in the How to section

---

ej2-asp-core-mvc/carousel/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/carousel/EJ2_ASP.MVC/populating-items.md
ej2-asp-core-mvc/carousel/EJ2_ASP.NETCORE/populating-items.md
ej2-asp-core-mvc/tab/how-to/prevent-content-swipe-selection.md

Description:
Resolve link navigation errors in mvc and core platform,
Test cases:
NA
NA

documentation(ES-835222-ugFailure): Resolve errors.

---

ej2-asp-core-mvc/linear-gauge/EJ2_ASP.MVC/getting-started.md

Hi @ChristoIssac  ,
|--|--|
|Task Category|ASP.NET MVC Linear Gauge Money Keywords|
|Content Task Link/Mail Screenshot|https://syncfusion.atlassian.net/browse/CONTENT-7692
|UX task|NA|
|InterlinkPR link|Interlink- https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/1894|
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/171362/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/Angular-Linear-Gauge---Money-Keywords.aspx|
|angular linear gauge|10-100 |4FT |Need to work on FT page |added new section and image|
|linear gauge angular|10-100 |4FT|Need to work on …

SEO-123725-ASP.NET MVC Linear-Gauge Interlink

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

To include UG document for frequently asked requirements for core and mvc platform

Documentation(EJ2-836754) : To include UG document for frequently asked requirements for core and mvc platform

---

ej2-asp-core-mvc/EJ2_ASP.MVC/introduction.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/introduction.md

|**Task Link**|https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/174643|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. No design changes are required.|
|**Solution description**|1.Changed the col width in the introduction.md file|
|**Output screenshots**||
|**Areas affected and ensured**|<ul><li>Changes in the introduction.md file. Previous code didn't affected and ensured in end.</li></ul>|
|**Test cases**|Check the site locally.|
|**Testbed sample location**|-|
|**Additional CheckList**|<ul><li>Did you run the automation against your fix? No</li><li>Is there any API name change?No</li><li>Is there any existing behavior change of other features due to this code change? No.</li><li>Does your new …

174643-Tabletextalignmentissue-dev

---

ej2-asp-core-mvc/toolbar/item-configuration.md

To include note section for input elements inside toolbar for core and mvc platform

Documentation(ES-820307): To include note section for input elements inside toolbar for core and mvc platform

---

ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/timezone.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/timezone.md

To include note section for timezone in scheduler set to specific timezone for core and mvc platforms

Documentation(ES-820304): To include note section for timezone in scheduler set to specific timezone for core and mvc platforms

---

ej2-asp-core-mvc/uploader/EJ2_ASP.NETCORE/how-to/preview-images-before-uploading.md

changed the image preview url in uploader
https://ej2.syncfusion.com/aspnetcore/documentation/uploader/how-to/preview-images-before-uploading

docs(843135): changed the image preview url in uploader

---

ej2-asp-core-mvc/EJ2_ASP.MVC/introduction.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/introduction.md

|**Task Link**|https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/175165|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. No design changes are required.|
|**Solution description**|1.Changed the col width in the introduction.md file|
|**Output screenshots**|-|
|**Areas affected and ensured**|<ul><li>Changes in the introduction.md file. Previous code didn't affected and ensured in end.</li></ul>|
|**Test cases**|Check the site locally.|
|**Testbed sample location**|-|
|**Additional CheckList**|<ul><li>Did you run the automation against your fix? No</li><li>Is there any API name change?No</li><li>Is there any existing behavior change of other features due to this code change? No.</li><li>Does your new …

175165-Changecolumnwidth-hotfix

---

ej2-asp-core-mvc/sidebar/how-to/sidebar-with-partial-view.md

I have corrected the MVC & Core Sidebar component partial view topic in the documentation.

documentation(ES-842913): Need to correct the MVC & Core Sidebar component partial view topic in the documentation.

---

ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/timescale.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/timescale.md

To include note section about the timescale restrictions for core and mvc platforms
NA
NA

Documentation(ES-820305): To include note section about the timescale restrictions for core and mvc platforms

---

ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/ajax-data/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/ajaxbind/razor
ej2-asp-core-mvc/code-snippet/tree-grid/editing/dialog-template/razor
ej2-asp-core-mvc/code-snippet/tree-grid/editing/dialog-template/tagHelper
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/data-binding/data-binding.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/data-binding/data-binding-core.md

Fetch Implementation for the data binding samples.

story(EJ2-841141):Fetch Implementation for the data binding samples.

---

ej2-asp-core-mvc/sidebar/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/sidebar/EJ2_ASP.NETCORE/getting-started.md

I have added a note "How to apply the proper backdrop for the Sidebar main content " section in the Sidebar documentation.

documentation(ES-842915): Need to add a note "How to apply the proper backdrop for the Sidebar main content " section in the Sidebar documentation.

---

ej2-asp-core-mvc/sidebar/style.md

I have added the style "Prevent the animation transition" for the Sidebar component.

documentation(ES-844258): Need to add styles "Prevent the animation transition" for the Sidebar component.

---

ej2-asp-core-mvc/tooltip/style.md

I have added the "How to customize the Tooltip tip inner" missed classes in the EJ2 Tooltip documentation.

documentation(ES-844143): Need to add the "How to customize the Tooltip tip inner" class in the EJ2 Tooltip documentation.

---

ej2-asp-core-mvc/tooltip/content.md

I have added a note "How to set GUID as a Tooltip target" in the EJ2 documentation.

documentation(ES-844132): Need to add a note "How to set GUID as a Tooltip target" in the EJ2 documentation.

---

ej2-asp-core-mvc/code-snippet/document-editor-container/insert-text-image-table/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/insert-text-image-table/tagHelper

Modified code of insert text or image in table programmatically in Core and MVC

(Ej2-840003) : Modify code of insert text or image in table programmatically in Core and MVC

---

ej2-asp-core-mvc/sidebar/style.md

I have added the style "Prevent the animation transition" for the Sidebar component.

documentation(ES-844258): Need to add styles "Prevent the animation transition" for the Sidebar component. 

---

ej2-asp-core-mvc/sidebar/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/sidebar/EJ2_ASP.NETCORE/getting-started.md

I have corrected the mentioned changes.

documentation(ES-842915): Need to add a note "How to apply the proper backdrop for the Sidebar main content " section in the Sidebar documentation. 

---

ej2-asp-core-mvc/diagram/context-menu.md

(EJ2-842539)-ContextMenuIssue

---

ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/frozen.md

Documentaion content update for Frozen rows and columns in Asp Core UG.

documentation(EJ2-846965): Documentaion content update for Frozen rows and columns in Asp Core UG.

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/frozen.md

Documentaion content update for Frozen rows and columns

doc(EJ2-845673): Documentaion content update for Frozen rows and columns

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Adding XlsIO in EJ2 Core and EJ2 MVC UG

847601 - Add XlsIO in EJ2 Core and EJ2 MVC UG - HF

---

ej2-asp-core-mvc/common/EJ2_ASP.MVC/animation.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/animation.md

Need to add Global animation document
We have added global animation method to handle animation of EJ2 components globally. So, we need to add documentation.
Added the UG document that describe about the Global animation method and utilization.
No area is affected due to this changes.
* Is there any API name change? No
* Did you record this case in the unit test or UI test? NA

feature(845883): Need to add Global animation document

---

ej2-asp-core-mvc/auto-complete/virtual-scroll.md
ej2-asp-core-mvc/code-snippet/autocomplete/virtual-scroll/razor
ej2-asp-core-mvc/code-snippet/autocomplete/virtual-scroll/records.cs
ej2-asp-core-mvc/code-snippet/autocomplete/virtual-scroll/tagHelper
ej2-asp-core-mvc/code-snippet/autocomplete/virtual-scroll/virtualscroll.cs
ej2-asp-core-mvc/code-snippet/combobox/virtual-scroll/razor
ej2-asp-core-mvc/code-snippet/combobox/virtual-scroll/records.cs
ej2-asp-core-mvc/code-snippet/combobox/virtual-scroll/tagHelper
ej2-asp-core-mvc/code-snippet/combobox/virtual-scroll/virtualscroll.cs
ej2-asp-core-mvc/code-snippet/dropdownlist/virtuaal-scroll/razor
ej2-asp-core-mvc/code-snippet/dropdownlist/virtuaal-scroll/records.cs
ej2-asp-core-mvc/code-snippet/dropdownlist/virtuaal-scroll/tagHelper
ej2-asp-core-mvc/code-snippet/dropdownlist/virtuaal-scroll/virtualscroll.cs
ej2-asp-core-mvc/combo-box/virtual-scroll.md
ej2-asp-core-mvc/drop-down-list/virtual-scroll.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

documenation added for virtual scroll feature on dropdowns to the ASP core and mvc

documentation(EJ2-846072):documenation added for virtual scroll feature on dropdowns to the ASP core and mvc

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/troubleshooting/document-loading-issues.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/troubleshooting/document-loading-issues.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Hi Parthipan,
I have added the troubleshoot page for databind property usage. Can you please review the changes?
Regards,
Ranjitha A.

EJ2-844780 Added troubleshoot topic to describe databind usage.

---

ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-csv-export/server-exportMvc.cs
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-export/server-exportMvc.cs
ej2-asp-core-mvc/code-snippet/tree-grid/pdf-export/server-export/server-exportMvc.cs
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/excel-export/exporting-treegrid-in-server.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/pdf-export/exporting-treegrid-in-server.md

Added documentation for Server side exporting feature.

Task 847428: Need to add documentation for server side exporting feature

---

ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-csv-export/razor
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-csv-export/server-exportCore.cs
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-csv-export/server-exportMvc.cs
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-csv-export/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-export/razor
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-export/server-exportCore.cs
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-export/server-exportMvc.cs
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-export/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-rotate-header/razor
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-rotate-header/server-rotate-header.cs
ej2-asp-core-mvc/code-snippet/tree-grid/excel-export/server-rotate-header/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/pdf-export/rotate-header/razor
ej2-asp-core-mvc/code-snippet/tree-grid/pdf-export/rotate-header/rotate-header.cs
ej2-asp-core-mvc/code-snippet/tree-grid/pdf-export/rotate-header/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/pdf-export/server-export/razor
ej2-asp-core-mvc/code-snippet/tree-grid/pdf-export/server-export/server-exportCore.cs
ej2-asp-core-mvc/code-snippet/tree-grid/pdf-export/server-export/server-exportMvc.cs
ej2-asp-core-mvc/code-snippet/tree-grid/pdf-export/server-export/tagHelper
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/excel-export/exporting-treegrid-in-server.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/pdf-export/exporting-treegrid-in-server.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/excel-export/exporting-tree-grid-in-server.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/pdf-export/exporting-treegrid-in-server.md

Added documentation for Server side exporting feature.

Task 847956: Update the documentation for server side exporting

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Hi all,
- With this PR, we have added DocIO & Presentation controls in ASP.NET MVC and ASP.NET Core platform UG.
Regards,
Dharanitharan A

ES-846833-Add DocIO & Presentation controls in ASP.NET MVC and ASP.NET Core platform UG-hotfix

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/excel-export/export-multiple-grids.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/pdf-export/export-multiple-grids.md

Updated the limitations for multiple grid export.

Documentation(EJ2-847476):Multiple-Grid-Export Content updated

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Hi all,
- With this PR, we have modified the DocIO and Presentation overview and getting started page links.
Regards,
Dharanitharan A

ES-846833-Modified the DocIO and Presentation links

---

ej2-asp-core-mvc/code-snippet/schedule/virtual-scroll/lazy-load/data.cs
ej2-asp-core-mvc/code-snippet/schedule/virtual-scroll/lazy-load/razor
ej2-asp-core-mvc/code-snippet/schedule/virtual-scroll/lazy-load/tagHelper
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/virtual-scrolling.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/virtual-scrolling.md

UG included for lazy loading feature

docs(ES-378260): UG included for lazy loading feature

---

ej2-asp-core-mvc/accordion/EJ2_ASP.NETCORE/getting-started.md

Remove the unwanted content from Getting Started with ASP.NET Core Accordion Control.

Remove the unwanted content from Getting Started with ASP.NET Core Accordion Control

---

ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.NETCORE/getting-started.md

Remove the unwanted content from Getting Started with ASP.NET Core AccumulationChart Control.

Remove the unwanted content from Getting Started with ASP.NET Core AccumulationChart Control

---

ej2-asp-core-mvc/appbar/EJ2_ASP.NETCORE/getting-started.md

Remove the unwanted content from Getting Started with ASP.NET Core AppBar Control.

Remove the unwanted content from Getting Started with ASP.NET Core AppBar Control

---

ej2-asp-core-mvc/auto-complete/EJ2_ASP.NETCORE/getting-started.md

Getting Started with ASP.NET Core AutoComplete Control.

Getting Started with ASP.NET Core AutoComplete Control

---

ej2-asp-core-mvc/auto-complete/virtual-scroll.md
ej2-asp-core-mvc/combo-box/virtual-scroll.md
ej2-asp-core-mvc/drop-down-list/virtual-scroll.md

documentation(EJ2-849665): resolved the preview samples issue for ASP Core and MVC platforms

documentation(EJ2-849665): resolved the preview samples issue for asp core and mvc

---

ej2-asp-core-mvc/code-snippet/grid/excel-export/new-sheet/razor
ej2-asp-core-mvc/code-snippet/grid/excel-export/new-sheet/tagHelper
ej2-asp-core-mvc/code-snippet/grid/excel-export/same-sheet/razor
ej2-asp-core-mvc/code-snippet/grid/excel-export/same-sheet/tagHelper
ej2-asp-core-mvc/code-snippet/grid/pdf-export/multiple/razor
ej2-asp-core-mvc/code-snippet/grid/pdf-export/same-page/razor
ej2-asp-core-mvc/code-snippet/grid/pdf-export/same-page/same-page.cs
ej2-asp-core-mvc/code-snippet/grid/pdf-export/same-page/tagHelper
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/excel-export/export-multiple-grids.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/excel-export/exporting-grid-in-server.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/pdf-export/export-multiple-grids.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/pdf-export/exporting-grid-in-server.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/excel-export/export-multiple-grids.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/excel-export/exporting-grid-in-server.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/pdf-export/export-multiple-grids.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/pdf-export/exporting-grid-in-server.md

Updated the limitations for multiple grid export.

Documentation(EJ2-847476):Multiple-Grid-Export Content updated 

---

ej2-asp-core-mvc/code-snippet/uploader/custom-template/tagHelper

bug(850304): Delete button not working has been resolved

bug(850304): Delete button not working has been resolved

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/excel-export/exporting-grid-in-server.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/pdf-export/exporting-grid-in-server.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/excel-export/exporting-grid-in-server.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/pdf-export/exporting-grid-in-server.md

Added detail template exporting topic in PDF and Excel exporting of grid component.

Doc(848333): added the limitation of detail template

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

To revamp the UG topics in Core and MVC

Documentation(EJ2-849790): To revamp the UG topics in Core and MVC

---

ej2-asp-core-mvc/auto-complete/virtual-scroll.md
ej2-asp-core-mvc/combo-box/virtual-scroll.md
ej2-asp-core-mvc/drop-down-list/virtual-scroll.md

documentation(EJ2-851766): Need to modify the UG documentation content for virtualization in asp .net core and mvc

documentation(EJ2-851766): Need to modify the UG documentation content for virtualization in asp core

---

ej2-asp-core-mvc/document-editor/how-to/optimize-sfdt.md

Updated the code formatting.

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Hi All,
Modify the TOC file for DocIo and Presentation Product.
Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/851567
Regards
venkatesh

ES-851567 Modify TOC File

---

ej2-asp-core-mvc/file-manager/how-to/custom-file-provider.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Prepare UG on steps to implement own service provider.

bug(ES-841331): hotfix - Addressed the review changes.

---

ej2-asp-core-mvc/code-snippet/tab/customize/customize.cs
ej2-asp-core-mvc/code-snippet/tab/customize/razor
ej2-asp-core-mvc/code-snippet/tab/customize/tagHelper

Improved the selected tab styles customization sample
Selected tab styles customization
**Output:**
NA
NA
**Additional checklist:**

Documentation(ES-379331): Improved the selected tab styles customization sample

---

ej2-asp-core-mvc/chart/EJ2_ASP.MVC/getting-started.md

Changed the code snippet for ASP.NET MVC UG getting started.

(EJ2-848281): Changed the code snippet.

---

ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.NETCORE/getting-started.md

(EJ2-848281): Resolved the conflict issue.

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

I have added XlsIO control UG redirect links.

854120-XlsIOChanges

---

ej2-asp-core-mvc/code-snippet/spreadsheet/find-target-context-menu/opencontroller.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/find-target-context-menu/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/find-target-context-menu/tagHelper
ej2-asp-core-mvc/code-snippet/spreadsheet/open-uploader/opencontroller.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/open-uploader/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/open-uploader/tagHelper
ej2-asp-core-mvc/spreadsheet/how-to/identify-the-context-menu-opened.md
ej2-asp-core-mvc/spreadsheet/how-to/import-an-excel-document-using-file-uploader.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Description:
Added the topic to find the target of the opened context menu
Added topic to import an excel file using uploader component

Documentation(378723): How to find presently opened context menu in spreadsheet

---

ej2-asp-core-mvc/diagram/EJ2_ASP.NETCORE/getting-started.md

To ensure the getting Started Page works fine in all platforms
Typo Error is ASP Core Diagram getting Started Page
updated the Typo error in Diagram getting Started Page.

bug(854436):preview Sample issues in getting started resolved 

---

ej2-asp-core-mvc/diagram/EJ2_ASP.NETCORE/getting-started.md

To ensure the getting Started Page works fine in all platforms
Typo Error is ASP Core Diagram getting Started Page
updated the Typo error in Diagram getting Started Page.

bug(854436): preview Sample issues in getting started resolved in hotfix

---

ej2-asp-core-mvc/code-snippet/spreadsheet/formula-cs2/formulaController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/formula-cs2/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/formula-cs2/tagHelper
ej2-asp-core-mvc/code-snippet/spreadsheet/formula/formulaController.cs
ej2-asp-core-mvc/spreadsheet/formulas.md

Modified the existing user defined function content and added round down formula snippets into the source.

Added ROUNDDOWN formula snippets into the custom defined function.

---

ej2-asp-core-mvc/accordion/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/datepicker/EJ2_ASP.NETCORE/ej1-api-migration.md
ej2-asp-core-mvc/datetimepicker/EJ2_ASP.NETCORE/ej1-api-migration.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
ej2-asp-core-mvc/in-place-editor/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/timepicker/EJ2_ASP.NETCORE/ej1-api-migration.md

Resolved the Liquid syntax error in ASp.NET Core and MVC UG.

Resolved the Liquid syntax error in ASp.NET Core and MVC UG.

---

ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/bullet-chart/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/code-snippet/bullet-chart/getting-started/default/default.cs
ej2-asp-core-mvc/code-snippet/bullet-chart/getting-started/default/razor
ej2-asp-core-mvc/code-snippet/bullet-chart/getting-started/ranges/ranges.cs
ej2-asp-core-mvc/code-snippet/bullet-chart/getting-started/title/razor
ej2-asp-core-mvc/code-snippet/bullet-chart/getting-started/title/title.cs
ej2-asp-core-mvc/code-snippet/bullet-chart/getting-started/tooltip/tooltip.cs
ej2-asp-core-mvc/code-snippet/chart/accumulation-charts/datalabel/initial/initial.cs
ej2-asp-core-mvc/code-snippet/chart/accumulation-charts/datalabel/initial/tagHelper
ej2-asp-core-mvc/code-snippet/range-navigator/getting-started/data/data.cs
ej2-asp-core-mvc/code-snippet/range-navigator/getting-started/data/tagHelper
ej2-asp-core-mvc/code-snippet/smithchart/getting-started/data-label/tagHelper
ej2-asp-core-mvc/code-snippet/smithchart/getting-started/legend/tagHelper
ej2-asp-core-mvc/code-snippet/smithchart/getting-started/marker/tagHelper
ej2-asp-core-mvc/code-snippet/smithchart/getting-started/series/tagHelper
ej2-asp-core-mvc/code-snippet/smithchart/getting-started/title/tagHelper
ej2-asp-core-mvc/code-snippet/smithchart/getting-started/tooltip/tagHelper
ej2-asp-core-mvc/code-snippet/stock-chart/getting-started/populateData/razor
ej2-asp-core-mvc/range-navigator/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/sparkline/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/stock-chart/EJ2_ASP.MVC/getting-started.md

Fixed the issue in getting started in MVC and Core UG.

(EJ2-854558): Fixed the issue in getting started.

---

ej2-asp-core-mvc/accordion/EJ2_ASP.MVC/getting-started-coremvc.md
ej2-asp-mvc-toc.html

Added Getting Started with ASp.NET Core MVC UG accordion control.

Added Getting Started with ASp.NET Core MVC UG accordion control.

---

ej2-asp-core-mvc/accordion/EJ2_ASP.MVC/getting-started-coremvc.md
ej2-asp-core-mvc/accordion/EJ2_ASP.NETCORE/getting-started.md

Unwanted taps removed.

---

ej2-asp-core-mvc/code-snippet/pivot-table/grouping/date-group/tagHelper

We currently have UG documentation for date grouping via the UI. However, code that highlights the date grouping with group interval via code-behind was missed in the provided code example. As a result, we must add the missing code snippet to demonstrate how to use date grouping via code behind. 
Added the groupSettings code in code behind

Documentation(EJ2-848921): Need to update the date grouping code snippet in the group interval sample for the ASP .NET Core platform

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/create-project.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/create-samples.md

I have modified the UG Content

EXT- 1775 - I have modified the UG

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/adding-script-references.md

https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/2257/files

config(853031): Update adding-script-references.md

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/create-project.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/create-samples.md

I have modified the UG Content

EXT-177167

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/selection/check-box-selection.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/selection/check-box-selection.md

Added Limitation for checkbox selection with CellSelection

documentation(857635): Added Limitation

---

ej2-asp-core-mvc/code-snippet/document-editor-container/ruler/document-editor.cs
ej2-asp-core-mvc/code-snippet/document-editor-container/ruler/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/ruler/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor/ruler/document-editor.cs
ej2-asp-core-mvc/code-snippet/document-editor/ruler/razor
ej2-asp-core-mvc/code-snippet/document-editor/ruler/tagHelper
ej2-asp-core-mvc/document-editor/how-to/enable-ruler-in-document-editor-component.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Description:
Ported documentation for ruler

feature(ej2-857020): Documentation for ruler hotfix

---

ej2-asp-core-mvc/code-snippet/document-editor-container/ruler/document-editor.cs
ej2-asp-core-mvc/code-snippet/document-editor-container/ruler/razor
ej2-asp-core-mvc/code-snippet/document-editor-container/ruler/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor/ruler/document-editor.cs
ej2-asp-core-mvc/code-snippet/document-editor/ruler/razor
ej2-asp-core-mvc/code-snippet/document-editor/ruler/tagHelper
ej2-asp-core-mvc/document-editor/how-to/enable-ruler-in-document-editor-component.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Description:
Ported documentation for ruler

feature(ej2-857020): Documentation for ruler

---

ej2-asp-core-mvc/button/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/sidebar/EJ2_ASP.NETCORE/getting-started.md

Worked on page with redirect for core changes.
Regards,
Sharly A.

SEO-177266 - ASP.NET Core Control changes

---

ej2-asp-core-mvc/grid/accessibility.md

Tested the below cases in the share point page and updated the document based on this.
[Accessibility improvement (sharepoint.com)](https://syncfusion.sharepoint.com/sites/EJ2-ClientSide/SitePages/Accessibility-improvement.aspx?OR=Teams-HL&CT=1699535162259&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzEwMTIyNDgwNiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)

Documentation(EJ2-859048):Accessibility document of Grid Component

---

ej2-asp-core-mvc/toast/EJ2_ASP.NETCORE/getting-started.md

Hi @Aishwarya-Ganesan,
Have worked on Page with Redirect links.
Regards,
Yvone.

SEO-177708 Core Page Redirect

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/keyboard-support.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/keyboard-support.md

Need to update the Keyboard shortcuts in the Rich Text Editor Documentation after ensuring all the actions
I have ensured all the actions in the documentation and missing the audio and video shortcuts
No
No
I have updated the audio and video keyboard shortcuts in the Rich Text Editor component documentation.
Yes
No
No
No
 
/label ~bug

bug(860373): Need to update the Keyboard shortcuts in the Rich Text Editor Documentation after ensuring all the actions - Hotfix

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/keyboard-support.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/keyboard-support.md

Need to update the Keyboard shortcuts in the Rich Text Editor Documentation after ensuring all the actions
I have ensured all the actions in the documentation and missing the audio and video shortcuts
No
No
I have updated the audio and video keyboard shortcuts in the Rich Text Editor component documentation.
Yes
No
No
No
 
/label ~bug

bug(860373): Need to update the Keyboard shortcuts in the Rich Text Editor Documentation after ensuring all the actions - Development

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/selection/selection.md

Hi @Aishwarya-Ganesan 
Fixed the broken image in documentation pages, Please check and merge it.
Thanks
Mallika

SEO-178147: Fixed broken image

---

ej2-asp-core-mvc/spreadsheet/formulas.md

Added the description for the newly added formulas.

861780: Added the description for the newly added formulas.

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/custom-tool/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/custom-tool/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/toolbar.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/toolbar.md

861631: Need to prepare documentation for custom toolbar root element  with Css class.

861631: Need to prepare documentation for custom toolbar root element  with Css class.

---

ej2-asp-core-mvc/grid/accessibility.md

Updated Keyboard compatibility in accessibility document

Documentation(EJ2-861810):Accessibility-content Keyboard compatibility update

---

ej2-asp-core-mvc/grid/accessibility.md

Grid Accessibility Content updated

Documentation(EJ2-859048): Grid Accessibility Content update

---

ej2-asp-core-mvc/code-snippet/gantt/editing/customValidation/customValidation.cs
ej2-asp-core-mvc/code-snippet/gantt/editing/customValidation/razor
ej2-asp-core-mvc/code-snippet/gantt/editing/customValidation/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/editing/tab-validating/razor
ej2-asp-core-mvc/code-snippet/gantt/editing/tab-validating/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/editing/tab-validating/validating.cs
ej2-asp-core-mvc/code-snippet/gantt/editing/validating/razor
ej2-asp-core-mvc/code-snippet/gantt/editing/validating/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/editing/validating/validating.cs
ej2-asp-core-mvc/gantt/managing-tasks/validation.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added validation rule doc

---

ej2-asp-core-mvc/spreadsheet/overview.md
ej2-asp-core-toc.html

Added overview for spreadsheet component.

documentation(EJ2-861844): Added overview for spreadsheet component.

---

ej2-asp-core-mvc/code-snippet/gantt/pdf-export/pdfexportindicator/pdfexport.cs
ej2-asp-core-mvc/code-snippet/gantt/pdf-export/pdfexportindicator/razor
ej2-asp-core-mvc/code-snippet/gantt/pdf-export/pdfexportindicator/tagHelper
ej2-asp-core-mvc/gantt/pdf-export/pdf-export.md

Add ug topics for new pdf export improvement
- Common guidelines / Core team guideline
- Specification document
- Requirement document
- Common guidelines / Core team guideline
- Specification document
- Requirement document
Guidelines/documents are not followed.
No
Added ug topics for new pdf export improvement
NA
- Did you run the automation against your fix? NO
- Is there any API name change? NO
- Is there any existing behavior change of other features due to this code change? NO
- Does your new code introduce new warnings or binding errors? NO
- Does your code pass all FxCop and StyleCop rules? NA
- Did you record this case in the unit test or UI test? NO

bug(EJ2-861647):  Add ug topics for new pdf export improvement

---

ej2-asp-core-mvc/code-snippet/document-editor/collaborative-editing/razor
ej2-asp-core-mvc/code-snippet/document-editor/collaborative-editing/tagHelper

Updated Collboration UG for MVC

feature(EJ2-861905): Updated Collboration UG for MVC

---

ej2-asp-mvc-toc.html

Resolved the path issue in 3d chart getting started.

(EJ2-861407): Resolved the path issue in ASP.NET MVC.

---

ej2-asp-mvc-toc.html

Resolved the path issue in 3d chart getting started.

(EJ2-862259): Resolved the path issue in ASP.NET MVC.

---

ej2-asp-core-mvc/code-snippet/diagram/group/groupchild/groupchild.cs
ej2-asp-core-mvc/code-snippet/diagram/group/groupchild/tagHelper
ej2-asp-core-mvc/diagram/group.md

Added Documentation for newly added feature - how to add/remove children in to the specific group at runtime

862149: documentation added for group feature for Diagram

---

ej2-asp-core-mvc/code-snippet/diagram/umldiagramshapes/uml/razor

Issue in Uml sample in MVC
**Solution**
Razor file for the UML sample is missing for MVC. After adding the sample it works fine.

862184: Issue

---

ej2-asp-core-mvc/code-snippet/grid/how-to/empty-record-template/empty-record-template.cs
ej2-asp-core-mvc/code-snippet/grid/how-to/empty-record-template/razor
ej2-asp-core-mvc/code-snippet/grid/how-to/empty-record-template/tagHelper
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/how-to/customize-the-empty-record-template.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/how-to/customize-the-empty-record-template.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Creating UG document for Empty record template

TASK 861830 - Creating UG document for Empty record template

---

ej2-asp-core-mvc/document-editor/collaborative-editing.md
ej2-asp-mvc-toc.html

Resolved the TOC error in collaborative editing.

Resolved the TOC error in collaborative editing.

---

ej2-asp-core-mvc/document-editor/collaborative-editing.md

Resolved the TOC and numbering issue.

Resolved the TOC and numbering issue.

---

ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/appointments.md
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/cell-customization.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/appointments.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/cell-customization.md

Update the restriction details about isSlotAvailable method in core and mvc platform
NA
NA

640354: Update the restriction details about isSlotAvailable method in core and mvc platform

---

ej2-asp-core-mvc/code-snippet/grid/checkbox-excel-filter/ondemandexcelfilter.cs
ej2-asp-core-mvc/code-snippet/grid/checkbox-excel-filter/razor
ej2-asp-core-mvc/code-snippet/grid/checkbox-excel-filter/tagHelper
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/filtering/excel-like-filter.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/filtering/excel-like-filter.md

Ug for Excel or Checkbox filtering with on-demand feature

Doc(EJ2-849633): UG for OnDemand Checkbox/Excel Filter type

---

ej2-asp-core-mvc/code-snippet/button/howto/tooltip/razor
ej2-asp-core-mvc/code-snippet/button/howto/tooltip/tooltip.cs

857333: Title Attributes was not working in Button MVC UG

857333: Title Attributes was not working in Button MVC UG

---

ej2-asp-core-mvc/code-snippet/spreadsheet/filter-cs1/filterController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/filter-cs1/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/filter-cs1/tagHelper
ej2-asp-core-mvc/spreadsheet/how-to/get-filtered-rows.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added get filtered row details in how to section of spreadsheet documentation.

860306: Added get filtered row details in how to section of spreadsheet.

---

ej2-asp-core-mvc/code-snippet/diagram/umldiagramshapes/uml/razor

Uml class documentation issues need to be resolved
**Solution**
The razor file codes are varied from development in hotfix.

854111: Umlfile

---

ej2-asp-core-mvc/code-snippet/diagram/umldiagramshapes/uml/razor

Uml class documentation issues need to be resolved
**Solution**
The runtime adding button are need to be placed and need to add diagram canvas for the symbol palette in UML.

Ej2 854111 uml dev

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/columns/columns-mvc.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/row/row-drag-and-drop.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/virtual-scroll.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/columns/columns-core.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/row/row-drag-and-drop.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/virtual-scroll.md

Added the isPrimaryKey property is necessary to perform RowDD action in row drag and drop section in Mvc and core platform

documentation(381188): rowdd changes

---

ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/getting-started.md

Description:
Added the ASP.NET Core Scheduler GS video in UG
NA
Output:
NA
Test cases:
NA
NA

861836: Added the ASP.NET Core Scheduler GS video in UG

---

ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/exporting.md

Description:
Added the ASP.NET Core Scheduler exporting video in UG
NA
Output:
NA
Test cases:
NA
NA

861836: Added the ASP.NET Core Scheduler exporting video in UG

---

ej2-asp-core-mvc/pivot-table/accessibility.md

Task: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/854623

854623: To improve core&mvc accessibility UG document

---

ej2-asp-core-mvc/message/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/accessibility.md

WCAG version is missing in the accessibility document and some component link are missed.
WE have not verified the accessibility document are having proper WCAG version.
Added WCAG version in the accessibility document and added component link.
Check and update the link of the component and version of WCAG for every release.
Is this common issue …

864782: Need to modify message accessibility document

---

ej2-asp-core-mvc/message/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/message/EJ2_ASP.NETCORE/accessibility.md

WCAG version is missing in the accessibility document and some component link are missed.
WE have not verified the accessibility document are having proper WCAG version.
Added WCAG version in the accessibility document and added component link.
Check and update the link of the component and version of WCAG for every release.
Is this common issue …

864782: Accessibility document modified

---

ej2-asp-core-mvc/diagram/accessibility.md

Changed the content in the accessability.md file

EJ2-Accessability

---

ej2-asp-core-mvc/auto-complete/accessibility.md
ej2-asp-core-mvc/calendar/accessibility.md
ej2-asp-core-mvc/combo-box/accessibility.md
ej2-asp-core-mvc/datepicker/accessibility.md
ej2-asp-core-mvc/daterangepicker/accessibility.md
ej2-asp-core-mvc/datetimepicker/accessibility.md
ej2-asp-core-mvc/dialog/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/dialog/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/drop-down-list/accessibility.md
ej2-asp-core-mvc/in-place-editor/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/in-place-editor/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/maskedtextbox/accessibility.md
ej2-asp-core-mvc/mention/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/mention/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/multi-select/accessibility.md
ej2-asp-core-mvc/numerictextbox/accessibility.md
ej2-asp-core-mvc/textbox/accessibility.md
ej2-asp-core-mvc/timepicker/accessibility.md
ej2-asp-core-mvc/toast/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/toast/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/uploader/wai-aria-accessibility.md

Need to update accessibility document for Notifications components document.
We have not updated accessibility document with reviewed content for Notifications components.
Updated the document for Notifications components with WCAG, Section 508 and ADA content.
No area is affected due to this changes.
* Is there any API name change? No
* Did you record this case in the unit test or UI test? NA

864838: Need to update accessibility document

---

ej2-asp-core-mvc/code-snippet/kanban/keyboard-disable/controller.cs
ej2-asp-core-mvc/code-snippet/kanban/keyboard-disable/datasource.cs
ej2-asp-core-mvc/code-snippet/kanban/keyboard-disable/razor
ej2-asp-core-mvc/code-snippet/kanban/keyboard-disable/tagHelper
ej2-asp-core-mvc/kanban/EJ2_ASP.MVC/accessiblility.md
ej2-asp-core-mvc/kanban/EJ2_ASP.NETCORE/accessiblility.md
ej2-asp-core-toc.html

We have enhanced the accessibility documentation for the Vue Kanban component. To ensure consistency and alignment within the component.
I had already documented accessibility for the Kanban in React Platform. Now I have followed that document and implemented it in an Vue document.
No
No
I have implemented an accessibility document for that Kanban component.
Yes
No
No
No
/label ~bug

864853: Accessibility document improvement of the Kanban in all platform - Hotfix

---

ej2-asp-core-mvc/gantt/accessibility.md

Made improvements in Accessibility vue gantt

documentation(864980): Update changes in the accessibility

---

ej2-asp-core-mvc/tree-grid/accessibility.md

Modified the tree grid accessibility section in core and mvc platform

documentation(864976): accessibility changes

---

ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/appointments.md

Added the ASP.NET Core Scheduler Drag and Drop video in the UG

documentation(ES-864834-AddVideo): Added the ASP.NET Core Scheduler Drag and Drop video in the UG.

---

ej2-asp-core-mvc/3d-chart/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/bullet-chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/bullet-chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/progress-bar/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/progress-bar/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/range-navigator/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/smithchart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/smithchart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/sparkline/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/sparkline/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/stock-chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/stock-chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Accessibility sample changes included in ASP.NET Core and ASP.NET MVC documentation.

(EJ2-864881): Changes included into the Accessibility sample.

---

ej2-asp-core-mvc/file-manager/views.md

documentation(ES-854381): Clear the UG preview issues of EJ2 platform - phase2

documentation(ES-854381): Clear the UG preview issues of EJ2 platform - phase2

---

ej2-asp-core-mvc/code-snippet/dashboard-layout/getting-started/tagHelper
ej2-asp-core-mvc/code-snippet/dropdownbutton/getting-started/demo/tagHelper
ej2-asp-core-mvc/drop-down-button/EJ2_ASP.NETCORE/getting-started.md

Code snippet correction in live page.

Code snippet correction in live page

---

ej2-asp-core-mvc/breadcrumb/accessibility.md
ej2-asp-core-mvc/button-group/accessibility.md
ej2-asp-core-mvc/button/accessibility.md
ej2-asp-core-mvc/check-box/accessibility.md
ej2-asp-core-mvc/color-picker/accessibility.md
ej2-asp-core-mvc/context-menu/accessibility.md
ej2-asp-core-mvc/drop-down-button/accessibility.md
ej2-asp-core-mvc/image-editor/accessibility.md
ej2-asp-core-mvc/list-box/accessibility.md
ej2-asp-core-mvc/menu/accessibility.md
ej2-asp-core-mvc/progress-button/accessibility.md
ej2-asp-core-mvc/query-builder/accessibility.md
ej2-asp-core-mvc/radio-button/accessibility.md
ej2-asp-core-mvc/signature/accessibility.md
ej2-asp-core-mvc/split-button/accessibility.md
ej2-asp-core-mvc/switch/accessibility.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

864907: Accessibility sample modification in mvc core platform

864907: Accessibility sample modification in mvc core platform

---

ej2-asp-core-mvc/spreadsheet/accessibility.md

Need to update the accessibility table in accessibility file.

864972: Need to update the accessibility table in accessibility file.

---

ej2-asp-core-mvc/code-snippet/diagram/connectors/hitPadding/padding.cs
ej2-asp-core-mvc/code-snippet/diagram/connectors/hitPadding/tagHelper
ej2-asp-core-mvc/diagram/connectors.md

Added the hit padding property in connector

EJ2-hitPadding

---

ej2-asp-core-mvc/grid/performance.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

documentation(ej2-1010): performance tips

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/filtering/excel-like-filter.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/filtering/excel-like-filter.md

In failure, EJ2 live publishing

Doc(864982): In failure, EJ2 live publishing

---

ej2-asp-core-mvc/accordion/accessibility.md
ej2-asp-core-mvc/appbar/accessibility.md
ej2-asp-core-mvc/carousel/accessibility.md
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/tab/accessibility.md
ej2-asp-core-mvc/toolbar/accessibility.md

Review correction in accessibility topic in mvc and core documentation.

documentation(ES-864834-reviewCorrection): Review correction in mvc and core docs.

---

ej2-asp-core-mvc/chips/accessibility.md
ej2-asp-core-mvc/dashboard-layout/accessibility.md
ej2-asp-core-mvc/drop-down-tree/accessibility.md
ej2-asp-core-mvc/file-manager/accessibility.md
ej2-asp-core-mvc/listview/accessibility.md
ej2-asp-core-mvc/range-slider/accessibility.md
ej2-asp-core-mvc/sidebar/accessibility.md
ej2-asp-core-mvc/tooltip/accessibility.md
ej2-asp-core-mvc/treeview/accessibility.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to update the accessibility UG content for  all EJ2 FileManager components.
[865175](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/865175)
NA
NA
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
NA 
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
Drafted …

865175: Updated the accessibility UG content for all EJ2 FileManager components

---

ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/bullet-chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/bullet-chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/progress-bar/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/progress-bar/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/range-navigator/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/range-navigator/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/smithchart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/smithchart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/stock-chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/stock-chart/EJ2_ASP.NETCORE/accessibility.md

Changes included in accessibility sample.

(EJ2-864881): Changes included in accessibility sample.

---

ej2-asp-core-mvc/3d-chart/EJ2_ASP.MVC/chart-dimensions.md
ej2-asp-core-mvc/3d-chart/EJ2_ASP.MVC/legend.md
ej2-asp-core-mvc/3d-chart/EJ2_ASP.NETCORE/chart-dimensions.md
ej2-asp-core-mvc/3d-chart/EJ2_ASP.NETCORE/legend.md

(EJ2-864881): Resolved the published report errors.

---

ej2-asp-core-mvc/3d-chart/EJ2_ASP.MVC/chart-dimensions.md
ej2-asp-core-mvc/3d-chart/EJ2_ASP.MVC/legend.md
ej2-asp-core-mvc/3d-chart/EJ2_ASP.NETCORE/chart-dimensions.md
ej2-asp-core-mvc/3d-chart/EJ2_ASP.NETCORE/legend.md
ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/bullet-chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/bullet-chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/progress-bar/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/progress-bar/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/range-navigator/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/range-navigator/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/smithchart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/smithchart/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/stock-chart/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/stock-chart/EJ2_ASP.NETCORE/accessibility.md

Changes included in accessibility sample.

(EJ2-862259): Changes included in accessibility sample.

---

ej2-asp-core-mvc/circular-gauge/accessibility.md
ej2-asp-core-mvc/heatmap-chart/accessibility.md
ej2-asp-core-mvc/linear-gauge/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/linear-gauge/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/maps/accessibility.md
ej2-asp-core-mvc/treemap/accessibility.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to change the content in the accessibility section in our control documentation.
We did not consider this before.
Changed the content in the accessibility section in our components with reference to the react documentation. 
NA
N/A …

864983: Clean the content in the accessibility section.

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/filtering/excel-like-filter.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/filtering/excel-like-filter.md

Doc(863182):Resolve the conflict issue

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/columns/column-spanning.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/column-spanning.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/row/row-spanning.md

Need to add the limitation of column spanning and row spanning in all platform

Doc(867101):Need to add the limitation of column spanning and row spanning in all platform

---

ej2-asp-core-mvc/calendar/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/check-box/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/color-picker/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/datepicker/EJ2_ASP.NETCORE/globalization.md
ej2-asp-core-mvc/document-editor/bookmark.md
ej2-asp-core-mvc/document-editor/header-footer.md
ej2-asp-core-mvc/drop-down-list/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/drop-down-list/filtering.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/columns.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/toolbar-customization.md
ej2-asp-core-mvc/radio-button/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/textbox/EJ2_ASP.NETCORE/getting-started.md

Hello,
I have worked on links with redirects.
Regards,
Beryl.

SEO-179239-Redirect-Links-Core

---

ej2-asp-core-mvc/code-snippet/pivot-table/toolbar/toolbar-customize-inbuilt/razor
ej2-asp-core-mvc/code-snippet/pivot-table/toolbar/toolbar-customize-inbuilt/tagHelper
ej2-asp-core-mvc/code-snippet/pivot-table/toolbar/toolbar-customize/razor
ej2-asp-core-mvc/code-snippet/pivot-table/toolbar/toolbar-customize/tagHelper
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/getting-started.md

To resolve UG sample issues in Core and MVC

Documentation(EJ2-866811) - To resolve UG sample issues in Core and MVC

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/getting-started/razor-pages.md
ej2-asp-core-mvc/combo-box/data-binding.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/editing/edit.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/getting-started-core.md
ej2-asp-core-mvc/menu/EJ2_ASP.NETCORE/getting-started.md

I have worked on redirection links, please review.
Regards,
Scholar.

SEO-178903-Page-With-Redirect

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/getting-started/yeoman.md
ej2-asp-core-mvc/drop-down-list/data-binding.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/getting-started.md

Hi @Aishwarya-Ganesan,
I have changed redirection, please review.
Regards,
Scholar.

SEO-179238-Page-With-Redirect

---

ej2-asp-core-mvc/EJ2_ASP.MVC/getting-started/visual-studio-2017.md
ej2-asp-core-mvc/EJ2_ASP.MVC/introduction.md
ej2-asp-core-mvc/carousel/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/getting-started-core.md

Hi @MallikaRK 
Kindly review my PR below. Thank you.
Regards.
Dickson J

SEO-174654-ASP-MVC-Controls-ej2-UG

---

ej2-asp-core-mvc/document-editor/EJ2_ASP.NETCORE/import.md
ej2-asp-core-mvc/document-editor/link.md

Please review the redirect link changes made
Thanks.
Regards,
Edith.

SEO-178901-ej2-core-page-with-redirect-link

---

ej2-asp-core-mvc/combo-box/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/file-manager/EJ2_ASP.NETCORE/getting-started.md

Have worked on Page with Redirect links.
Regards,
Yvone.

SEO-178567 ASP NET Core MVC Redirect UG

---

ej2-asp-core-mvc/drop-down-list/filtering.md
ej2-asp-core-mvc/gantt/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/numerictextbox/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/iframe.md

Have changed Page with Redirect links.
Regards,
Yvone.

SEO-178115 ASP.NET Core MVC Redirect UG

---

ej2-asp-core-mvc/code-snippet/grid/data-binding/odata/razor
ej2-asp-core-mvc/code-snippet/grid/data-binding/odata/tagHelper
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/row/row-spanning.md

ODataAdaptor URL is not working in DataManager

Doc(856309):ODataAdaptor URL is not working in DataManager

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/globalization-and-localization.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/globalization-and-localization.md

To update locale keywords and corresponding text

Documentation(EJ2-866811) - To update locale keywords and corresponding text

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/compatible-with-essential-JS1.md

Hi @Aishwarya-Ganesan,
Please review the changes made.
Regards,
Scholar.

SEO-179238 Redirection links

---

ej2-asp-core-mvc/floating-action-button/accessibility.md
ej2-asp-core-mvc/rating/accessibility.md
ej2-asp-core-mvc/ribbon/accessibility.md
ej2-asp-core-mvc/skeleton/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/skeleton/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-mvc/speeddial/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/speeddial/EJ2_ASP.NETCORE/accessibility.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to update the Accessibity document for our controls in core and mvc.
**FAB**
- Accessibility in ##Platform_Name## Floating Action Button component
- WAI-ARIA attributes
- Keyboard interaction
- Ensuring accessibility
- See also
**SpeedDial**
- Accessibility in ##Platform_Name## Speed dial component
- WAI-ARIA attributes
- Keyboard interaction
- Ensuring accessibility
- See also
**Rating**
- Accessibility in ##Platform_Name## Rating control
- WAI-ARIA attributes
- Keyboard interaction
- Ensuring accessibility
- See also
**Skeleton**
- Accessibility in ##Platform_Name Skeleton control
- WAI-ARIA attributes
- Ensuring accessibility
- See also
**Ribbon**
- Accessibility in ##Platform_Name## Ribboncontrol
- WAI-ARIA attributes
- Keyboard interaction
- Ensuring accessibility
- See also

documentation(865472): Need to update accessibility document.

---

ej2-asp-core-mvc/code-snippet/uploader/max-count-validation/razor

Modified the selected event binding in uploader
https://ej2.syncfusion.com/aspnetmvc/documentation/uploader/validation

documentation(866142): Modified the selected event binding in uploader

---

ej2-asp-core-mvc/code-snippet/grid/checkbox-excel-filter/ondemandexcelfilter.cs
ej2-asp-core-mvc/code-snippet/grid/checkbox-excel-filter/razor
ej2-asp-core-mvc/code-snippet/grid/checkbox-excel-filter/tagHelper

Doc(867101):Resolve the issue

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Navigation link updated for In-place editor component.

868918: Navigation link updated for In-place editor component.

---

ej2-asp-core-mvc/stepper/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/accessibility.md

Need to update the Accessibity document for Stepper.
**Stepper**
- Accessibility in ##Platform_Name## Stepper control
- WAI-ARIA attributes
- Keyboard interaction
- Ensuring accessibility
- See also

documentation(865622): Need to update accessibility document. 

---

ej2-asp-core-mvc/stepper/EJ2_ASP.MVC/events.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/animation.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/events.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/globalization.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/linear-flow.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/orientations.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/steps-validation.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/steps.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/steptypes.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/template.md
ej2-asp-core-mvc/stepper/EJ2_ASP.NETCORE/tooltip.md

Need to update path mappings for code blocks in Stepper.
Update the code snippet path with correct file name.

857516: Updated the CS mapping for Stepper

---

ej2-asp-core-mvc/code-snippet/schedule/customization/weekend-cell-color/data.cs
ej2-asp-core-mvc/code-snippet/schedule/customization/weekend-cell-color/razor
ej2-asp-core-mvc/code-snippet/schedule/customization/weekend-cell-color/tagHelper
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/cell-customization.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/cell-customization.md

**Description**:
Added the topic for weekend cell customization in Scheduler
**Areas affected and ensured**:
Cell Customizations
**Test cases**:
NA
**Test bed sample location**:
NA
**Additional checklist**:

Documentation(ES-379228): Added the topic for weekend cell customization in Scheduler

---

ej2-asp-core-mvc/progress-button/spinner-and-progress.md
ej2-asp-core-mvc/spreadsheet/how-to/save-and-open-spreadsheet-data-as-base64-string.md

Have worked on Missing H1.
Regards,
Yvone.

SEO-179769 ASP.NET Core MVC Missing H1

---

ej2-asp-core-mvc/code-snippet/splitter/content-template/controller.cs
ej2-asp-core-mvc/code-snippet/splitter/content-template/tagHelper
ej2-asp-core-mvc/splitter/EJ2_ASP.NETCORE/pane-content.md

Added the content template section in splitter
https://ej2.syncfusion.com/aspnetcore/documentation/splitter/pane-content?cs-save-lang=1&cs-lang=razor

Documentation(858228): Added the content template section in splitter

---

ej2-asp-core-mvc/splitter/EJ2_ASP.NETCORE/pane-content.md

Need to resolve the Liquid syntax error in ASP.NET Core UG Staging.
_if_ tag was never closed in ej2-asp-core/splitter/pane-content.md.
Resolved the Liquid syntax error by  _if_ tag was closed in ej2-asp-core/splitter/pane-content.md.
Is this common issue need to be addressed in the same …

868918: Liquid syntax error resolved in staging links.

---

ej2-asp-core-mvc/splitter/EJ2_ASP.NETCORE/pane-content.md

Need to resolve the Liquid syntax error in ASP.NET Core UG Live.
_if_ tag was never closed in ej2-asp-core/splitter/pane-content.md.
Resolved the Liquid syntax error by  _if_ tag was closed in ej2-asp-core/splitter/pane-content.md.
Is this common issue need to be addressed in the same component …

868918: Liquid syntax error resolved in live links.

---

ej2-asp-core-mvc/code-snippet/grid/columns/autofitspecificcolumn/autofitspecificcolumn.cs
ej2-asp-core-mvc/code-snippet/grid/columns/autofitspecificcolumn/razor
ej2-asp-core-mvc/code-snippet/grid/columns/autofitspecificcolumn/tagHelper
ej2-asp-core-mvc/code-snippet/grid/edit/showaddnewrow/razor
ej2-asp-core-mvc/code-snippet/grid/edit/showaddnewrow/showaddnewrow.cs
ej2-asp-core-mvc/code-snippet/grid/edit/showaddnewrow/tagHelper
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/clipboard.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/columns/auto-fit-columns.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/editing/in-line-editing.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/row/row-drag-and-drop.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/clipboard.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/auto-fit-columns.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/editing/in-line-editing.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/row/row-drag-and-drop.md

Need to add UG documentation for feature wise in all platform

874761: Need to add UG documentation for feature wise in all platform

---

ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/version-compatibility.md

Updated .NET 8.0 version in ASP.NET Core

564560 : version-compatibility updated

---

ej2-asp-core-mvc/splitter/EJ2_ASP.NETCORE/pane-content.md

Resolved the issue "improper if tag on splitter documentation"

Documentation(858228): Resolved the issue "improper if tag on splitter documentation"

---

ej2-asp-core-mvc/common/EJ2_ASP.MVC/how-to/troubleshoot.md

Need to update the broken KB link in ASP.NET MVC platform.

567420 - updated KB link

---

ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/resources.md

documentation(ES-566926): Added Core scheduler with multiple resources youtube video.

documentation(ES-566926): Added Core scheduler with multiple resources youtube video.

---

ej2-asp-core-mvc/heatmap-chart/bubble-heatmap.md

Worked on HeatMap Chart changes.
Regards,
Sharly A.

SEO-180850-HeatMap-Chart-Changes

---

ej2-asp-core-mvc/code-snippet/query-builder/clone/default.cs
ej2-asp-core-mvc/code-snippet/query-builder/clone/razor
ej2-asp-core-mvc/code-snippet/query-builder/clone/tagHelper
ej2-asp-core-mvc/code-snippet/query-builder/import-export/export-mongo/default.cs
ej2-asp-core-mvc/code-snippet/query-builder/import-export/export-mongo/razor
ej2-asp-core-mvc/code-snippet/query-builder/import-export/export-mongo/tagHelper
ej2-asp-core-mvc/code-snippet/query-builder/import-export/export-sql2/default.cs
ej2-asp-core-mvc/code-snippet/query-builder/import-export/export-sql2/razor
ej2-asp-core-mvc/code-snippet/query-builder/import-export/export-sql2/tagHelper
ej2-asp-core-mvc/code-snippet/query-builder/import-export/export-sql3/default.cs
ej2-asp-core-mvc/code-snippet/query-builder/import-export/export-sql3/razor
ej2-asp-core-mvc/code-snippet/query-builder/import-export/export-sql3/tagHelper
ej2-asp-core-mvc/code-snippet/query-builder/import-export/import-mongo/default.cs
ej2-asp-core-mvc/code-snippet/query-builder/import-export/import-mongo/razor
ej2-asp-core-mvc/code-snippet/query-builder/import-export/import-mongo/tagHelper
ej2-asp-core-mvc/code-snippet/query-builder/import-export/import-sql2/default.cs
ej2-asp-core-mvc/code-snippet/query-builder/import-export/import-sql2/razor
ej2-asp-core-mvc/code-snippet/query-builder/import-export/import-sql2/tagHelper
ej2-asp-core-mvc/code-snippet/query-builder/import-export/import-sql3/default.cs
ej2-asp-core-mvc/code-snippet/query-builder/import-export/import-sql3/razor
ej2-asp-core-mvc/code-snippet/query-builder/import-export/import-sql3/tagHelper
ej2-asp-core-mvc/code-snippet/query-builder/lock/default.cs
ej2-asp-core-mvc/code-snippet/query-builder/lock/razor
ej2-asp-core-mvc/code-snippet/query-builder/lock/tagHelper
ej2-asp-core-mvc/query-builder/clone-group-rule.md
ej2-asp-core-mvc/query-builder/import-export.md
ej2-asp-core-mvc/query-builder/lock-group-rule.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

prepared UG for QB new features
- Inline SQL - Import and Export
- Parameter SQL - Import and Export
- Named Parameter SQL - Import and Export
- MongoDB - Import and Export
- Clone Group/Rule
- Lock Group/Rule

875971: prepared UG for QB new features

---

ej2-asp-core-mvc/image-editor/annotation.md

Added additional parameters in Image Editor Annotations public methods in all platforms
- Ellipse
- Rectangle
- Line
- Arrow
- Path
- Text
- Image

876447: Added additional parameters in Image Editor Annotations public methods

---

ej2-asp-core-mvc/code-snippet/gantt/projectview-multitaskbar-cs1/projectview-multitaskbar.cs
ej2-asp-core-mvc/code-snippet/gantt/projectview-multitaskbar-cs1/razor
ej2-asp-core-mvc/code-snippet/gantt/projectview-multitaskbar-cs1/tagHelper
ej2-asp-core-mvc/gantt/taskbar.md

Adding document for multi taskbar support in project view.
NA
Added documentation for multi taskbar support in project view..
NA
NA
* [ x  NA
NA
Is there any new API or …

76168: Project view multi taskbar asp

---

ej2-asp-core-mvc/toast/EJ2_ASP.NETCORE/timeout.md

Have worked on Page with Redirect, please review.
Regards,
Yvone.

SEO-180841 ASP.NET Core Toast

---

ej2-asp-core-mvc/image-editor/filter.md
ej2-asp-core-mvc/image-editor/finetune.md

Added note content for filter and finetuning limitation in iOS.

871837: filter and finetune limitation

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/columns/auto-fit-columns.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/auto-fit-columns.md

876379: Resolve the conflict

---

ej2-asp-core-mvc/code-snippet/query-builder/clone/razor
ej2-asp-core-mvc/code-snippet/query-builder/clone/tagHelper

set showButtons false for clone sample

871837: set showButtons false for clone sample

---

ej2-asp-core-mvc/circular-chart-3d/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/circular-chart-3d/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added api reference to 3d circular chart.

875329: Added api reference in circular chart 3d in ASP.NET Core and ASP.NET MVC UG.

---

ej2-asp-core-mvc/spreadsheet/formulas.md

Need to add the formula list and decimal separator support information in the UG.
Referred competitor UG document and checked the samples to showcase the formulas.
Added the formula list and decimal separator support information in the UG.
NA
NA
Test
NA

documentation(877091): Updated Formula list and decimal separator information in formula section.

---

ej2-asp-core-mvc/uploader/EJ2_ASP.MVC/async.md

877017: Changed service URL links for Input and dropdown components documentations.

877017: Changed service URL links for Input and dropdown components documentations.

---

ej2-asp-core-mvc/textarea/style-appearance.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added UG documentation for new TextArea component in asp.net Mvc and Core.
NA
Added UG documentation for new TextArea component in asp.net Mvc and Core.
NA
NA
Is there any …

871738: Added UG documentation for new TextArea component in asp.net

---

ej2-asp-core-mvc/code-snippet/circular-chart/user-interaction/export/razor
ej2-asp-core-mvc/code-snippet/circular-chart/user-interaction/export/tagHelper

Resolved preview issues in circular chart 3d features samples.

875329: Resolved preview issues in circular chart 3d in ASP.NET Core and ASP.NET MVC UG.

---

ej2-asp-core-mvc/timeline/EJ2_ASP.MVC/align.md
ej2-asp-core-mvc/timeline/EJ2_ASP.MVC/events.md
ej2-asp-core-mvc/timeline/EJ2_ASP.MVC/items.md
ej2-asp-core-mvc/timeline/EJ2_ASP.MVC/orientations.md
ej2-asp-core-mvc/timeline/EJ2_ASP.MVC/reverse.md
ej2-asp-core-mvc/timeline/EJ2_ASP.MVC/template.md
ej2-asp-core-mvc/timeline/EJ2_ASP.NETCORE/align.md
ej2-asp-core-mvc/timeline/EJ2_ASP.NETCORE/events.md
ej2-asp-core-mvc/timeline/EJ2_ASP.NETCORE/items.md
ej2-asp-core-mvc/timeline/EJ2_ASP.NETCORE/orientations.md
ej2-asp-core-mvc/timeline/EJ2_ASP.NETCORE/reverse.md
ej2-asp-core-mvc/timeline/EJ2_ASP.NETCORE/template.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to map API link to the timeline property.

UG(875578): Need to Map API link to the timeline property.

---

ej2-asp-core-mvc/diagram/bpmn-shapes.md
ej2-asp-core-mvc/diagram/interaction/keyboard.md

Documentation added for the feature implemented.
Keyboard interaction.
BPMN text annotation revamped

875008: featureUG

---

ej2-asp-core-mvc/uploader/EJ2_ASP.NETCORE/async.md

Include github sample in documentation

Documentation(EJ2-872912): Include github sample in documentation

---

ej2-asp-core-mvc/diagram/nodes.md

1.Add content on how to customize the style of main node on multiple selection

877695: mainNode

---

ej2-asp-core-mvc/textarea/events.md

877017: Resolved file path error in textarea component.

877017: Resolved file path error in textarea component.

---

ej2-asp-core-mvc/code-snippet/spreadsheet/formula-cs3/formulaController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/formula-cs3/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/formula-cs3/tagHelper
ej2-asp-core-mvc/spreadsheet/formulas.md

Need to add the formula list and decimal separator support information in the UG.
Referred competitor UG document and checked the samples to showcase the formulas.
Added the formula list and decimal separator support information in the UG.
Added a sample JSX and TSX which render the formulas with the list and decimal separator.
NA
NA
Test
NA

documentation(EJ2-876470): Culture based list and decimal separator support UG added

---

ej2-asp-core-mvc/timeline/EJ2_ASP.MVC/items.md
ej2-asp-core-mvc/timeline/EJ2_ASP.NETCORE/items.md

Need to fix timeline UG items table alignment issue.

UG9877772): Timeline UG items table alignment issue.

---

ej2-asp-core-mvc/timeline/EJ2_ASP.MVC/items.md
ej2-asp-core-mvc/timeline/EJ2_ASP.NETCORE/items.md

Need to Change item property to e-timeline-item tag helper..

UG(877772): Change item property to e-timeline-item tag helper.

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/server-side-pivot-engine.md

Kindly review the issue fix changes.
Regards,
Edith.

SEO-180849-ej2-mvc-grid-issue-fixes

---

ej2-asp-core-mvc/code-snippet/gantt/pdf-export/pdfexport-header-Template/tagHelper

Adding document content to taskbar template, tasklabel template and header tempalte.
NA
Added documentation content to  taskbar template, tasklabel template and header tempalte.
NA
NA
* [ x  NA
NA
Confirm whether this feature is ensured in …

875490: Adding document content to taskbar template, tasklabel template and header tempalte.

---

ej2-asp-core-mvc/gantt/taskbar.md

Adding document for multi taskbar support in project view.
NA
Added documentation for multi taskbar support in project view..
NA
NA
* [ x  NA
NA
Is there any new API or …

76168: Project view multi taskbar asp image updated

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/form-designer/create-programmatically.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/form-designer/create-with-user-interface-interaction.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/form-designer/create-programmatically.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/form-designer/create-with-user-interface-interaction.md

Formfield image paths are committed properly as other md files

835457: formfield image paths are committed properly as other md files

---

ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/category-axis.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/logarithmic-axis.md
ej2-asp-core-mvc/code-snippet/chart/getting-started/multi-export/tagHelper

Description
Need to add video in log axis and fixed issue in multiple chart export sample in ASP.NET core.

876007: Fixed CR issue for April 16.

---

ej2-asp-core-mvc/code-snippet/image-editor/annotation/adjust-stroke-color/razor
ej2-asp-core-mvc/code-snippet/image-editor/annotation/adjust-stroke-color/tagHelper

Image editor freehand colour change was not working in mvc platform

880554: Image editor freehand colour change was not working in all EJ2 platforms 

---

ej2-asp-core-mvc/code-snippet/image-editor/annotation/adjust-stroke-color/razor
ej2-asp-core-mvc/code-snippet/image-editor/annotation/adjust-stroke-color/tagHelper

Image editor freehand colour change was not working in all EJ2 platforms

880554: Image editor freehand colour change was not working in all EJ2 platforms

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/virtual-scrolling.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/virtual-scrolling.md

875577: UG failure resolved.

---

ej2-asp-core-mvc/timeline/EJ2_ASP.MVC/items.md
ej2-asp-core-mvc/timeline/EJ2_ASP.NETCORE/items.md

Need to modify item e-timeline-item tag helper..

UG(877772): Modify item tag helper tag

---

ej2-asp-core-mvc/uploader/EJ2_ASP.MVC/async.md
ej2-asp-core-mvc/uploader/EJ2_ASP.NETCORE/async.md

Provide support for catch the returned response body in uploader component.
- https://dev.azure.com/EssentialStudio/b6db0cd2-2cc5-4f25-849c-c7a027012a1a/_apis/wit/attachments/9feb4c86-5abf-4dc0-8193-6899a5aa488a?fileName=Specification%20Document%20-%20Support%20for%20Returning%20Response%20Body%20Syncfusion%20JavaScript%20File%20Upload%20Component.docx&download=true&api-version=5.0-preview.2
- https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/83631
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Docu …

83631: Provide support for catch the returned response body in upload

---

ej2-asp-core-mvc/ribbon/EJ2_ASP.MVC/keytip.md

Need to resolve the documentation conflicts reported for the ribbon keytip file..

UG(885071): Need to solved the conflict in ribbon keytip.

---

ej2-asp-core-mvc/spreadsheet/rows-and-columns.md
ej2-asp-core-mvc/toast/EJ2_ASP.MVC/timeout.md
ej2-asp-core-mvc/tooltip/animation.md

Hi @Aishwarya-Ganesan,
Have worked on On Page changes and Page with Redirect links
Regards,
Yvone.

SEO-182846 ASP.NET Core MVC Page with Redirect

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/2805/files#diff-a634864d389872a35e1e141f857db3390bc51466fc13c760f315403ba1a0a808 -  In this PR, the toc for the newly added MD files is included, but in the latest hotfix branch, the toc alone was missed, so I manually added the toc file. 

875662: Missed TOC files updated for core and mvc 

---

ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/ajax-data/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/custom-adaptor/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/loading-animation/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/offline-data/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-core/remote-data/tagHelper
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/ajaxbind/razor
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/customadaptor/razor
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/loading-animation/razor
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/offline/razor
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/param/razor
ej2-asp-core-mvc/code-snippet/tree-grid/data-binding-mvc/remote-data/razor

Changed service link in remote samples.

887205: Changed service link in Asp.Net Core\MVC documentation

---

ej2-asp-core-mvc/code-snippet/gantt/data-binding/ajaxBinding/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/data-binding/lazy-loading/razor
ej2-asp-core-mvc/code-snippet/gantt/data-binding/lazy-loading/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/data-binding/remoteData/razor
ej2-asp-core-mvc/code-snippet/gantt/data-binding/remoteData/tagHelper

changing URL of datasource in asp-core-mvc files
NA
Changed the datasource url in gantt
The reported issue replicated only when validation rule is applied to column. Missed to test this case.
NA
NA
NA
* [ x  NA
NA
Is there any new API or existing API name change?
Is …

887541: changing URL of datasource in asp-core-mvc files

---

ej2-asp-core-mvc/code-snippet/listview/databinding/remote-data/razor
ej2-asp-core-mvc/code-snippet/listview/databinding/remote-data/tagHelper

885514: Updated web service url link

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Resolved File Path Validation in Hotfix branch

858844: Resolved File Path Validation in Hotfix branch

---

ej2-asp-core-mvc/document-editor/content-control.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added UG for Content control in Core and MVC

888515: Added UG for Content control in Core and MVC

---

ej2-asp-core-mvc/spreadsheet/protect-sheet.md

Added content for the Read-only feature in Spreadsheet.

documentation(EJ2-890332): Added content for the Read-only feature in Spreadsheet.

---

ej2-asp-core-mvc/spreadsheet/data-binding.md

Added content for the fieldsOrder feature in Spreadsheet.

documentation(EJ2-890332): Added content for the fieldsOrder feature in Spreadsheet.

---

ej2-asp-core-mvc/common/EJ2_ASP.MVC/internationalization.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/internationalization.md

Need to add millisecond custom format under globalization.

600228: add millisecond custom format

---

ej2-asp-core-mvc/auto-complete/virtual-scroll.md
ej2-asp-core-mvc/combo-box/virtual-scroll.md
ej2-asp-core-mvc/drop-down-list/virtual-scroll.md
ej2-asp-core-mvc/multi-select/virtual-scroll.md

Need to update the documentation for blazor multiselect component 
NA
we have added documentation for mutiselect virtualization in blazor.
- Checked with fix component behavior
* []  Yes, Tag `breaking-issue`. 
NA
NA
Is there any new API or existing API name change?
Is there any existing behavior change due to this code …

887665: updated the virtualization sample

---

ej2-asp-core-mvc/code-snippet/textarea/rows-cols/razor
ej2-asp-core-mvc/code-snippet/textarea/rows-cols/tagHelper
ej2-asp-core-mvc/textarea/rows-columns.md

Textarea component rows and colums property changes in Documentation on EJ2 Platform
Need to add Textarea component rows and colums property changes in Documentation on EJ2 Platform
Added Textarea component rows and colums property changes in Documentation on EJ2 Platform
NA
NA
Is there …

890708: Textarea component documentation

---

ej2-asp-core-mvc/code-snippet/chart/dynamic-update/add-point/razor
ej2-asp-core-mvc/code-snippet/chart/dynamic-update/remove-point/razor

Added volume 2 new features sample in ASP.NET Core and ASP.NET MVC UG.

889696: Added volume 2 new features sample in ASP.NET Core and ASP.NET MVC documentation.

---

ej2-asp-core-mvc/uploader/EJ2_ASP.MVC/async.md
ej2-asp-core-mvc/uploader/EJ2_ASP.NETCORE/async.md

Need to add the client side response in uploader component documentation
- https://dev.azure.com/EssentialStudio/b6db0cd2-2cc5-4f25-849c-c7a027012a1a/_apis/wit/attachments/9feb4c86-5abf-4dc0-8193-6899a5aa488a?fileName=Specification%20Document%20-%20Support%20for%20Returning%20Response%20Body%20Syncfusion%20JavaScript%20File%20Upload%20Component.docx&download=true&api-version=5.0-preview.2
- https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/83631
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documen …

891182: Need to add the client side response in uploader component documentation

---

ej2-asp-core-mvc/diagram/labels.md

##Description
API Reference for rotation reference is updated.

866112: API for rotation reference updated

---

ej2-asp-core-mvc/diagram/ports.md

Update in UG Documentation for the property- connection Direction

851216: Update in Ug documentation

---

ej2-asp-core-mvc/code-snippet/spreadsheet/read-only/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/read-only/readOnlyController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/read-only/tagHelper
ej2-asp-core-mvc/spreadsheet/protect-sheet.md

Need to code snippets and samples for Read-Only feature details in the UG document.

documentation(EJ2-891146): Need to add code snippets and sample for Read-Only feature

---

ej2-asp-core-mvc/spreadsheet/keyboard-shortcuts.md

Description:
Added content for the newly added keyboard shortcuts in Spreadsheet.

documentation(891499): Added content for the newly added keyboard shortcuts.

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/getting-started.md

To update documentation for the getting started page for Rich text editor component for all platform
Changed the documentation for the getting started page for Rich text editor component for all platform

890672: To update documentation for the getting started page for Rich text editor component for all platform

---

ej2-asp-core-mvc/code-snippet/spreadsheet/field-mapping/fieldMappingController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/field-mapping/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/field-mapping/tagHelper
ej2-asp-core-mvc/spreadsheet/data-binding.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to add the sample for fields order feature in Spreadsheet.

documentation(EJ2-891308): Need to code snippets and samples for the Fields Order feature

---

ej2-asp-core-mvc/multicolumn-combobox/EJ2_ASP.MVC/virtualization.md
ej2-asp-core-mvc/multicolumn-combobox/EJ2_ASP.NETCORE/virtualization.md

Need to fix the documentation failures due to the MCCB component.

UG(892244): Fixed documentation failure due to code snippet file path.

---

ej2-asp-core-mvc/diagram/connectors.md
ej2-asp-core-mvc/diagram/group.md
ej2-asp-core-mvc/diagram/nodes.md

Provide support to add diagram nodes or connectors collection dynamically through API method

---

ej2-asp-core-mvc/chart/EJ2_ASP.MVC/working-with-data.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/working-with-data.md
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/custom-adaptor/custom-adaptor.cs
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/custom-adaptor/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/custom-adaptor/tagHelper
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/odata-adaptor/odata-adaptor.cs
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/odata-adaptor/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/odata-adaptor/tagHelper
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/odatav4-adaptor/odatav4-adaptor.cs
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/odatav4-adaptor/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/odatav4-adaptor/tagHelper
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/offline-mode/offline-mode.cs
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/offline-mode/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/offline-mode/tagHelper
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/web-adaptor/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/web-adaptor/tagHelper
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/web-adaptor/web-adaptor.cs

Revamp the documentation for the chart.

889696: Revamp the documentation for the chart.

---

ej2-asp-core-mvc/code-snippet/spreadsheet/open-from-json/openController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/open-from-json/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/open-from-json/tagHelper
ej2-asp-core-mvc/code-snippet/spreadsheet/save-as-json/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/save-as-json/saveController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/save-as-json/tagHelper
ej2-asp-core-mvc/spreadsheet/open-save.md

Description:
Added code sample and UG content for Save as json feature.

Documentation(EJ2-891499): Added code sample and UG content for  json serialization feature.

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Disabled Items Documentation
Need to add Disabled Items Documentation
Added Disabled Items Documentation
NA
NA
Is there any new API or existing API name change?
Do the code changes cause any memory leak and performance issue? …

891182: 890804: Disabled Items Documentation

---

ej2-asp-core-toc.html

Image Editor sample not loaded in core platform
link was improper for z-order in core platform
changed the link to "/ej2-asp-core/image-editor/z-order"
Post the output screenshots if an UI is …

892297: Image Editor sample not loaded in core platform

---

ej2-asp-core-mvc/code-snippet/spreadsheet/save-as-json/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/save-as-json/tagHelper

Description:
Updated openUrl in spreadsheet save as json.

documentation(EJ2-891499): Updated openUrl in spreadsheet save as json.

---

ej2-asp-core-mvc/code-snippet/bullet-chart/target-bar/target-types/tagHelper

Resolved the targetTypes issue in Core documentation.

889696: Resolved the bullet chart targetType issue in Core documentation.

---

ej2-asp-core-mvc/code-snippet/bullet-chart/target-bar/target-types/tagHelper

Resolved the targetTypes issue in Core documentation.

889696: Resolved the bullet chart targetType issue in Core documentation

---

ej2-asp-core-mvc/code-snippet/chart/axis/working-data/custom-adaptor/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/custom-adaptor/tagHelper
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/offline-mode/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/offline-mode/tagHelper
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/web-adaptor/razor
ej2-asp-core-mvc/code-snippet/chart/axis/working-data/web-adaptor/tagHelper

889696: Changed the service link for Core and MVC documentation..

---

ej2-asp-core-mvc/toast/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/toast/EJ2_ASP.NETCORE/accessibility.md

893672: Changed Accessibility support as N/A.

893672: Changed Accessibility support as N/A.

---

ej2-asp-core-mvc/code-snippet/gantt/how-to/draganddrop/razor
ej2-asp-core-mvc/code-snippet/gantt/how-to/draganddrop/tagHelper

Modified code snippet in how to drag and drop from another component section

833342:  Modified code snippet in how to drag and drop from another component section

---

ej2-asp-core-mvc/spreadsheet/notes.md

Description:
Need to add limitation to the Notes in Spreadsheet UG.

documentation(EJ2-894158): Need to add limitation to the Notes in Spreadsheet UG

---

ej2-asp-core-mvc/common/EJ2_ASP.MVC/accessibility.md

updated href value for the empty controls in common accessibility

892200: Updated accessibility Control URLs

---

ej2-asp-core-mvc/spreadsheet/filter.md
ej2-asp-core-mvc/spreadsheet/open-save.md
ej2-asp-core-mvc/spreadsheet/sort.md
ej2-asp-core-mvc/spreadsheet/worksheet.md

Description:
Need to add section 'Import and Export' and move 'import an excel document using file uploader' to it.
Need to move 'How to save and open spreadsheet data as base64 string' to Open and save section.
Need to move 'How to print' to the Worksheet section.
Need to move 'How to get filtered rows ' to Filtering section.
Need to move 'How to sort a range by a custom list' to Sorting section.
Need to move 'How to insert sheet programmatically and make it active sheet' to Worksheet section.

documentation(EJ2-889454): Need to move the following sections from How To section to feature section in Spreadsheet UG 

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/restricting-zoom-in-mobile-mode.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/restricting-zoom-in-mobile-mode.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Description
Added content to the "How to" section for the JavaScript and TypeScript platform, covering the topic "How to Restrict Zoom Percentage on Mobile Devices."

883856: restrict Zoom

---

ej2-asp-core-mvc/code-snippet/pivot-table/getting-start-mvc/fieldlist/razor
ej2-asp-core-mvc/code-snippet/pivot-table/getting-start-mvc/fieldlist/tagHelper
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/getting-started.md

Update Getting Started UG Document for Core and MVC

894649: Update Getting Started UG Document for Core and MVC-Hotfix

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/add-save-button.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/add-save-button.md

Description:
Added Documentation for 'How to add Save button in built-in toolbar' for MVC and Core Platform

895039 save button

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

updated over view path in core

Update overview path

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/resolve-pdfium-issue.md

Added additional details to address the pdfium issue that occurred during the deployment

Added additional details to address the pdfium issue that occurred during the deployment

---

ej2-asp-core-mvc/common/EJ2_ASP.MVC/showcase-samples.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/showcase-samples.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added showcase sample in ASP.NET Core and MVC platform.

885233: Added showcase samples list

---

ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/appointments.md

Added ASP.NET Core Scheduler event template you tube video in UG.

898267: Added ASP.NET Core Scheduler event template you tube video in UG.

---

ej2-asp-core-mvc/EJ2_ASP.MVC/appearance/icons.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/appearance/icons.md

Added the Material 3 icons in icons topic in MVC and core documentation.

898255: Added the material 3 icons in MVC and core documentation.

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/open-pdf-file/from-azure-blob-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/save-pdf-file/to-azure-blob-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/open-pdf-file/from-azure-blob-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/save-pdf-file/to-azure-blob-storage.md

Provide sample and steps to load the PDF document from Azure Blob Storage in Standalone PDF Viewer

Ej2 898059 Open Save Azure Blob Storage

---

ej2-asp-core-mvc/code-snippet/file-manager/flat-data/FlatDataController_core.cs
ej2-asp-core-mvc/code-snippet/file-manager/flat-data/FlatDataController_mvc.cs
ej2-asp-core-mvc/code-snippet/file-manager/flat-data/ServiceController.cs
ej2-asp-core-mvc/code-snippet/file-manager/flat-data/razor
ej2-asp-core-mvc/code-snippet/file-manager/flat-data/tagHelper
ej2-asp-core-mvc/file-manager/flat-data.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Included a UG documentation for File Manager with Flat Data in Asp.net core and mvc.

Added UG for FlatData in Asp.net core and mvc and committed.

---

ej2-asp-core-mvc/code-snippet/barcode/qrcode/logo/tagHelper

899102: UG updated for QrCode Logo

---

ej2-asp-core-mvc/document-editor/collaborative-editing/overview.md
ej2-asp-core-mvc/document-editor/collaborative-editing/using-redis-cache-asp-net.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

897352: Adding changes in Redis UG

---

ej2-asp-core-mvc/document-editor/collaborative-editing/overview.md
ej2-asp-core-mvc/document-editor/collaborative-editing/using-dot-net.md
ej2-asp-core-mvc/document-editor/collaborative-editing/using-redis-cache-asp-net.md

Adding platform name for collaborative editing

897352: Adding platform name for collaborative editing

---

ej2-asp-core-mvc/document-editor/collaborative-editing/overview.md
ej2-asp-core-mvc/document-editor/collaborative-editing/using-dot-net.md
ej2-asp-core-mvc/document-editor/collaborative-editing/using-redis-cache-asp-net.md

Adding platform name in collaborative editing file

897352: Adding plat from name in collaborative editing

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/toolbar.md

Updated the create custom toolbar sample

Updated the create custom toolbar sample

---

ej2-asp-core-mvc/gantt/global-local.md

Need to add locale list ss,sf,ff,fs  in the Gantt  Chart.
NA
None
NA
NA

910542 :locale

---

ej2-asp-core-mvc/code-snippet/color-picker/show-recent-color/razor
ej2-asp-core-mvc/code-snippet/color-picker/show-recent-color/show-recent-color.cs
ej2-asp-core-mvc/code-snippet/color-picker/show-recent-color/tagHelper
ej2-asp-core-mvc/color-picker/how-to/show-recent-color.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

910776: Color Picker new UG sample

910776: Color Picker new UG sample

---

ej2-asp-core-mvc/spreadsheet/formatting.md

Description:
Need to port the culture-based number formats globalization stability support with preview samples to all the platforms in Spreadsheet.
Task Link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/911245
Content Location: https://ej2.syncfusion.com/documentation/spreadsheet/formatting#culture-based-number-formatting

documentation(EJ2-911245): Port the Culture-based number formats Globalization stability support to all the platforms in Spreadsheet

---

ej2-asp-core-mvc/spreadsheet/formatting.md

Description:
Need to port the culture-based number formats globalization stability support with preview samples to all the platforms in Spreadsheet.
Task Link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/911245
Content Location: https://ej2.syncfusion.com/documentation/spreadsheet/formatting#culture-based-number-formatting

documentation(EJ2-911245): Port the Culture-based number formats Globalization stability support to all the platforms in Spreadsheet 

---

ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/accessibility.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/accessibility.md

Added new documentation for Keyboard Interaction feature.

909653: Documenting the Key-interaction feature in hotfix branch.

---

ej2-asp-core-mvc/kanban/EJ2_ASP.NETCORE/getting-started.md

-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/3321|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187689/|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B1AEC8B02-054F-41E4-A9CF-1E907D8651D6%7D&file=Faith-%20Coverage.xlsx&action=default&mobileredirect=true&ovuser=77f1fe12-b049-4919-8c50-9fb41e5bb63b%2Cfaithatienoa%40syncfusion.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDA4MDIxMjAwOCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D|
|-- | -- |
|Changed-Redirect link | To avoid …

SEO-189041-EJ2-Vue-document-editor-header-foote-Page-with-redirect-links

---

ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.MVC/pie-dough-nut.md
ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.NETCORE/pie-dough-nut.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/range-step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/stacked-step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/step-line.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/zooming.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/range-step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/stacked-step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/step-line.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/zooming.md

Added API links for Volume 3 features in the Chart and Accumulation Chart.

899297: Added API links for Volume 3 features in the Chart and Accumulation Chart.

---

ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.MVC/pie-dough-nut.md
ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.NETCORE/pie-dough-nut.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/range-step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/stacked-step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/step-line.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/zooming.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/range-step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/stacked-step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/step-line.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/zooming.md

Added API links for Volume 3 features in the Chart and Accumulation Chart.

891749: Added API links for Volume 3 features in the Chart and Accumulation Chart.

---

ej2-asp-core-mvc/image-editor/how-to/open-dialog.md

911047: Image Editor publishing failure resolving

911047: Image Editor publishing failure resolving

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/text-search.md

Provide the GitHub sample link in the UG documentation
Share the JIRA task which is attached with the requirement and specification document or directly share the document. 
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/910812
Provide task link.
Post the output screenshots if an UI is affected or added due to this feature.
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Draft the …

897679: provided the GitHub sample link in the TS UG documentation

---

ej2-asp-core-mvc/code-snippet/query-builder/globalization/localization/razor
ej2-asp-core-mvc/code-snippet/query-builder/globalization/localization/tagHelper
ej2-asp-core-mvc/query-builder/global-local.md

913460: Add localization for "Add Group/Condition" tooltip in all platform

913460: Add localization for "Add Group/Condition" tooltip in all platform

---

ej2-asp-core-mvc/code-snippet/spreadsheet/globalization-cs1/cultureController.cs

Need to add the culture-based value in the dataSource and the quantity column should be an integer so modify it with an integer value.
Changed the quantity value to an integer.
Culture-based formatted value updated in the data source.

documentation(EJ2-911245): Updated the sample data source

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/globalization.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/globalization.md

Description:
Updated missing localization keywords in MVC and CORE

912613: updated missing keywords in globalization

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/globalization.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/globalization.md

Description:
Added missing keyword in localization.

912613: updated missing keyword in localization

---

ej2-asp-core-mvc/code-snippet/document-editor/style-dialog/razor
ej2-asp-core-mvc/code-snippet/document-editor/style-dialog/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor/styles-dialog/razor
ej2-asp-core-mvc/code-snippet/document-editor/styles-dialog/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor/table-of-contents-dialog/razor
ej2-asp-core-mvc/code-snippet/document-editor/table-of-contents-dialog/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor/table-options-dialog/razor
ej2-asp-core-mvc/code-snippet/document-editor/table-options-dialog/tagHelper
ej2-asp-core-mvc/code-snippet/document-editor/table-properties-dialog/razor
ej2-asp-core-mvc/code-snippet/document-editor/table-properties-dialog/tagHelper

912808: Added fix for the dialog components in the dialog page.

912808: Added fix for the dialog components in the dialog page.

---

ej2-asp-core-mvc/ribbon/EJ2_ASP.MVC/events.md
ej2-asp-core-mvc/ribbon/EJ2_ASP.NETCORE/events.md

Need to expose the overflow popup events usages in the ribbon control
NA
Exposed the overflow popup events usages in the ribbon control
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/911883
NA

documentation(911883): Exposed the overflow popup events usages in the ribbon control

---

ej2-asp-core-mvc/textarea/resize.md

Need to update the Resize Property Limitations on TextArea Documentation

915086: Need to update the Resize Property Limitations on TextArea Documentation

---

ej2-asp-core-mvc/uploader/EJ2_ASP.MVC/async.md
ej2-asp-core-mvc/uploader/EJ2_ASP.NETCORE/async.md

916797: Added more information for save and Remove Method

916797: Added more information for save and Remove Method

---

ej2-asp-core-mvc/file-manager/file-operations.md

Included the traversal changes in physical and node JS code block.

916694: Included the traversal changes in physical and node JS code block.

---

ej2-asp-core-mvc/code-snippet/pivot-table/performance-best-practices/performance-best-practices-cs2/Performance-best-practices2.cs

Need to include "Performance Best Practices" UG document for Pivot Table component in all EJ2 platforms as like blazor platform.
Link =>https://blazor.syncfusion.com/documentation/pivot-table/performance-best-practices

915680: Ensured live sample and updated the md file.

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/data-binding/remote-data.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/editing/persisting-data-in-server.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/excel-export/exporting-with-templates.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/filtering/filter-menu.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/filtering/filtering.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/grouping/lazy-load-grouping.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/pdf-export/exporting-with-templates.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/selection/selection.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/data-binding/remote-data.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/editing/persisting-data-in-server.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/excel-export/exporting-with-templates.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/filtering/filter-menu.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/filtering/filtering.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/grouping/lazy-load-grouping.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/pdf-export/exporting-with-templates.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/row/row.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/selection/selection.md

Updated image path of grid ug topics

914882: Update image path in Asp.net core and mvc documentation

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/data-binding/remote-data.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/editing/persisting-data-in-server.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/excel-export/exporting-with-templates.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/filtering/filter-menu.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/filtering/filtering.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/grouping/lazy-load-grouping.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/pdf-export/exporting-with-templates.md
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/selection/selection.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/data-binding/remote-data.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/editing/persisting-data-in-server.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/excel-export/exporting-with-templates.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/filtering/filter-menu.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/filtering/filtering.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/grouping/lazy-load-grouping.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/pdf-export/exporting-with-templates.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/selection/selection.md

Updated image path of grid ug topics in development branch

914882: Update image path of Asp.net core and mvc documentation in development

---

ej2-asp-core-mvc/uploader/EJ2_ASP.MVC/chunk-upload.md
ej2-asp-core-mvc/uploader/EJ2_ASP.NETCORE/chunk-upload.md

917671: Updated the latest code for chunk Uploading

917671: Updated the latest code for chunk Uploading

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/create-project.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/visual-studio-integration/create-samples.md

Need to update UG with NET9.0 changes for all below platforms:
1. Blazor
2. EJ2
3. MAUI
4. WPF
5. WinForms

UG changes for NET9.0 for all platforms

---

ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/spline-range-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/spline-range-area.md

Resolved the failure issues in ASP.NET Core and ASP.NET MVC.

827259: Resolved the failure issues in ASP.NET Core and ASP.NET MVC.

---

ej2-asp-core-mvc/uploader/EJ2_ASP.MVC/chunk-upload.md
ej2-asp-core-mvc/uploader/EJ2_ASP.NETCORE/chunk-upload.md

[UG documentation 920406](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/920406): How can I get the chunk-index and total-chunk values from the file uploader in Asp.net

920406: Added note for chunk-index and total-chunk

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/system-requirements.md
ej2-asp-core-mvc/common/EJ2_ASP.NETCORE/version-compatibility.md

I updated .NET 9 framework details in ASP.NET Core UG documentation.

Updated .NET 9 framework in ASP.NET Core UG documentation

---

ej2-asp-core-mvc/code-snippet/pivot-table/performance-best-practices/performance-best-practices-cs1/Performance-best-practices1.cs
ej2-asp-core-mvc/code-snippet/pivot-table/performance-best-practices/performance-best-practices-cs1/razor
ej2-asp-core-mvc/code-snippet/pivot-table/performance-best-practices/performance-best-practices-cs1/tagHelper
ej2-asp-core-mvc/code-snippet/pivot-table/performance-best-practices/performance-best-practices-cs2/Performance-best-practices2.cs
ej2-asp-core-mvc/code-snippet/pivot-table/performance-best-practices/performance-best-practices-cs2/razor
ej2-asp-core-mvc/code-snippet/pivot-table/performance-best-practices/performance-best-practices-cs2/tagHelper
ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/performance-best-practices.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/performance-best-practices.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to include "Performance Best Practices" UG document for Pivot Table component in all EJ2 platforms as like blazor platform.
Link =>https://blazor.syncfusion.com/documentation/pivot-table/performance-best-practices

900224: Need to update the Performance best practices file for the latest hotfix.

---

ej2-asp-core-mvc/treeview/how-to/manipulating-nodes.md

Changed the dynamically update node topic in nodes manipulation in TreeView.
The single space infront of Dynamically update node .
We have removed the space in that topic.
* [] Guidelines not followed. If yes, provide which guideline is not followed.
**Before:**
* []  All provided information are reviewed and ensured.

920583: Changed the dynamically update node topic in nodes manipulation in TreeView.

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/infinite-scroll.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/infinite-scroll.md

Updating the limitations for infinite scrolling feature.

925008: Updating the limitations for infinite scrolling

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/adaptive.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/adaptive.md

Added information to the adaptive docs in development branch

926205: Added information to the adaptive docs in development branch

---

ej2-asp-core-mvc/appbar/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/carousel/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/carousel/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/code-snippet/carousel/populating-items/partial-visible/razor
ej2-asp-core-mvc/code-snippet/carousel/populating-items/partial-visible/tagHelper
ej2-asp-core-mvc/code-snippet/carousel/populating-items/partial-visible/without-loop/razor
ej2-asp-core-mvc/code-snippet/carousel/populating-items/partial-visible/without-loop/tagHelper
ej2-asp-mvc-toc.html

Getting started code snippet issues resolved in carousel and appbar

Getting started code snippet issues resolved in carousel and appbar

---

ej2-asp-core-mvc/spreadsheet/cell-range.md

Description:
Task Link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/927003
Added the UG content for the custom data validation features.

documentation(EJ2-927003): Added UG content for custom data validation feature for spreadsheet.

---

ej2-asp-core-mvc/spreadsheet/formulas.md

Description:
Added UG content for Calculation mode support.
Task: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/926985

926985: UG content added for Calculation mode support

---

ej2-asp-core-mvc/spreadsheet/EJ2_ASP.MVC/getting-started-mvc.md

**Task Link**: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/927013
Ensure spreadsheet samples are created properly by following the UG Getting Started section.

927013: Ensure spreadsheet samples are created properly by following the UG Getting Started section. 

---

ej2-asp-core-mvc/carousel/accessibility.md

Include UG for disabling keyboard interaction in carousel

925705: Disabling keyboard interaction in carousel in UG was added.

---

ej2-asp-core-mvc/code-snippet/tab/swipe/razor
ej2-asp-core-mvc/code-snippet/tab/swipe/tagHelper
ej2-asp-core-mvc/tab/how-to/prevent-content-swipe-selection.md

Added the UG documentation for SwipeMode property in tab component.
NA
[925701](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/925701)
NA 
NA
NA
Confirm whether the ensured feature is in both Blazor Server and WASM.
Do the code changes cause any memory leak …

925701: Added the UG documentation for SwipeMode property.

---

ej2-asp-core-mvc/document-editor/collaborative-editing/overview.md

925314: Resolved collaborative sample link hf

925314: Resolved collaborative sample link hf

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/classic-layout.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/classic-layout.md

Updated classic layout content in Core and MVC UG documentation.

925503: Updated Classic layout content in core and mvc docs.

---

ej2-asp-core-mvc/code-snippet/spreadsheet/data-validation-cs2/dataValidation.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/data-validation-cs2/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/data-validation-cs2/tagHelper
ej2-asp-core-mvc/spreadsheet/cell-range.md

Description:
Task Link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/927003
Added the code sample for the custom data validation features.

documentation(EJ2-927003): Added Code sample for custom data validation feature.

---

ej2-asp-core-mvc/code-snippet/spreadsheet/calculation-cs1/calculationModeController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/calculation-cs1/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/calculation-cs1/tagHelper
ej2-asp-core-mvc/code-snippet/spreadsheet/calculation-cs2/calculationModeController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/calculation-cs2/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/calculation-cs2/tagHelper
ej2-asp-core-mvc/spreadsheet/formulas.md

**Task Link**: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/927123
Added sample to demonstrate the calculation mode in Spreadsheet.

927123: Added the samples for calculation mode feature for ASP .NET Core and MVC platform. 

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/form-designer/form-field-events.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/form-designer/form-field-events.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Update the form field event sample in the documentation.

EJ2 908096 Form Field Event

---

ej2-asp-core-mvc/code-snippet/schedule/clipboard/context-menu/data.cs
ej2-asp-core-mvc/code-snippet/schedule/clipboard/context-menu/razor
ej2-asp-core-mvc/code-snippet/schedule/clipboard/context-menu/tagHelper
ej2-asp-core-mvc/code-snippet/schedule/clipboard/normal-schedule/data.cs
ej2-asp-core-mvc/code-snippet/schedule/clipboard/normal-schedule/razor
ej2-asp-core-mvc/code-snippet/schedule/clipboard/normal-schedule/tagHelper
ej2-asp-core-mvc/code-snippet/schedule/clipboard/schedule-grid/data.cs
ej2-asp-core-mvc/code-snippet/schedule/clipboard/schedule-grid/razor
ej2-asp-core-mvc/code-snippet/schedule/clipboard/schedule-grid/tagHelper
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/clipboard.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/clipboard.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

drafted documentation content for scheduler clipboard property.

925691: drafted documentation content for scheduler clipboard property.

---

ej2-asp-core-mvc/code-snippet/file-manager/file-download-url/tagHelper
ej2-asp-core-mvc/code-snippet/file-manager/file-upload-url/tagHelper
ej2-asp-core-mvc/code-snippet/file-manager/getting-started/HomeController_core.cs
ej2-asp-core-mvc/code-snippet/file-manager/getting-started/tagHelper
ej2-asp-core-mvc/code-snippet/file-manager/image-preview/tagHelper
ej2-asp-core-mvc/code-snippet/file-manager/view/tagHelper
ej2-asp-core-mvc/file-manager/EJ2_ASP.NETCORE/getting-started.md

Getting started code snippet issues resolved in Asp.Net Core File Manager.

Getting started code snippet issues resolved in Asp.Net Core File Manager

---

ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/appearance.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/events.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/footer.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/globalization.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/header.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/load-on-demand.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/messages.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/templates.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/timebreak.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/timestamp.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/typing-indicator.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/appearance.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/events.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/globalization.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/header.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/load-on-demand.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/messages.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/templates.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/timebreak.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/timestamp.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/typing-indicator.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to map api link for chat UI component.
NA
None
NA
NA

documentation(927480): api link mapped for chatUI

---

ej2-asp-core-mvc/context-menu/template-and-multilevel-nesting.md

925769: Resolve UG staging issues completed for 2024 Vol 4 features

925769: Resolve UG staging issues completed for 2024 Vol 4 features

---

ej2-asp-core-mvc/chips/customization.md
ej2-asp-core-mvc/code-snippet/chips/template/default.cs
ej2-asp-core-mvc/code-snippet/chips/template/razor
ej2-asp-core-mvc/code-snippet/chips/template/tagHelper

Added UG documentation for Chip template feature

928256: Added UG documentation for chip template feature

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/data-binding/remote-data.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/data-binding/remote-data.md

Changed the behaviour of LoadChildOnDemand behaviour - Default value = true.

901689: Modify the LoadChild OnDemand behaviour content

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Reverting some changes 
(Briefly describe analysis of the feature. If there is an internal discussion on the Forum, provide the link.)
(Describe your code changes in detail for reviewers.)
(List out the areas are affected by your code changes.)
(Provide unit testing spec coverage details.)
(Provide new or update of API details)
/label ~bug

927515: Reverting Unwanted Changes

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/enable-local-storage.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/enable-local-storage.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Description:
UG Documentation on How to Enable Local Storage

927839: UG Documentation on How to enable local storage

---

ej2-asp-core-mvc/spreadsheet/open-save.md

Added UG content with client-side and server-side processing details for chunk response processing support.
Task: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/927766

927766: Documentation for chunk response processing feature added.

---

ej2-asp-core-mvc/spreadsheet/open-save.md

Added UG content with client-side and server-side processing details for chunk response processing support.
Task: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/927766

927766: Documentation for chunk response processing feature added

---

ej2-asp-core-mvc/code-snippet/spreadsheet/calculation-cs1/calculationModeController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/calculation-cs1/razor
ej2-asp-core-mvc/code-snippet/spreadsheet/calculation-cs2/calculationModeController.cs
ej2-asp-core-mvc/code-snippet/spreadsheet/calculation-cs2/razor

**Task Link**: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/927123
Added sample to demonstrate the calculation mode in Spreadsheet.

927123: Corrected the MVC code snippets for Calculation mode.

---

ej2-asp-core-mvc/code-snippet/schedule/clipboard/schedule-grid/razor
ej2-asp-core-mvc/code-snippet/schedule/clipboard/schedule-grid/tagHelper
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/clipboard.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/clipboard.md

modified documentation content for scheduler clipboard property.

925691: modified documentation content for scheduler clipboard property.

---

ej2-asp-core-mvc/listview/style.md

Corrected the css code snippet for selected item customization in Angular ListView component.

905715: Corrected css code snippet in Syncfusion ListView component.

---

ej2-asp-core-mvc/document-editor/find-and-replace.md

930846: Added backward selection code for replace in Core and MVC

930846: Added backward selection code for replace in Core and MVC

---

ej2-asp-core-mvc/document-editor/security-advisories.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

921700: Added Security advisories page in Core and MVC

921700: Added Security advisories page in Core and MVC

---

ej2-asp-core-mvc/code-snippet/spreadsheet/globalization-cs1/razor

Check and resolve the preview sample failures of Typescript and Javascript documentation.
Task link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/932704

932704: Corrected the code snippets in Spreadsheet MVC documentation.

---

ej2-asp-core-mvc/grid/EJ2_ASP.MVC/paging.md

-- | --
|Task Category | Site Audit work- Duplicate H1 and title|
|Content Task Link/Mail Screenshot |![image](https://github.com/user-attachments/assets/0202ce61-d540-4a1e-be20-673d4478dd5c)|
|Hotfix |https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/3766 |
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/195166|
|Work link https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B88556AA0-E423-4333-BBC5-6F0CE7494E0B%7D&file=Duplicate%20H1%20and%20Title.xlsx&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&action=default&mobileredirect=true|
|-- | -- |
| Modified title | To improve the performance of our page|

SEO-195166-EJ2-ASP.NET-MVC-Grid--Paging-Duplicate-H1-and-title

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/virtual-scroll.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/virtual-scroll.md

Updated Limitations for row and column virtualization in virtual-scroll.md for both mvc and core platforms

932741: Added Limitations to Row virtualization and column virtualization seperately 

---

ej2-asp-core-mvc/code-snippet/tree-grid/getting-start-mvc/error-handling/razor
ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/getting-started-mvc.md

**Corrected <script> tags:** Removed extra spaces inside the opening and closing <script> tags to prevent rendering errors.
**Updated file paths:** Fixed incorrect paths for styles and scripts. Changed ~/Pages/Shared/_Layout.cshtml to the correct path ~/Views/Shared/_Layout.cshtml.

933516 mvc

---

ej2-asp-core-mvc/code-snippet/listbox/drag-drop/dual-drag/taghelper

Correction in dual listbox with drag and drop sample code of listbox.

324496: Correction in dual listbox with drag and drop sample code of listbox.

---

ej2-asp-core-mvc/diagram/EJ2_ASP.NETCORE/getting-started-with-Layout.md
ej2-asp-core-mvc/diagram/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-toc.html

Updated the 'Getting Started' section in the diagram documentation to include instructions for both Visual Studio and Visual Studio Code environments.

933689: Core Application Getting Started Update

---

ej2-asp-core-mvc/code-snippet/slider/buttons/tagHelper
ej2-asp-core-mvc/code-snippet/slider/custom-bar/tagHelper
ej2-asp-core-mvc/code-snippet/slider/custom-limits/tagHelper
ej2-asp-core-mvc/code-snippet/slider/custom-ticks/tagHelper
ej2-asp-core-mvc/code-snippet/slider/numeric-value/tagHelper
ej2-asp-core-mvc/code-snippet/slider/reversible-slider/tagHelper
ej2-asp-core-mvc/code-snippet/slider/tooltip/tagHelper
ej2-asp-core-mvc/code-snippet/slider/types/HomeController.cs
ej2-asp-core-mvc/code-snippet/slider/types/tagHelper
ej2-asp-core-mvc/range-slider/EJ2_ASP.MVC/ej1-api-migration.md
ej2-asp-core-mvc/range-slider/EJ2_ASP.NETCORE/ej1-api-migration.md
ej2-asp-core-mvc/range-slider/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/range-slider/accessibility.md
ej2-asp-core-mvc/range-slider/how-to/customize-slider-bar.md
ej2-asp-core-mvc/range-slider/how-to/customize-slider-limits.md
ej2-asp-core-mvc/range-slider/how-to/customize-slider-thumb.md
ej2-asp-core-mvc/range-slider/how-to/customize-slider-ticks-label.md
ej2-asp-core-mvc/range-slider/how-to/date-range-slider.md
ej2-asp-core-mvc/range-slider/how-to/form-slider-with-form-validator.md
ej2-asp-core-mvc/range-slider/how-to/numeric-range-slider.md
ej2-asp-core-mvc/range-slider/how-to/reversible-slider.md
ej2-asp-core-mvc/range-slider/how-to/show-slider-from-hidden-state.md
ej2-asp-core-mvc/range-slider/how-to/time-range-slider.md
ej2-asp-core-mvc/range-slider/limits.md
ej2-asp-core-mvc/range-slider/orientation.md
ej2-asp-core-mvc/range-slider/overview.md
ej2-asp-core-mvc/range-slider/style.md
ej2-asp-core-mvc/range-slider/ticks.md
ej2-asp-core-mvc/range-slider/tooltip.md
ej2-asp-core-mvc/range-slider/types.md

934883: Test and resolve issues in UG all sections - ASP core Range Slider control.

934883: Test and resolve issues in UG all sections - ASP core Range Slider control.

---

ej2-asp-core-mvc/document-editor/shapes.md

378273: Updated shape support highlighted in Notes

378273: Updated shape support highlighted in Notes in Core and MVC

---

ej2-asp-core-mvc/document-editor/EJ2_ASP.NETCORE/getting-started-core.md

932523: Added video for getting started in Core

932523: Added video for getting started in Core

---

ej2-asp-core-mvc/tree-grid/EJ2_ASP.MVC/virtual-scroll.md
ej2-asp-core-mvc/tree-grid/EJ2_ASP.NETCORE/virtual-scroll.md

In virtualization Ug virtual-scroll file added checkbox selection limitation

875454:  Added limitation in Virtualization that doesn't support for checkbox selection

---

ej2-asp-core-mvc/file-manager/localization.md

939109: Added localization content

---

ej2-asp-core-mvc/code-snippet/schedule/appointments/custom-fields/data.cs
ej2-asp-core-mvc/code-snippet/schedule/appointments/custom-fields/razor
ej2-asp-core-mvc/code-snippet/schedule/appointments/custom-fields/tagHelper

IsBlock field mapping is missed in UG - Resolved

916469: IsBlock field mapping is missed in UG - Resolved

---

ej2-asp-core-mvc/file-manager/EJ2_ASP.MVC/file-system-provider.md
ej2-asp-core-mvc/file-manager/EJ2_ASP.NETCORE/file-system-provider.md

941511: Core and MVC- Removed the MVC file provider topic from File providers section in File Manager

941511: Core and MVC- Removed the MVC file provider topic from File providers section in File Manager

---

ej2-asp-core-mvc/image-editor/resize.md

941529: ImageEditor component IsAspectRadio need to explain for resize method

941529: ImageEditor component IsAspectRadio need to explain for resize method

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/nuget-packages.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/resolve-pdfium-issue.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/getting-started-with-server-backed.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/extract-text-using-text-collections.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/extract-text.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/install-packages.md

Description:
Updated NuGet Packages to Common Syncfusion.EJ2.PdfViewer.AspNet.Core

942172: Updated nugget packages

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/nuget-packages.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/resolve-pdfium-issue.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/getting-started-with-server-backed.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/extract-text-using-text-collections.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/extract-text.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/install-packages.md

Description:
Updated NuGet Packages to Common Syncfusion.EJ2.PdfViewer.AspNet.Core

942172: Update nugget Changes

---

ej2-asp-core-mvc/gantt/pdf-export/customize-pdf-export.md

The conditional formatting topic code snippet was modified and updated.
Before : 
After; 
None
NA
NA

937002: content modified

---

ej2-asp-core-mvc/uploader/EJ2_ASP.NETCORE/getting-started.md

-- | --
|Task Category | Coverage Issues page with redirect links|
|Content Task Link/Mail Screenshot |NA|
|Hotfix | https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/3933|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/197806|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BC7946AB1-0EE7-4CD1-8129-50040FF5758C%7D&file=Book.xlsx&action=default&mobileredirect=true&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1740465739326&web=1|
|-- | -- |
| Worked on redirect links | To avoid redirect links hence improving the performance of our page| …

SEO-197806-EJ2-ASP.NET-CORE-uploader-Page-with-redirect-links

---

ej2-asp-core-mvc/EJ2_ASP.MVC/introduction.md

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>
<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr;border-width:100%'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr'>
-- | --
Task Link | IN -   198113 Updating Banner Content in Documentation
Feature description | To   update the content in the overview pages
Analysis and design | N/A
Output screenshots | N/A
Areas affected and ensured | Changes …

Update banner Dev

---

ej2-asp-core-mvc/EJ2_ASP.MVC/introduction.md

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>
<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr;border-width:100%'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr'>
-- | --
Task Link | IN -   198113 Updating Banner Content in Documentation
Feature description | To   update the content in the overview pages
Analysis and design | N/A
Output screenshots | N/A
Areas affected and ensured | Changes …

Update Banner Hotfix

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/form-support.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/toolbar.md

944703: Video added

---

ej2-asp-core-mvc/barcode/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/barcode/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/barcode/barcodeGenerator.md
ej2-asp-core-mvc/barcode/datamatrixgenerator.md
ej2-asp-core-mvc/barcode/export.md
ej2-asp-core-mvc/barcode/qrcodegenerator.md

Reverts syncfusion-content/ej2-asp-core-mvc-docs#3958

944377: Revert  Added trademark

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/prevent-cross-site-scripting.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/prevent-cross-site-scripting.md

897361: Failure resolved

---

ej2-asp-core-mvc/code-snippet/grid/columns/template-aria-label/razor
ej2-asp-core-mvc/code-snippet/grid/columns/template-aria-label/tagHelper
ej2-asp-core-mvc/code-snippet/grid/columns/template-aria-label/template-aria-label.cs
ej2-asp-core-mvc/grid/EJ2_ASP.MVC/columns/column-template.md
ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/column-template.md

Included the Aria Label property for the template columns topic in Core and MVC documentation

946042: Included the Aria Label property for the template columns topic

---

ej2-asp-core-mvc/gantt/managing-tasks/splitting-and-merging-tasks.md

- [Task-945801](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/945801) - Remove Limitation for Split Task in All Platforms
The Gantt chart now supports split tasks for the resource view across all platforms. The existing documentation and codebase currently impose a limitation that split tasks are unsupported in this scenario. This limitation must be removed to reflect the updated functionality.
Update the documentation  to remove the content reflecting the unsupported status of split tasks in the resource view, as the Gantt chart now supports this functionality.
* [NA] 
* [ NA] 
If yes, provide the …

945801:  Remove Limitation for Split Task in All Platforms

---

ej2-asp-core-mvc/EJ2_ASP.MVC/introduction.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/introduction.md
ej2-asp-core-mvc/toast/EJ2_ASP.NETCORE/timeout.md

-- | --
|Task Category | Coverage Issues page with redirect links|
|Content Task Link/Mail Screenshot |![image](https://github.com/user-attachments/assets/8f1c0a8a-f426-4a88-9184-ba7953ce2ac6)|
|Hotfix |https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/3970|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/197453|
|Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B8D09F47E-B62B-44E2-8EFE-FF4F4B48899B%7D&file=Page%20with%20redirect.xlsx&nav=MTVfezVFRUUwODE1LTQzMzgtNDE0NC04OEFELTg4REE3MkVDNEY1NX0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&action=default&mobileredirect=true|
|-- | -- |
| Worked on redirect links | To …

Seo 197453  ej2 asp.net core toast page with redirect links

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/exec-command.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/exec-command.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

877792: modified heading of executeCommand and included insertAudio & insertVideo in RichTextEditor(Mvc/Dev)

877792: modified heading of executeCommand and included insertAudio & insertVideo in RichTextEditor(Mvc/Dev)

---

ej2-asp-core-mvc/code-snippet/file-manager/upload-feature-cs1/razor
ej2-asp-core-mvc/code-snippet/file-manager/upload-feature-cs1/tagHelper
ej2-asp-core-mvc/file-manager/upload.md

844015: Resolved corrections in How to prevent external drag and drop" section in the File Manager control.

844015: Resolved corrections in How to prevent external drag and drop" section in the File Manager control.

---

ej2-asp-core-mvc/file-manager/how-to/pass-custom-value-to-server.md

906899: Core MVC How to pass custom value from client to server side in the File Manager component.

906899: Core MVC How to pass custom value from client to server side in the File Manager component.

---

ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/classic-layout.md
ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/classic-layout.md

Need to update the UG document for the Classic layout

947317: Need to update the UG document for the Classic layout

---

ej2-asp-core-mvc/code-snippet/speech-to-text/appearance/buttonSettings/tagHelper

Need to update iconPosition property.
NA.
None
NA
NA

Docs(943869): Need to update iconPosition property.

---

ej2-asp-core-mvc/code-snippet/pivot-table/paging/template/razor
ej2-asp-core-mvc/code-snippet/pivot-table/paging/template/tagHelper

Updating UG Documentation paging template preview samples

947507: Need to update UG Documentation paging template preview samples

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/relative-url/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/relative-url/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/relative-url/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/link.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/link.md

382945: Added enableAutoUrl section (Absolute and Relative Url) in RTE(Mvc)

382945: Added enableAutoUrl section (Absolute and Relative Url) in RTE(Mvc)

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/relative-url/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/relative-url/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/relative-url/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/link.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/link.md

382945: Added enableAutoUrl section (Absolute and Relative Url) in RTE(Mvc/Dev)

382945: Added enableAutoUrl section (Absolute and Relative Url) in RTE(Mvc/Dev)

---

ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/appearance.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/events.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/globalization.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/speech-recognition.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.NETCORE/appearance.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.NETCORE/events.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.NETCORE/getting-started.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.NETCORE/globalization.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.NETCORE/speech-recognition.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Need to add API links for all the properties in SpeechToText.
NA.
None
NA
NA

documentation(943869): Need to add API links for all the properties in SpeechToText.

---

ej2-asp-core-mvc/code-snippet/schedule/overlap/overlap-actionbegin/data.cs
ej2-asp-core-mvc/code-snippet/schedule/overlap/overlap-actionbegin/razor
ej2-asp-core-mvc/code-snippet/schedule/overlap/overlap-actionbegin/tagHelper
ej2-asp-core-mvc/code-snippet/schedule/overlap/overlap-normal/data.cs
ej2-asp-core-mvc/code-snippet/schedule/overlap/overlap-normal/razor
ej2-asp-core-mvc/code-snippet/schedule/overlap/overlap-normal/tagHelper
ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/appointments.md
ej2-asp-core-mvc/schedule/EJ2_ASP.NETCORE/appointments.md

Include UG for allowOverlap events.

947714: Include UG for allowOverlap events.

---

ej2-asp-core-mvc/EJ2_ASP.MVC/introduction.md
ej2-asp-core-mvc/EJ2_ASP.NETCORE/introduction.md

Added new component list in Core and MVC UG documentation.
Accumulation Chart
AI AssistView
Chat UI
3D Chart
3D Circular Chart
DropDownTree
Markdown Editor
Multicolumn ComboBox
OTP Input
Predefined Dialog
Range Navigator
Ribbon
Speech To Text
Stepper
Timeline
TextArea

949653: Added new component list in Core and MVC UG documentation

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/extract-text-completed.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/extract-text-option.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/extract-text.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/find-text-async.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/extract-text-completed.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/extract-text-option.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/extract-text.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/find-text-async.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Description:
Extract Text Option UG documentation

948910: Extract Text Option

---

ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/stacked-column.md

Added UG sample for newly added features.

949742: Added UG sample for newly added features.

---

ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.MVC/title-and-sub-title.md
ej2-asp-core-mvc/accumulation-chart/EJ2_ASP.NETCORE/title-and-sub-title.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/bar.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/column.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/range-column.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/stack-bar100.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/stack-column100.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/stacked-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/stacked-bar.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/stacked-column.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/stacked-line.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/stacked-step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/chart-types/waterfall.md
ej2-asp-core-mvc/chart/EJ2_ASP.MVC/cross-hair-and-track-ball.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/bar.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/column.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/range-column.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/stack-bar100.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/stack-column100.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/stacked-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/stacked-bar.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/stacked-column.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/stacked-line.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/stacked-step-area.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/chart-types/waterfall.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/cross-hair-and-track-ball.md

Addressed the review changes in the UG sample for newly added features.

949742: Addressed the review changes in the UG sample for newly added features.

---

ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/filtering/excel-like-filter.md

-- | --
|Task Category | Coverage Issues page with redirect links|
|Content Task Link/Mail Screenshot |NA|
|Hotfix |https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/4151 |
|Ticket/Task link |https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/200180 |
|Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B9EB214A4-8251-4316-86D1-6887ABE8B482%7D&file=[pages_with_only_one_internal_link_20250409.xlsx](https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B9EB214A4-8251-4316-86D1-6887ABE8B482%7D&file=pages_with_only_one_internal_link_20250409.xlsx&action=default&mobileredirect=true)&action=default&mobileredirect=true|
Changes …

SEO-200180--EJ2-ASP.NET-CORE-grid-Page-with-redirect-links

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/tools/built-in-tools.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/tools/text-formatting.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/tools/built-in-tools.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/tools/text-formatting.md

951777: Corrected Heading and image path - Mvc

951777: Corrected Heading and image path - Mvc

---

ej2-asp-core-mvc/EJ2_ASP.NETCORE/installation/install-nuget-packages.md

Hi @Gowthaman
|--|--|
|Task Category|Coverage-Blazor- Page with redirect|
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix PR|https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/4175|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/199759|
|Excel/SharePoint link| https://syncfusion-my.sharepoint.com/:x:/p/mallika_kannan/EXPwlIhDQChLmSunvUytnxABKxuyoG9PuYeebq7QzVe4YA?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1745819292740&web=1|
|Changes made|Reason for changes|
|--|--|
|Changed redirect link  |  To avoid redirection and providing direct links    |     
Regards,
Hillary

SEO-199759-aspnetcore-installation-docs

---

ej2-asp-core-mvc/uploader/EJ2_ASP.NETCORE/async.md

Docs Task - https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/905249

905249: Uploader Changing titles to saving and returning responses

---

ej2-asp-core-mvc/code-snippet/document-editor/custom-toolbar/razor
ej2-asp-core-mvc/code-snippet/document-editor/custom-toolbar/tagHelper

378201: Added wrap text for toolbar on CoreMVC

378201: Added wrap text for toolbar on CoreMVC

---

ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/appearance.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/events.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/globalization.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/methods.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/security.md
ej2-asp-core-mvc/speech-to-text/EJ2_ASP.MVC/speech-recognition.md

-- | --
|Task Category | Post Release|
|Content Task Link/Mail Screenshot |NA|
|Hotfix |https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/4173| 
|Ticket/Task link |https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/200901|
|-- | -- |
|Modified title and description| To improve the performance of the page|
|Changed redirect link|To avoid redirection error|
Regards,
Yvone.

SEO-200901 ASP.NET MVC Speech to Text UG

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/getting-started.md

957433: Added the Controller code in the Getting started documentation of RichTextEditor

957433: Added the Controller code in the Getting started documentation of RichTextEditor

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/getting-started.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/getting-started.md

957433: Added the Controller code in the Getting started documentation of RichTextEditor-Hotfix

957433: Added the Controller code in the Getting started documentation of RichTextEditor-Hotfix

---

ej2-asp-core-mvc/file-manager/how-to/pass-custom-value-to-server.md

Added a note section when setting args.useFormPost = false in the FileManager component.

958054: Need to add a note section when setting args.useFormPost = false in the FileManager component.

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/insert-image-media/insert-images.md

956287: Updated the insertImageSettings: Add the new image types to the allowedTypes array.

956287: Updated the insertImageSettings: Add the new image types to the allowedTypes array.

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/globalization.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/globalization.md

Description:
Updated Globalization for "No Match"

960014: Updated Globalization for "No Match"

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/globalization.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/globalization.md

Description:
Updated Latest globaliazation

960014: Updated Latest Localization

---

ej2-asp-core-mvc/code-snippet/gantt/pdf-export/showhidecolumns/razor
ej2-asp-core-mvc/code-snippet/gantt/pdf-export/showhidecolumns/tagHelper

In the PDF export section, we have a topic *Show or hide columns on exported PDF*. However, when following the code given in that section, columns are not hidden. Need to modify that section with the below approach in all platforms.
None
NA
NA

378990: pdf code modified

---

ej2-asp-core-mvc/code-snippet/kanban/tooltip/tagHelper

963051: Corrected the code in Kanban tooltip template section in UG Documentation

963051: Corrected the code in Kanban tooltip template section in UG Documentation

---

ej2-asp-core-mvc/code-snippet/kanban/tooltip/tagHelper

963051: Corrected the code in Kanban tooltip template section in UG Documentation-Dev

963051: Corrected the code in Kanban tooltip template section in UG Documentation-Dev

---

ej2-asp-core-mvc/spreadsheet/open-save.md
ej2-asp-core-mvc/spreadsheet/performance-best-practices.md

Need to add section to demonstrate the workbook parse options support
**Task Link:** https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/964194
**Content UG Location:** https://github.com/syncfusion-content/ej2-asp-core-mvc-docs

documentation(EJ2-964194): Need to add section to demonstrate the workbook parse options support

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/image-quick-toolbar/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/table-quick-toolbar/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/text-quick-toolbar/controller.cs

Enhance the quick toolbar content in the Rich Text Editor documentation
[Task 965566: Enhance the quick toolbar content in the Rich Text Editor documentation](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/965566)
Added the documentation for typescript and javascript sample
* If any other reason, provide the details here.
Test cases did not cover this specific use case.
No
No
Added the documentation for typescript and javascript sample
-Ensured with tests.
NA
No
No
* [] All provided information are reviewed and ensured.

965566: Enhance the quick toolbar content in the Rich Text Editor documentation

---

ej2-asp-core-mvc/spreadsheet/docker-deployment.md

Description:
Need to update the Docker details based on .Net 8 version.
Content link - https://ej2.syncfusion.com/documentation/spreadsheet/docker-deployment
Task link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/956720

956720: Docker UG details update

---

ej2-asp-core-mvc/chart/EJ2_ASP.MVC/lastvaluelabel.md
ej2-asp-core-mvc/chart/EJ2_ASP.NETCORE/lastvaluelabel.md
ej2-asp-core-mvc/code-snippet/chart/last-value-label-customization/lastValueLabelCustomization.cs
ej2-asp-core-mvc/code-snippet/chart/last-value-label-customization/razor
ej2-asp-core-mvc/code-snippet/chart/last-value-label-customization/tagHelper
ej2-asp-core-mvc/code-snippet/chart/last-value-label/lastValueLabel.cs
ej2-asp-core-mvc/code-snippet/chart/last-value-label/razor
ej2-asp-core-mvc/code-snippet/chart/last-value-label/tagHelper
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Added lastvaluelabel  in chart UG documentation
Added lastvaluelabel in chart UG documentation
NA
NA
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive and worst-case test-cases.   
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is …

935608: To add a content for lastvaluelabel in MVC and Core documentation.

---

ej2-asp-core-mvc/code-snippet/rich-text-editor/clear-undo-redo/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/clear-undo-redo/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/clear-undo-redo/tagHelper
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-bottom/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-bottom/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-bottom/tagHelper
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-popup/controller.cs
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-popup/razor
ej2-asp-core-mvc/code-snippet/rich-text-editor/toolbar-popup/tagHelper
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/toolbar/toolbar-position.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/toolbar/toolbar-types.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.MVC/undo-redo.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/toolbar/toolbar-position.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/toolbar/toolbar-types.md
ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/undo-redo.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

* [950709](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/950709) - Create UG Documentation for bottom toolbar, popup toolbar an clear undo redo stack Support in All Platforms
Added the documentation for typescript and javascript sample
* If any other reason, provide the details here.
Test cases did not cover this specific use case.
No
No
Added the documentation for typescript and javascript sample
-Ensured with tests.
NA
No
No
* [] All provided information are reviewed and ensured.

950709: Added the documentation for the popup , bottom toolbar and  clearUndoRedo method

---

ej2-asp-core-mvc/file-manager/how-to/pass-custom-value-to-server.md

Added get Image feature UG documentation
Added get Image feature UG documentation
NA
NA
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive and worst-case test-cases.    …

Updated UG document for new feature in get image

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/how-to/enable-text-selection.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/enable-text-selection.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

Description:
UG Documentation on How to Dynamically enable or disable text selection

966016: UG Documentation on How to Dynamically enable or disable text selection

---

ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/getting-started-with-server-backed.md
ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/getting-started-with-server-backed.md

Description:
Version and link Updated for SkiaSharp NativeAssets Linux

969719: Version and link Updated for SkiaSharp NativeAssets Linux

---

ej2-asp-core-mvc/gantt/task-constraints.md

Resolving liquid warning syntax error in Constraint Sample
None
NA
NA

971748 - Resolved cli error in mvc

---

ej2-asp-core-mvc/document-editor/styles.md
ej2-asp-core-mvc/document-editor/text-format.md

955200: Added the change case and get styles

955200: Added the change case and get styles

---

ej2-asp-core-mvc/document-editor/form-fields.md

857401: Added the form field shading in form field file in core/mvc

857401: Added the form field shading in form field file

---

ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

-  Remove Excel list from Core and MVC

976406: Remove Excel list from Core and MVC

---

ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/messages.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/messages.md

updating of naming in preview for Markdown support in ChatUI component in Core and Mvc
Azure Task URL: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/972430
NA
NA
NA
NA
Confirm whether the ensured feature is in both Blazor Server and WASM.
Do the code …

972430: updating of naming in preview

---

ej2-asp-core-mvc/block-editor/EJ2_ASP.MVC/built-in-blocks/code-block.md
ej2-asp-core-mvc/block-editor/EJ2_ASP.MVC/built-in-blocks/embed.md
ej2-asp-core-mvc/block-editor/EJ2_ASP.MVC/built-in-blocks/inline-content.md
ej2-asp-core-mvc/block-editor/EJ2_ASP.MVC/built-in-blocks/list-types.md
ej2-asp-core-mvc/block-editor/EJ2_ASP.MVC/built-in-blocks/typography.md
ej2-asp-core-mvc/block-editor/EJ2_ASP.NETCORE/built-in-blocks/code-block.md
ej2-asp-core-mvc/block-editor/EJ2_ASP.NETCORE/built-in-blocks/embed.md
ej2-asp-core-mvc/block-editor/EJ2_ASP.NETCORE/built-in-blocks/inline-content.md
ej2-asp-core-mvc/block-editor/EJ2_ASP.NETCORE/built-in-blocks/list-types.md
ej2-asp-core-mvc/block-editor/EJ2_ASP.NETCORE/built-in-blocks/typography.md

Need to Update UG content against
[976097](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/976097)
Updated the issues after staging for the UG documentation
NA
NA
NA
NA
Confirm whether the ensured feature is in both Blazor Server and WASM.
Do the code changes …

976110: Updated the changes against UG staging

---

ej2-asp-core-mvc/code-snippet/gantt/editing/task-dialog-default-value/razor
ej2-asp-core-mvc/code-snippet/gantt/editing/task-dialog-default-value/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/editing/task-dialog-default-value1/razor
ej2-asp-core-mvc/code-snippet/gantt/editing/task-dialog-default-value1/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/editing/task-dialog-default-value2/razor
ej2-asp-core-mvc/code-snippet/gantt/editing/task-dialog-default-value2/tagHelper
ej2-asp-core-mvc/code-snippet/gantt/editing/task-dialog-default-value3/razor
ej2-asp-core-mvc/code-snippet/gantt/editing/task-dialog-default-value3/tagHelper

[979683](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/979683): Modify additional params field in Editing task in the existing managing task UG Documentation
Modified the additional params in adddialogfields and editdialogfields in managing task column in asp core and asp mvc ug documentation.
NA
NA
Draft the test cases in excel and …

979683: Modify additional params field in Editing task in the existing managing task UG Documentation

---

ej2-asp-core-mvc/gantt/task-constraints.md
ej2-asp-core-toc.html

[979683](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/979683): Modify additional params field in Editing task in the existing managing task UG Documentation
Modified the additional params in adddialogfields and editdialogfields in managing task column in asp core and asp mvc ug documentation.
NA
NA
Draft the test cases in excel and …

Ej2 979683 modified task constraints

---

ej2-asp-core-mvc/code-snippet/diagram/shapes/HTML-Template/HTML-Node-With-Template.cshtml
ej2-asp-core-mvc/code-snippet/diagram/shapes/native-Template/SVG-Node-With-Template.cshtml
ej2-asp-core-mvc/diagram/shapes.md

978765: Provide UG documentation for HTML/SVG Template support - Phase 2
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/978765
Added mac keyboard support UG documentation
NA
NA
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive and worst-case test-cases.   
Mark 'Is …

978765: updated

---

ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/ai-integrations/gemini-integration.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/ai-integrations/openai-integration.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/ai-integrations/gemini-integration.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/ai-integrations/openai-integration.md

updated UG concerns in md file in the Core and MVC platform.
[974582](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/974582)
NA
NA
NA
NA
NA
Confirm whether the ensured feature is in both Blazor Server and WASM.
Do the code changes cause any memory leak and …

974582: updated UG concerns in md file

---

ej2-asp-core-mvc/rich-text-editor/EJ2_ASP.NETCORE/tools/styling-tools.md

983305: Included the youtube video in Styling tools section in ASP.Net Core documentation in RichTextEditor

983305: Included the youtube video in Styling tools section in ASP.Net Core documentation in RichTextEditor

---

ej2-asp-core-mvc/ai-assistview/EJ2_ASP.MVC/ai-integrations/gemini-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.MVC/ai-integrations/ollama-llm-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.MVC/ai-integrations/openai-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.NETCORE/ai-integrations/gemini-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.NETCORE/ai-integrations/ollama-llm-integration.md
ej2-asp-core-mvc/ai-assistview/EJ2_ASP.NETCORE/ai-integrations/openai-integration.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/bot-integrations/integration-with-bot-framework.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.MVC/bot-integrations/integration-with-dialogflow.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/bot-integrations/integration-with-bot-framework.md
ej2-asp-core-mvc/chat-ui/EJ2_ASP.NETCORE/bot-integrations/integration-with-dialogflow.md
ej2-asp-core-toc.html
ej2-asp-mvc-toc.html

updated UG concerns in Md file :
gemini ai
azure open ai
bot integration

updated latest concerns in UG
